### ISSUE TITLE
Failed to build gem native extension / libiconv is missing

### ISSUE THREAD

**Issue by AnthonyMyatt** [KrauseFx/fastlane#10]
Before being able to install fastlane, I had to manually install nokogiri using the following command:

sudo gem install nokogiri -- --use-system-libraries --with-xml2-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2

--use-system-libraries allows the install to use the OS X version of libiconv.
--with-xml2= tells it where to find libxml2

Other solutions I found online involved installing homebrew, which I didn't want to do.

**Comment by KrauseFx** [comment]
Building `nokogiri` manually is a pain and sometimes quite tricky to do, that's why I recommend using `homebrew`. Is there a reason you don't want to use it?

**Comment by KrauseFx** [comment]
I'll close this issue for now, let me know if you need any help.
