### ISSUE TITLE
Allow Shenzhen Crashlytics ENV vars

### ISSUE THREAD

**Issue by dtrenz** [KrauseFx/fastlane#101]
The Shenzhen Crashlytics plugin supports ENV vars for:
- CRASHLYTICS_FRAMEWORK_PATH 
- CRASHLYTICS_API_TOKEN
- CRASHLYTICS_BUILD_SECRET

The fastlane Crashlytics action requires that all of these are sent in via hash parameter, which negates the ability to use ENV vars. The assert_valid_* methods in the fastlane action should be modified to check for ENV vars as part of the validation.

Reference: https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/plugins/crashlytics.rb

**Comment by KrauseFx** [comment]
I agree, that needs to be updated.
