### ISSUE TITLE
fastlane xctool call with system()

### ISSUE THREAD

**Issue by cakl** [KrauseFx/fastlane#105]
As there aren't different xctool-args files possible (for test, deploy etc.), I tried to call xctool with system:

```
lane :test do
  system("xctool test -workspace Strack.xcworkspace -scheme StrackTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO")
end
```

output:
```
$ fastlane test
INFO [2015-03-07 00:57:20.29]: Driving the lane 'test'
ERROR: Specified workspace doesn't exist: Strack.xcworkspace
```

The xctool command without fastlane works without problems. Do I have to specify a workspace for fastlane or is this a bug?

**Comment by KrauseFx** [comment]
The problem is probably the directory in which `fastlane` runs. You can add a `sh("pwd")` to get the directory. It is recommended to use `sh` instead of `system`.
The solution is, to just update the workspace to `../Strack.xcworkspace`. I hope that helps.
