### ISSUE TITLE
Going to download app metadata from iTunesConnect FATAL 

### ISSUE THREAD

**Issue by codesourse** [KrauseFx/fastlane#107]
INFO [2015-03-08 13:25:37.78]: Going to download app metadata from iTunesConnect
FATAL [2015-03-08 13:25:37.79]: Could not download metadata from iTunes Connect. Do you have special characters in your password (Like ' or ")?
FATAL [2015-03-08 13:25:37.79]: Error occured with the setup program! Reverting changes now!

anyone can help me?

**Comment by KrauseFx** [comment]
Does your password contain any special characters? There is an issue for that: https://github.com/KrauseFx/fastlane/issues/39

If not, is there any other error message shown? Is the xcode path set correctly?

**Comment by codesourse** [comment]
my password is very simple 

Going to download app metadata from iTunesConnect
FATAL [2015-03-09 17:22:40.79]: Could not download metadata from iTunes Connect. Do you have special characters in your password (Like ' or ")?
FATAL [2015-03-09 17:22:40.79]: Error occured with the setup program! Reverting changes now!
INFO [2015-03-09 17:22:40.79]: Deleting the 'fastlane' folder
/Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/app_metadata.rb:302:in `read': No such file or directory - /tmp/975018225.itmsp//metadata.xml (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/app_metadata.rb:302:in `parse_package'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/app_metadata.rb:66:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/app.rb:113:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/app.rb:113:in `metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/deliverfile/deliverfile_creator.rb:59:in `create_based_on_identifier'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.7.13/lib/deliver/deliverfile/deliverfile_creator.rb:31:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.16/lib/fastlane/setup.rb:80:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.16/lib/fastlane/setup.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.16/bin/fastlane:45:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.16/bin/fastlane:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.16/bin/fastlane:64:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
kjxdeMacBook-Pro:yyb kjx$

**Comment by KrauseFx** [comment]
Could you run `deliver init` instead of `fastlane init` and post the complete output?

**Comment by codesourse** [comment]
yes ,i can run "deliver init"

**Comment by KrauseFx** [comment]
Can you post the complete output?

**Comment by cvergeade** [comment]
Hello,
I think it is because your apple Id contains special characters.

**Comment by KrauseFx** [comment]
This should be fixed with the latest version :+1:
