### ISSUE TITLE
Document that xctool can also be used to archive as an alternative to 'ipa' (Shenzhen)

### ISSUE THREAD

**Issue by fatuhoku** [KrauseFx/fastlane#115]
~~I experienced problems with xcodebuild / Shenzhen~~ EDIT: I have since just run xcodebuild and my problems turned out to be provisioning profiles. Sigh.

But still, wouldn't it be great if instead of archiving with shenzhen, you could choose to archive with `xctool` and still benefit from `Deliverfile` understanding `ENV[IPA_OUTPUT_PATH]`?

Or does this already? Does this just need documentation?

**Comment by KrauseFx** [comment]
Does this help you? https://github.com/KrauseFx/fastlane/pull/114/files

Everything except of https://github.com/KrauseFx/fastlane/pull/113 is already released with the latest version.

**Comment by dtrenz** [comment]
@fatuhoku You can use the new [`xcodebuild`](https://github.com/dtrenz/fastlane/blob/xcodebuild-docs/Actions.md#xcodebuild) action to achieve this.

```ruby
  # Create an archive (./build-dir/MyApp.xcarchive)
  xcarchive

  # Export a signed binary (./build-dir/MyApp.ipa)
  xcexport
```

Full docs here: https://github.com/dtrenz/fastlane/blob/xcodebuild-docs/Actions.md#xcodebuild

**Comment by fatuhoku** [comment]
Ooh. @KrauseFx looks like a fair bit of customization; definitely looks good to me. I solved my problem (not related to IPA, in the end...) and so I think we can close this one. =] :beers:

**Comment by KrauseFx** [comment]
Great to hear :+1:
