### ISSUE TITLE
Support increment PATCH version (e.g. 'Z' in x.y.Z) of semantic version

### ISSUE THREAD

**Issue by fatuhoku** [KrauseFx/fastlane#118]
I've got a project that works with semantic versions like so:

![screen shot 2015-03-11 at 18 18 53](https://cloud.githubusercontent.com/assets/430233/6603623/256f5344-c81b-11e4-824b-c48068e67338.png)

The build number is set to `DEVELOPMENT` because I'm setting it to the count of git commits, as described here: http://stackoverflow.com/a/24750392/590767. So we can expect `CFBundleVersion` to look like `2532` or something when you actually do an Xcode build.

When I do a release with `fastlane`, more often than not, I intend only to increment the PATCH number (e.g. `0.7.0` -> `0.7.1`). It'd be great if `fastlane` could automate that!

**Comment by KrauseFx** [comment]
Why should `fastlane` change your app version? Not sure I understand the use case. Maybe you just want the build number to be updated? https://github.com/KrauseFx/fastlane/blob/master/Actions.md#increment_build_number

**Comment by serluca** [comment]
Hi @KrauseFx 

I was looking for something like this issue.
Usually, I work with gulp project and I really like how I can update the version number of my project with gulp (i.e. [gulp-release-task](https://www.npmjs.com/package/gulp-release-tasks) )

It would be nice to have an equivalent in fastlane.

**Comment by mtford90** [comment]
+1 e.g. would be nice for a "bump" lane for bumping version numbers in a similar way to what is achievable in js projects via a gulp file

**Comment by KrauseFx** [comment]
Thanks, this is now implemented :rocket:
