### ISSUE TITLE
[Feature] xcodebuild action build settings

### ISSUE THREAD

**Issue by bartoszj** [KrauseFx/fastlane#130]
It would be great if [xcodebuild action](https://github.com/KrauseFx/fastlane/blob/master/Actions.md#user-content-xcodebuild) allows to pass build settings like `CODE_SIGN_IDENTITY`, `PROVISIONING_PROFILE`, `JOBS`, or any other [build settings](https://developer.apple.com/library/ios/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html).

Maybe the format should looks like:

    xcodebuild(
      workspace: "...",
      scheme: "...",
      build_settings: {
        "CODE_SIGN_IDENTITY" => "iPhone Developer: ...",
        "PROVISIONING_PROFILE" => "...",
        "JOBS" => 16
      }
    )

**Comment by KrauseFx** [comment]
I agree, this looks pretty amazing. But in my experience, setting the provisioning profile from the command line does not work usually. I always have to set it in the project.

**Comment by KrauseFx** [comment]
@joshdholtz

**Comment by joshdholtz** [comment]
@KrauseFx Looks like you can :8ball: - http://stackoverflow.com/a/1180731. This is gunna change my life :rocket:

I can work on this while I am on the plane this morning :airplane:
