### ISSUE TITLE
[Issue] xcexport - incorrect export path

### ISSUE THREAD

**Issue by bartoszj** [KrauseFx/fastlane#138]
When archiving and exporting application to IPA file using:

```ruby
ENV["XCODE_BUILD_PATH"] = "./build"
xcarchive(
  workspace: "Project.xcworkspace",
  scheme: "Project",
)
xcexport()
```

It will create `Project.xcarchive` inside `build` folder, but it also creates `build.ipa` file inside project folder.

But when using a little bit different configration:
```ruby
ENV["XCODE_BUILD_PATH"] = "./build"
ENV["XCODE_SCHEME"] = "Project"
xcarchive(
  workspace: "Project.xcworkspace",
)
xcexport()
```

It will build `Project.xcarchive` and `Project.ipa` inside `build` folder.

The problem is with:
```ruby
# If not passed, construct export path from env vars
params[:export_path] ||= "#{build_path}#{scheme}"
```
The `scheme` parameter is not passed between XcodebuildAction actions but the archive path is saved between executions using `XCODEBUILD_ARCHIVE`. In my opinion scheme value should also be saved this way.

**Comment by KrauseFx** [comment]
@dtrenz Could you take a look at this?

**Comment by dtrenz** [comment]
Yeah, this is a problem.

@bartoszj: What if -- when no SCHEME is passed/set -- `xcexport` used the filename of the `*.xcarchive` as the filename of the IPA? That feels a bit tidier to me.

Example:
```ruby
ENV["XCODE_BUILD_PATH"] = "./build"

# produce ./build/Project.xcarchive
xcarchive(
  workspace: "Project.xcworkspace",
  scheme: "Project",
)

xcexport  # would produce ./build/Project.ipa
```

**Comment by bartoszj** [comment]
Agree. This is even simpler solution, more intuitive for the user.

**Comment by dtrenz** [comment]
OK - I'll get to work on this. Thanks for pointing this out.
