### ISSUE TITLE
Keep getting error on "fastlane init"

### ISSUE THREAD

**Issue by irvene2000** [KrauseFx/fastlane#143]
I've only just installed fastlane and tried to run "fastlane init" from my project dir which was just a default single view application. Reinstalling didn't seemed to help. Screenshot below:

![screen shot 2015-03-23 at 10 10 18 am](https://cloud.githubusercontent.com/assets/2285528/6782914/e469fbfa-d144-11e4-887b-727c960c70d6.png)

**Comment by cybertk** [comment]
Try to remove local fastline dir? with `rm -rf fastline`

**Comment by KrauseFx** [comment]
Thanks @cybertk. Just delete the `fastlane` folder, as the error message mentions, you already have a folder.
