### ISSUE TITLE
push_to_git_remote and commit_version_bump examples

### ISSUE THREAD

**Issue by KristopherGBaker** [KrauseFx/fastlane#148]
The push_to_git_remote and commit_version_bump examples listed at https://github.com/KrauseFx/fastlane/blob/master/Actions.md don't work as is for me.

For commit_version_bump, I had to change "xcodeproj_path" to "xcodeproj".

For push_to_git_remote, it ignored "local_branch" and "remote_branch".  I had to use "branch" instead.

**Comment by KrauseFx** [comment]
Maybe @lmirosevic could take a quick look?

**Comment by lmirosevic** [comment]
Will take a look ASAP

**Comment by KrauseFx** [comment]
Thanks @lmirosevic :+1:
