### ISSUE TITLE
[Feature] AppStore alias for deliver

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/fastlane#150]
It makes more sense from a user's perspective to provide an `appstore` action, which is just an alias for `deliver`, which doesn't allow the `:beta` parameter.

**Comment by joshdholtz** [comment]
Makes sense to me :+1: I am all about making things as easy as possible

**Comment by KrauseFx** [comment]
From Victor:

> i think ipa uploading and metadata uploading should be decoupled.
> i think most people, especially teams will work separately on the app store metadata and the delivery of the release build.

I agree, but this might involve some bigger refactoring of `deliver`. Maybe we could provide a way to pass the mode of `deliver`.

**Comment by KrauseFx** [comment]
This is now implemented :+1:
