### ISSUE TITLE
[Feature] Depend/Include Other Lanes

### ISSUE THREAD

**Issue by bassrock** [KrauseFx/fastlane#159]
At this time it appears that you cannot call other lanes from within a lane or depend on another lane running successfully. This would give the ability to separate out the sigh, snapshot or other steps into their own lanes so that they could be run separately and so that you do not have to duplicate items in the fastfile.

**Comment by KrauseFx** [comment]
Yes, in the mean time, you can just use Ruby functions:

```ruby
def build_app
  sh "do something"
  i = 1 + 1
end

lane :appstore do
  build_app
end
```

Does that help?

**Comment by KrauseFx** [comment]
I'll close this issue for now, as this feature is not planned yet.

**Comment by KrauseFx** [comment]
Thanks again for the feedback :+1:
