### ISSUE TITLE
xcodebuild action - multiple destinations

### ISSUE THREAD

**Issue by bartoszj** [KrauseFx/fastlane#163]
`xcodebuild` command allows to pass multiple `destination` parameters:

```
xcodebuild -workspace MyWorkspace.xcworkspace -scheme MyScheme
    -destination 'platform=iOS Simulator,name=iPhone 5s'
    -destination 'platform=iOS,name=My iPad' test
```

It is very useful when you want to run test on multiple devices / simulators. Unfortunately `xcodebuild` action doesn't handle this. It would be nice to have `:destination` to support string parameter and array of strings, like:

```
xctest(
  destination: "platform=iOS Simulator,name=iPad Air,OS=8.2"
)
# And
xctest(
  destination: ["platform=iOS Simulator,name=iPad Air,OS=8.2", "platform=iOS Simulator,name=iPad Retina,OS=7.1"] 
)
```

**Comment by dral3x** [comment]
+1
