### ISSUE TITLE
Can't reinit fastlane

### ISSUE THREAD

**Issue by skywinder** [KrauseFx/fastlane#165]
Can't reinit fastlane

Step to reproduce:

1.  run `fastlane init` and init anything.
2. hard reset to previous state
3.  run `fastlane init` again.

Expected result:

fastlane should initialize all again from scratch

Actual result:

    fastlane init

```
ERROR [2015-04-01 11:51:29.63]: Could not check if 'fastlane' is up to date.
/Users/user/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/lib/fastlane/setup.rb:6:in `run': Fastlane already set up at path ./fastlane/ (RuntimeError)
	from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/bin/fastlane:45:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/command.rb:178:in `call'
	from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/command.rb:178:in `call'
	from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/command.rb:153:in `run'
	from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/runner.rb:68:in `run!'
	from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.1/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/bin/fastlane:60:in `run'
	from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/fastlane-0.4.2/bin/fastlane:64:in `<top (required)>'
	from /Users/user/.rvm/rubies/ruby-2.1.5/bin/fastlane:23:in `load'
	from /Users/user/.rvm/rubies/ruby-2.1.5/bin/fastlane:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by KrauseFx** [comment]
Mh, yes, as soon the the `fastlane` directory is there, it won't init again.

**Comment by KrauseFx** [comment]
Is the folder empty? What do you suggest? The error message shows why it fails, is it unclear? Should the message be updated?

**Comment by skywinder** [comment]
> Is the folder empty? 

- No. there is empty folder `actions` also. But it doesn't matter. The problem in check https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/fastlane_folder.rb#L15 - if the folder exists or not

> What do you suggest?

-  imho: `RuntimeError` is not good ending for script execution. Probably it's better show user-friendly explanation of the problem.  Like `pod init` - just show red output  "[!] Existing Podfile found in directory".

>The error message shows why it fails, is it unclear? 

- Yes. because actually fastlane is not initialized. There is just empty folder. 

- Possible solution: Probably it's better to check not the folder, but some essential file of fastlane in  string https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/fastlane_folder.rb#L15 ? Probably existing of `Fastfile`?

**Comment by pvegh** [comment]
I wouldn't throw an exception nor show a stacktrace either.
It's a known use case, so handle safely and shortly report to the user would be my proposal / wish.

**Comment by KrauseFx** [comment]
Thanks again for the feedback, fixed with https://github.com/KrauseFx/fastlane/commit/37d431433e390c7b5b502790afb7a6247b585c7e and https://github.com/KrauseFx/fastlane/commit/17dd564033b4404ef64261b324f29be9015b4ddc

**Comment by skywinder** [comment]
awesome! :+1:
