### ISSUE TITLE
increment_build_number should accept X.Y version numbers

### ISSUE THREAD

**Issue by ashfurrow** [KrauseFx/fastlane#167]
Currently, it [requires](https://github.com/KrauseFx/fastlane/blob/03c2aa98181974990810c9106e2d27d087bfba87/lib/fastlane/actions/increment_version_number.rb#L30) a version number formatted as `X.Y.Z`.

**Comment by ashfurrow** [comment]
@orta came and said that I'm wrong. We'll just use `X.Y.Z`:)

**Comment by orta** [comment]
http://semver.org always indicates x.y.z

**Comment by eytanbiala** [comment]
+1

**Comment by kcharwood** [comment]
Currently, it forces x.y.z, and doesn't take into account for beta semver syntax (such as 3.0.0-beta.1) 

I'd like see to support for full semver regex.
