### ISSUE TITLE
sigh timeout

### ISSUE THREAD

**Issue by turowicz** [KrauseFx/fastlane#17]
Running fastlane beta results in a timeout on a sigh step. Is there a way of overriding the timeout setting? Weird error, the dev portal works fine in the browser...

Wojciechs-MacBook-Pro:src wojtek$ fastlane beta
INFO [2015-01-26 13:58:27.69]: Driving the lane 'beta'
INFO [2015-01-26 13:58:27.69]: Step: increment_build_number
INFO [2015-01-26 13:58:27.69]: [SHELL COMMAND]: agvtool next-version -all
INFO [2015-01-26 13:58:27.89]: [SHELL OUTPUT]: Setting version of project X to:
INFO [2015-01-26 13:58:27.89]: [SHELL OUTPUT]: 13.
INFO [2015-01-26 13:58:27.89]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:27.90]: [SHELL OUTPUT]: Also setting CFBundleVersion key (assuming it exists)
INFO [2015-01-26 13:58:27.90]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:27.91]: [SHELL OUTPUT]: Updating CFBundleVersion in Info.plist(s)...
INFO [2015-01-26 13:58:27.91]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:27.92]: [SHELL OUTPUT]: Updated CFBundleVersion in "X.xcodeproj/../X/Info.plist" to 13
INFO [2015-01-26 13:58:27.93]: [SHELL OUTPUT]: Updated CFBundleVersion in "X.xcodeproj/../XTests/Info.plist" to 13
INFO [2015-01-26 13:58:27.93]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:27.93]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:28.12]: Step: cocoapods
INFO [2015-01-26 13:58:28.12]: [SHELL COMMAND]: pod install
INFO [2015-01-26 13:58:28.36]: [SHELL OUTPUT]: Analyzing dependencies
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: CocoaPods 0.36.0.beta.1 is available.
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: To update use: `gem install cocoapods --pre`
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: [!] This is a test version we'd love you to try.
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: For more information see http://blog.cocoapods.org
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: and the CHANGELOG for this version http://git.io/BaH8pQ.
INFO [2015-01-26 13:58:31.52]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Downloading dependencies
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using GTMHTTPFetcher (1.141)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using GZIP (1.0.3)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using JDStatusBarNotification (1.5.0)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using Mixpanel (2.6.2)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using NSDate+TimeAgo (1.0.3)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using OpenSSL-Universal (1.0.1.k)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using SZTextView (1.1.10)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using SlackTextViewController (1.4.1)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using Tweaks (1.1.0)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using gtm-oauth2 (0.1.0)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Using mailcore2 (0.4.7)
INFO [2015-01-26 13:58:32.31]: [SHELL OUTPUT]: Generating Pods project
INFO [2015-01-26 13:58:33.10]: [SHELL OUTPUT]: Integrating client projects
INFO [2015-01-26 13:58:33.63]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:33.63]: [SHELL OUTPUT]: [!] GTMHTTPFetcher has been deprecated in favor of gtm-http-fetcher
INFO [2015-01-26 13:58:33.63]: [SHELL OUTPUT]: 
INFO [2015-01-26 13:58:33.63]: [SHELL OUTPUT]: [!] mailcore2 has been deprecated in favor of mailcore2-ios
INFO [2015-01-26 13:58:33.65]: Step: sigh
INFO [2015-01-26 13:58:35.15]: Login into iOS Developer Center
The file /Users/wojtek/Workspace/x-ios/src/Error1422280745.png does not exist.
INFO [2015-01-26 13:59:05.18]: Variable Dump:
INFO [2015-01-26 13:59:05.18]: {:LANE_NAME=>:beta, :BUILD_NUMBER=>13}
FATAL [2015-01-26 13:59:05.18]: Capybara::Poltergeist::TimeoutError
FATAL [2015-01-26 13:59:05.18]: fastlane finished with errors

**Comment by KrauseFx** [comment]
For easier debugging I recommend running `sigh` directly. Does this happen every time?
What does the generated screenshot show?

**Comment by turowicz** [comment]
Turned out the process was failing because it couldn't create the screenshot :open_mouth: 

Its going pass that step now, sorting out the delivery.

**Comment by KrauseFx** [comment]
Can you run `phantomjs -v` and let me know which version you're using?

**Comment by turowicz** [comment]
Wojciechs-MacBook-Pro:src wojtek$ phantomjs -v
1.9.8

**Comment by KrauseFx** [comment]
That looks okay. I wonder why it failed generating the screenshot...
