### ISSUE TITLE
Inconsistent values for IPA_OUTPUT_PATH and DSYM_OUTPUT_PATH

### ISSUE THREAD

**Issue by CraigSiemens** [KrauseFx/fastlane#171]
I'm working on building a custom action and I'm running into a case where it's getting a relative path to the ipa and an absolute path to the dsym.

```
:IPA_OUTPUT_PATH=>"../APP_NAME.ipa",
:DSYM_OUTPUT_PATH=>"/Users/Shared/Jenkins/Home/jobs/TestFlight/workspace/APP_NAME.app.dSYM.zip"
```

It's also weird that the ipa path is relative to the fastlane folder, not the root folder of my project. I tried expanding it using `File.expand_path(ipa_path)` but that doesn't work since it expands relative to the root folder of the project.

**Comment by KrauseFx** [comment]
I'll update it to store only absolute paths, thanks for letting me know!
