### ISSUE TITLE
Latest fastlane gem is 0.4.2

### ISSUE THREAD

**Issue by jshier** [KrauseFx/fastlane#172]
Is there a delay between release and the gem repo being updated? Because the latest version I can pull from gem or bundler is 0.4.2. I noticed the same when 0.4.0 was released where the latest was still 0.3.x. If there is a delay, perhaps the release email should be delayed until the gem is actually available?

**Comment by KrauseFx** [comment]
Ohhh, I hate myself right now, this happened already before, I just forgot to push the latest version to RubyGems, I'm sorry about that. Please try again, the update is now available.

Thanks for letting me know :+1:
