### ISSUE TITLE
saves .png images from ITC as .jpg

### ISSUE THREAD

**Issue by sneps85** [KrauseFx/fastlane#174]
When i am trying to use fastlane deploy, i get the following error for all images, that where previously downloaded automatically from ITC:

ERROR ITMS-9001: "/2fe65325869b498dd8d6975b571f9e42.jpg does not match type JPEG Image because of these validation issues: ; Error=com.apple.jingle.leghorn.fileformat.ValidationError@4f521bee[userString=This file does not start with a start of image marker.]" at Software/SoftwareMetadata/SoftwareVersion/SoftwareVersionLanguageDetail
...
Transporter transfer failed.

After taking a closer look at the mentioned files, i saw that the .jpg files are PNG files. So why are they stored with the wrong extension in the fastlane/[AppleID].itmsp?

**Comment by KrauseFx** [comment]
Good point, this needs to be fixed!

**Comment by sneps85** [comment]
Have you an ETA on when the bug will be fixed?

**Comment by KrauseFx** [comment]
No, I just took a look, `deliver` doesn't change anything regarding file extension. The easiest way for you is to just rename the file using the built in Finder bulk renamer.

**Comment by sneps85** [comment]
so the bug is somewhere else but not in your tools?

**Comment by sneps85** [comment]
i think the problem is at the fastlane init point:
Downloading all previously used app screenshots.
as the PNG files are downloaded and stored as .jpg

**Comment by KrauseFx** [comment]
Here is the source code in case you want to take a look: https://github.com/KrauseFx/deliver/blob/master/lib/deliver/itunes_connect/itunes_connect_screenshot_fetcher.rb

It doesn't seem as I'm modifying the file extension. I'll take a closer look later.

**Comment by sneps85** [comment]
i see...
i tried to open the url
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/version/[AppleID]
in the web browser, which gave me a JSON response containing the screenshots as .jpg file names. 
The URL of the screenshot instead is .png

Here a part of the (obscured) JSON:
{"value":[{"value":{"assetToken":"****/mzl.mwojjmau.jpg","thumbnailAssetToken":"****/screen170x170.jpeg","url":"https://is3-ssl.mzstatic.com/image/thumb/****/mzl.mwojjmau.jpg/640x960ss-80.png","thumbNailUrl":"https://is4-ssl.mzstatic.com/image/thumb/****/mzl.mwojjmau.jpg/500x500bb-80.png","sortOrder":1,"originalFileName":"****.jpg"},"isEditable":true,"isRequired":false,"errorKeys":null}

**Comment by sneps85** [comment]
Looks like you have to use the extension in the URL and not from the given file name to fix this issue.

**Comment by sneps85** [comment]
Could you reproduce the issue?

**Comment by KrauseFx** [comment]
No, but I'll try to push a fix in a few minutes.

**Comment by KrauseFx** [comment]
The `assetToken` is **not** the original file format: it's also jpg for me, but I uploaded pngs.

**Comment by KrauseFx** [comment]
`originalFileName` is the relevant one :+1:

**Comment by KrauseFx** [comment]
I'm currently using the given file extension:

```ruby
file_name = [screenshot['value']['sortOrder'], type, screenshot['value']['originalFileName']].join("_")
```

where `screenshot['value']['originalFileName']` is `:"***.jpg"` according to your previous comment.

**Comment by sneps85** [comment]
no, but the url you're downloading the screenshot from is .png:
"url":"https://is3-ssl.mzstatic.com/image/thumb//mzl.mwojjmau.jpg/640x960ss-80.png"

and you're storing it on it's original filename: "originalFileName":"***.jpg"

so you're storing a .png image with .jpg extension and that causes the issue when the downloaded screenshot will be re-uploaded

**Comment by KrauseFx** [comment]
So you uploaded a `jpg` back then and Apple converted it to a `png`? Can you send me your URL to test it with?

**Comment by sneps85** [comment]
sent it to github@krausefx.com

**Comment by sneps85** [comment]
i think that apple converted it, yes...

**Comment by sneps85** [comment]
any news on this? :-)

**Comment by KrauseFx** [comment]
Sorry, I'm not working on this right now.

**Comment by KrauseFx** [comment]
If you need this fixed urgently and have some time, I'd be happy to review a pull request :+1:

**Comment by KrauseFx** [comment]
This part will be completely rewritten using [spaceship](https://spaceship.airforce). I'll close this issue for now :+1:
