### ISSUE TITLE
ipa action ignores the configuration specified by the scheme

### ISSUE THREAD

**Issue by coreyfloyd** [KrauseFx/fastlane#176]
If you set up Xcode Schemes to reference specific configurations and then use the `ipa` action like so:

```
ipa({
    scheme: 'Test Project Alpha',
    clean: nil, # this means 'Do Clean'. Clean project before building.
    archive: nil, # this means 'Do Archive'. Archive project to the Xcode organizer after building.
  })
```

It generates this `ipa` command:

```
ipa build -s "Test project Alpha" --clean --archive -m "/Users/jenkins/.jenkins/jobs/TestProject/workspace/provisioning.mobileprovision"
```

Which results in this `xcodebuild` command:

```
xcodebuild -sdk iphoneos -workspace "Test.xcworkspace" -scheme "Test Project Alpha" -configuration 'Release' clean build archive
```

The configuration "Release" is being passed if a configuration isn't specified. Which is overwriting the Schemes specified configuration. To fix this you must pass the Configuration explicitly.

```
ipa({
    scheme: 'Test Project Alpha',
    configuration: 'Alpha', #Prevents fastlane from passing --configuration "Release"
    clean: nil, # this means 'Do Clean'. Clean project before building.
    archive: nil, # this means 'Do Archive'. Archive project to the Xcode organizer after building.
  })
```

To fix this, the `ipa` action should not pass configuration if not specified and fall back to the Scheme's settings.

**Comment by champo** [comment]
`ipa` is not a part of fastlane actually, it's at nomad/shenzhen

**Comment by dhagerty9009** [comment]
I think that may fall under Xcode's domain. There is an option (I'll have to go find it tomorrow) to have all command line builds be built with the "Release" configuration. That could be causing your issue.

**Comment by coreyfloyd** [comment]
@dhagerty9009 it's not that setting for sure, that was one of the first things I checked. 

When you pass a scheme to xcodebuild, it does the "right thing" and uses the configuration specified by the scheme. The setting you are referencing only kicks in if you ommit the scheme and configuration options. 

If you look at the issue description, you can see that Fastlane is explicitly passing the release argument to the xcodebuild command. This is not a case of an ommited option, it is being added within the Fasrlane tool chain. Or as noted above, it this could be happening within Shenzhen, but I haven't investigated any further yet.

**Comment by KrauseFx** [comment]
@coreyfloyd Have you found a way to solve this issue?

**Comment by masa-beheim** [comment]
@coreyfloyd I can confirm your observations. Fastlane seems to always forward a configuration to `xcodebuild`. I was experiencing it with shenzen/ipa and still am with gym. Running `xcodebuild -scheme the-scheme` will export the configuration that is attached to the scheme automatically.
@KrauseFx I think if a scheme without configuration is provided the configuration should not be set by Fastlane.

**Comment by KrauseFx** [comment]
The `ipa` action is deprecated and you should use the `gym` action instead. Do you have the same problem with it?

**Comment by masa-beheim** [comment]
Yes, I am still experiencing this with `gym`. If a configuration is not specified in `gym` and the `Release` configuration exists, `Release` will be set, even though the scheme itself points to a different configuration. Have a look here: [detect_values.rb#L161](https://github.com/fastlane/gym/blob/921b94be0fd814df5cfb9235b6ee2c2b6ddae9eb/lib/gym/detect_values.rb#L161)
I am also using the same workaround by additionally specifying the configuration.

**Comment by KrauseFx** [comment]
@masa-beheim So what does `gym` to do differently to make it work? Just not set it to `Release` by default?

**Comment by masa-beheim** [comment]
Yes, as proposed at the top, it should not pass configuration at all if not specified.

**Comment by coreyfloyd** [comment]
@KrauseFx as @masa-beheim said: if no configuration is passed to `gym`, it should not pass any configuration `xcodebuild`. 

This allows `xcodebuild` to use to the configuration specified by the scheme (which may be `Release` or `Debug` or something else).

**Comment by KrauseFx** [comment]
Perfect, thanks for clarifying! :+1:

**Comment by KrauseFx** [comment]
Check out the most recent release https://github.com/fastlane/gym/releases/tag/0.8.4 :rocket:

**Comment by masa-beheim** [comment]
I don't know whether this fixed it for you @coreyfloyd, but I am still struggling with this. I have checked with multiple projects and I still have to supply the correct configuration even though the scheme is specified. The scheme is passed on correctly though.

Running the following picks the wrong configuration for me.
```sh
gym -s AScheme
```
This picks the right configuration.
```sh
xcrun xcodebuild -scheme AScheme
```

I've been digging around a little bit and one thing I don't understand is what this command outputs:
```sh
xcrun xcodebuild -showBuildSettings -scheme 'AScheme' -project './The.xcodeproj'
```
I always thought that specifying the scheme gives me back the build settings for that scheme. But all the following commands return the same output:
```sh
xcrun xcodebuild -showBuildSettings
xcrun xcodebuild -showBuildSettings -scheme 'ASchemeThatExists'
xcrun xcodebuild -showBuildSettings -scheme 'AnotherSchemeThatExists'
```
It seems that the scheme flag is not really taken into account. Specifying a non-existing scheme results in an error though.
In particular the `CONFIGURATION` is always the same. It's set to the result of...
```sh
xcrun xcodebuild -list -project './The.xcodeproj'
```
...where it says: „If no build configuration is specified and -scheme is not passed then <i>ConfigurationX</i> is used.“ And this is not always the configuration of my specified scheme.



(fastlane 1.37.0, gym 1.1.4)
Hope somebody can help. Thank you!

**Comment by ender672** [comment]
I was scratching my head trying to figure out why my build configuration was defaulting to "Release" even though my scheme has a different one set.

I found the problem - gym is running the ```Archive``` build action and I was looking at the ```Run``` action's build configuration for the scheme. After changing this everything works as expected.

In short -- make sure you are looking at the scheme's build configuration for the ```Archive``` build action.

**Comment by masa-beheim** [comment]
@ender672 Thanks for pointing that out!
