### ISSUE TITLE
Consolidate syntax recommendations in docs

### ISSUE THREAD

**Issue by orta** [KrauseFx/fastlane#177]
Similar to: https://github.com/artsy/eidolon/pull/412 but for all docs

Choices @ashfurrow and I made:
* Always skip the `{` and `}` for the dictionary params
* If there's two params or less, inline it and remove all other 
* IMO there should be a space after a function & before the params, so
 
 ```
  hockey (
    thing: "thing"
  )
  ```

**Comment by orta** [comment]
These are ruby 2.0 things, which is 10.9 - 10.10, which is all Xcode 6 supports, so using fancy syntax feels reasonable to me.

**Comment by ashfurrow** [comment]
Happy to do this.

**Comment by KrauseFx** [comment]
Sounds like a good plan. I already require Ruby >= 2.0, so that's not a problem.

I already wrote all examples (e.g. https://github.com/fastlane/fastlane-example) and of course the documentation using the other style :disappointed:

**Comment by KrauseFx** [comment]
Another thing which I'm not happy about yet: Sometimes the example docs use `'` and sometimes `"`, which might confuse some users. I guess we should stick with `"`.

**Comment by orta** [comment]
yeah, imo standardising on `"` means when people try to interpolate with `#{}` they won't get confused.

**Comment by KrauseFx** [comment]
Just pushed https://github.com/KrauseFx/fastlane/commit/986375f50569847ec2900b8101f69a98f1461889

I decided to not got for the space after the method name, but to drop the `({` and only have `(` :+1:
