### ISSUE TITLE
[Feature] Trigger lane or other command on app status change

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/fastlane#178]
A way to trigger scripts (in particular `lanes`) if the app review status changes.

e.g.

- Send an email to customers when app was released
- Post on Facebook, a new version is available
- Post on Slack the update was rejected

Since I now know how to access the app status via JSON API, it should be possible.

The script has to run in the background and refresh the app status every other minute.

**Comment by shams-ahmed** [comment]
this sounds good, Hipchat integation would be answsome as well

**Comment by KrauseFx** [comment]
Hipchat is already integrated :wink: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#hipchat

**Comment by KrauseFx** [comment]
Closed for now
