### ISSUE TITLE
Support for different Apple Developer and iTunes Connect accounts

### ISSUE THREAD

**Issue by vytis** [KrauseFx/fastlane#18]
It seems that `fastlane` is having problems when iTC and developer's AppleID accounts are different. That happened in my case because my AppleID is assigned to multiple teams, but iTC doesn't support more that one account per email. `fastlane` tries to log in my AppleID email to iTC and fails because passwords don't match (even if they did it wouldn't work because that account is for different apps).

I have tried setting `SIGH_USERNAME` and `DELIVER_USER` to different emails but it seems that the latter is used all the time if present.

It seems that the problem might be because `SIGH_USERNAME` environment variable is read only when sigh is launched from command line:
https://github.com/KrauseFx/sigh/blob/master/bin/sigh#L59

but it falls back to `DELIVER_USER` from `CredentialsManager` if the class is instantiated directly:
https://github.com/KrauseFx/sigh/blob/master/lib/sigh/developer_center.rb#L72

My ruby knowledge is a bit limited and it might need updating several libs at the same time to make it work...

Just in case, the corresponding lane in `Fastlane` is (using [floatsign](https://github.com/nanonation/floatsign) to resign the `.ipa`):

```
lane :internal do
  sigh :adhoc
  system("ipa build -c \"AdHoc\" -w ../<AppName>.xcworkspace -s '<AppName>'")
  system("./floatsign.sh <AppName>.ipa \"iPhone Distribution: <team>" -b 'some.bundle.id' -p #{Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH]} <AppName>AdHoc.ipa")
  sigh
  system("./floatsign.sh <AppName>.ipa \"iPhone Distribution: <team>" -b 'some.bundle.id' -p #{Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH]} <AppName>AppStore.ipa")
  hockey({
    api_token: '<api_token>',
    ipa: 'fastlane/<AppName>AdHoc.ipa',
    dsym: 'fastlane/<AppName>.app.dSYM.zip'
    # notes: ""
  })
  deliver :skip_deploy, :beta
  increment_build_number
end
```

**Comment by KrauseFx** [comment]
Thanks for your detailed report and sorry for not coming back earlier.

You can remove the first `system('floatsign')`, right?

The problem you described is caused because of
https://github.com/KrauseFx/CredentialsManager/blob/master/lib/credentials_manager/password_manager.rb#L30
```ruby
      self.username ||= ENV["DELIVER_USER"] || id_to_use || AppfileConfig.try_fetch_value(:apple_id) || load_from_keychain[0]
```
I'll update it to use the parameter first.

**Comment by KrauseFx** [comment]
Here we go: https://github.com/KrauseFx/CredentialsManager/commit/9d112498391be1b7d7daf231055ce5970094fa66

Please download the `CredentialsManager` as zip and run `sudo bundle install` and `sudo rake install` and try again.

**Comment by KrauseFx** [comment]
Please try the latest version https://github.com/KrauseFx/fastlane/releases/tag/0.1.2 :+1:

**Comment by vytis** [comment]
I've added the first `system('floatsign')` just in case the `.ipa` was not made with the most up to date profile. Combined with `sigh :skip_install` flag this could easily be the case.

As for the issue, it doesn't seem to be fixed yet. It works good when using `sigh` from command line, but from `fastlane` it's still the same.

I think it happens because here the `user` is empty when the lib is called from `fastlane`:
https://github.com/KrauseFx/sigh/blob/master/lib/sigh/developer_center.rb#L71

Password manager is only initialized with value from `SIGH_USERNAME` when using standalone `sigh` command, not the lib:
https://github.com/KrauseFx/sigh/blob/master/bin/sigh#L67

**Comment by albertschulz** [comment]
Having the same problem. Would be glad to have a solution for this :+1:

**Comment by vytis** [comment]
I have found an easy way to reproduce it with this lane (`.ipa` file is already present in the directory and `Deliverfile` simply points to that file):

```
lane :external do
  sigh :skip_install
  deliver :beta
end
```

At first `sigh` asks me for Developer's Portal account, but then fails to login to iTunesConnect because it doesn't ask it again but uses the previous account.

**Comment by lmirosevic** [comment]
:thumbsup: I'm also a member of multiple teams with a single email on the Member Centre on developer.apple.com. And I use different emails for each of the related iTC accounts on itunesconnect.apple.com (out of necessity as iTC doesn't support multiple accounts under one email address).

Would be nice if fastlane would support this use case!

**Comment by KrauseFx** [comment]
@lmirosevic as far as I know, you can always add a `ENV["DELIVER_USER"] = "email@email.com"` before each of the steps.

**Comment by lmirosevic** [comment]
This can probably be closed. There is `ENV['DELIVER_USER']` and the `email` property in the Deliverfile that would let you select a (different) iTC account.

**Comment by t2** [comment]
This is still an issue. Even when changing the ```DELIVER_USER``` and ```DELIVER_PASSWORD``` before calling deliver, it still uses the login session from when I call ```sigh```

```
lane :demo do
  increment_build_number

  ipa({
    clean: false,
    workspace: ENV['WORKSPACE'],
    configuration: 'AdHoc',
    scheme: ENV['SCHEME']
  })

  ENV['DELIVER_USER']='developer.apple.com email'
  ENV['DELIVER_PASSWORD']='developer.apple.com password' 
  sigh(
    force: false,
    output_path: "./fastlane/profiles",
    adhoc: true
  )

  ENV['DELIVER_USER']='itunes connect email'
  ENV['DELIVER_PASSWORD']='itunes connect password'
  deliver(beta: true)

  slack(message: "Demo app successfully deployed!")
end
```

Please advise if I am missing something.

**Comment by KrauseFx** [comment]
@t2 Have you tried using:
```ruby
sigh(username: 'developer.apple.com email')
```

**Comment by t2** [comment]
I did:

```sigh(username: 'email', password: 'password')``` 
throws 
```You passed invalid parameters to 'sigh'.```

```sign(username: 'email')``` 
throws
````send_login_request': #<Faraday::Response:0x000001020d9be0> (Spaceship::Client::InvalidUserCredentialsError)```

**Comment by postmechanical** [comment]
Just discovered that this has been happening for one of my CI builds since the beginning of September. In my case both `sigh` and `fastlane` are using the same username. Using `fastlane` version `1.27.0`.

**Comment by KrauseFx** [comment]
<img width="775" alt="screenshot 2015-12-05 00 11 00" src="https://cloud.githubusercontent.com/assets/869950/11606152/d1854ad4-9ae4-11e5-8de7-7b2d265a3624.png">

This works now, add this to your `Appfile`. Let me know how that works :+1:

**Comment by muzammil-triffort** [comment]
@KrauseFx app_identifier command not found

**Comment by muzammil-triffort** [comment]
@KrauseFx I have different account ids for apple developer and iTunes connect. My issue is fastlane is using the default apple developer account for publishing on iTunes. So getting error. Please help, how can I add different itunes connect account and also how to update developer account which i setup in the starting?
