### ISSUE TITLE
Cannot add_git_tag with my own provided tag name

### ISSUE THREAD

**Issue by frobichaud** [KrauseFx/fastlane#180]
Here is the lane I've defined in my Fastfile:

lane :tag do
  add_git_tag tag: "test"
end

When I invoke:
#fastlane tag

I get the following error
INFO [2015-04-08 04:13:51.91]: Driving the lane 'tag'
INFO [2015-04-08 04:13:51.91]: -------------------------
INFO [2015-04-08 04:13:51.91]: --- Step: add_git_tag ---
INFO [2015-04-08 04:13:51.91]: -------------------------
INFO [2015-04-08 04:13:51.91]: [SHELL COMMAND]: git tag builds/tag/
INFO [2015-04-08 04:13:51.92]: [SHELL OUTPUT]: fatal: 'builds/tag/' is not a valid tag name.

**Comment by frobichaud** [comment]
Just realized this feature is brand new and only in master.

**Comment by KrauseFx** [comment]
Yes, sorry, there will be a new release today!

**Comment by frobichaud** [comment]
Thanks for the version bump

**Comment by KrauseFx** [comment]
Thanks for letting me know :+1:

**Comment by dalu93** [comment]
Hi @KrauseFx. Thanks for the great job developing fastlane.
I'm still having some problems with the action `add_git_tag`. It sometimes work, sometimes not, not sure why.

The version I use is `fastlane_version "1.101.0"` and here is the lane

```ruby
version_number = options[:version_number] || get_podspec_version #get_podspec_version is a bash script that works

add_git_tag(
      tag: version_number
)
push_git_tags
```

But the error I get is

```
Exit status of command 'git tag -am Tag\ 3.1'
' '3.1
'' was 128 instead of 0.
fatal: '3.1
' is not a valid tag name.
```
