### ISSUE TITLE
Rollback to 'old-version' if error happens

### ISSUE THREAD

**Issue by patoroco** [KrauseFx/fastlane#181]
Should be good to rollback version number when some exception is raised.

Until now, I use `error do |lane, exception|`, but I think that this should be default behavior, isn't it?

**Comment by KrauseFx** [comment]
You mean when you use the `increment_build_number` action?

**Comment by patoroco** [comment]
Yes, after use increase build, if the lane crashes, build continue with new version, so if you run newly same lane, build will be update two times.

Until the moment I store bundle version in a variable load in before all method, and if error happens, I set to the old build number, but I think that this behavior should be the default: if something was changed before lane, and it crashes, state should be the same that before than run this lane.

What do you think about that?

**Comment by KrauseFx** [comment]
I think that is very specific to the actions you use. You might use actions, that modify something. Every action would have to provide a `revert` method to solve this.

You should run `fastlane` only in a clean state, which is why there is a `ensure_git_status_clean` method.
