### ISSUE TITLE
pem action for fastlane

### ISSUE THREAD

**Issue by aafa** [KrauseFx/fastlane#182]
I've created simple pem action as part of my fastlane routines, cause I've found it very convenient to have everything in one place within Fastfile config.

So I'm curious if this action could be useful as addition to main actions?

**Comment by KrauseFx** [comment]
Absolutely, the only reason why there is no `PEM` action in fastlane is the limit of push profiles: You are only allowed to have 2 push profiles per app. Right now, `PEM` will **always** create a new profile if there is a spot left. 

To integrate `PEM` into `fastlane`, it must detect the expiration date to only create a profile if the old one is about to expire.

**Comment by aafa** [comment]
I see.  In my case I have it in a special lane which creates pem files and passes them to server. Basically running once per new app for now - fastlane config is created with each new app project (as part of a template). 

I will look into PEM functionality.
