### ISSUE TITLE
How to use the [App] variable?

### ISSUE THREAD

**Issue by drupalmodule** [KrauseFx/fastlane#189]
I have tried to use the [App] variable as it is described in the slack connector docs.  The [App] never gets the app code substituted See:

```
  slack({
        message: "[App] Successfully deployed new App Update",
        success: true,
        channel: 'mobile-automator'
  })
```
I have also tried it on a sh call:
```
sh "/automator/bin/ios_fastlane_done.py 8126062081 [App] 200"
```

any thoughts?

**Comment by KrauseFx** [comment]
There is no such thing as an app variable. This is just a standard markdown link for the slack message. 
What value did you expect from this variable?

**Comment by drupalmodule** [comment]
Not exactly sure- app bundleid or app name

**Comment by KrauseFx** [comment]
Okay, good to know, I'll think about it :+1:
