### ISSUE TITLE
iOS simulator app installer support

### ISSUE THREAD

**Issue by ashfurrow** [KrauseFx/fastlane#191]
https://github.com/stepanhruda/ios-simulator-app-installer 

Looks so cool. Willing to do this.

**Comment by KrauseFx** [comment]
Wow, what is this? Black magic? :octopus: I'll take a closer look at this today :+1:

**Comment by KrauseFx** [comment]
I took a closer look, I have 2 questions:

- What's the use case for integrating this into `fastlane`? What would you use it for at Artsy? 
- How would you approach integrating as it's programmed in Swift?

It sure sounds promising, it's just not clear to me yet what to use it for.

I think, integrating [appetize](https://appetize.io/) would be more useful, as you can send it to clients, or employees without an iPhone. Demo: https://appetize.io/demo

**Comment by ashfurrow** [comment]
Artsy doesn't have a use case for this tool, but I can see other companies or developers having one: deploy to a coworker, manager, designer via their Mac over email/whatever. It would be tricky to integrate; any suggestions? Maybe a check similar to `xctool`'s?

**Comment by KrauseFx** [comment]
Honestly, I'd rather prefer the `appetize` approach for various reasons:

- It's much easier to integrate, only S3 upload and post request
- It can be used by any team member, also non Mac-users and non developers
- It can be sent to a client to review the app

What do you think?

**Comment by ashfurrow** [comment]
Makes sense to me. Don't really have a stake in this. Could always go with both, or whatever ¯\_(ツ)_/¯

**Comment by KrauseFx** [comment]
I'll close this issue for now, as I don't think it's something we'll implement anytime soon. Thanks again for suggesting :+1:
