### ISSUE TITLE
FTP Upload available? 

### ISSUE THREAD

**Issue by chstraube** [KrauseFx/fastlane#192]
Hi,

is there an opportunity to use the FTP Upload of [shenzhen](https://github.com/nomad/shenzhen) in fastlane 
`$ ipa distribute:ftp --host HOST -u USER -p PASSWORD -P FTP_PATH`

Christoph

**Comment by KrauseFx** [comment]
Not right now, only AWS S3 distribution is available.

**Comment by KrauseFx** [comment]
It would be easily possible, if you want to, check out the integrated actions, in particular `s3` and `hockeyapp`, as most of the code can probably just be used for ftp distribution as well.

If you want to, you can always just run shell commands in `fastlane` using

```ruby
sh "ipa distribute:ftp ...."
```
