### ISSUE TITLE
highline gem dependency error on both  0.8.0 and 0.8.1

### ISSUE THREAD

**Issue by chipaubry** [KrauseFx/fastlane#194]
Anyone else seeing this error? Guessing its my env...but wanted to reach out first.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'highline (>= 1.7.1)', already activated 'highline-1.6.21' (Gem::LoadError)

**Comment by KrauseFx** [comment]
Sorry for the troubles, could you try updating `cupertino` and the other `nomad` tools if you have them installed?

**Comment by chipaubry** [comment]
uninstalled nokogiri and reinstalled with --use-system-libraries and upgraded fastlane to 0.9.0 and I am back. Thanks for the quick response. Love fastlane!

**Comment by KrauseFx** [comment]
Thanks. Sorry about the dependency troubles.
