### ISSUE TITLE
ERROR Could not find 'highline' on executing ipa command

### ISSUE THREAD

**Issue by sneps85** [KrauseFx/fastlane#198]
i get the following error for the ipa command on a new installed fastlane:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'highline' (~> 1.6.11) - did find: [highline-1.7.1] (Gem::LoadError)

if i install 1.6.11 i run into the error that it finds 1.6.11 active, but needs 1.7.1

**Comment by KrauseFx** [comment]
Sorry, I don't know what's wrong, but please update your gems using `sudo gem update`

**Comment by sneps85** [comment]
i updated my gems.
it's working now, thank you

**Comment by sneps85** [comment]
but now the command ipa build runs without any output and forever...

**Comment by KrauseFx** [comment]
That's probably because you haven't specified a scheme. Try running `ipa build` in your terminal.
