### ISSUE TITLE
ipa uploaded to HockeyApp but download status is disabled

### ISSUE THREAD

**Issue by JaniJegoroff** [KrauseFx/fastlane#213]
Not sure if I am missing something but download status is disabled in HockeyApp uploads after started to use `fastlane 0.12.2`. Upload itself works fine after fix for #209 but for some reason download is disabled.

Build 32 is uploaded with `fastlane 0.9.0`
Builds 35 and 36 are uploaded with `fastlane 0.12.2`

See screen captures for details:

> **Latest downloadable version** still points to Build 32

![hockeyapp-builds](https://cloud.githubusercontent.com/assets/2363231/7230393/450fd516-e765-11e4-99db-bd4fc5ba5a06.png)

> **Download** and **Status** options are different in Builds 32 and 36

![hockeyapp-build32](https://cloud.githubusercontent.com/assets/2363231/7230494/693cb368-e766-11e4-90de-17ef38a747e4.png)

![hockeyapp-build36](https://cloud.githubusercontent.com/assets/2363231/7230496/709e427a-e766-11e4-9438-89e816288d2b.png)

**Comment by JaniJegoroff** [comment]
I see, status needs to be set explicitly to enable download.

```
hockey(
    api_token: 'xxxxxxxx',
    status: '2' # Available for download
  )
```

**Comment by KrauseFx** [comment]
Thanks, I'll fix this with the next release

**Comment by KrauseFx** [comment]
Found the issue, I'll publish a release soon :+1:

**Comment by SandyChapman** [comment]
One thing that caught me with this is that you need to make sure your API token is either "Upload & Release" or "Full Access" if you want the notify and status options to work.
