### ISSUE TITLE
Symbols not uploaded to HockeyApp automatically

### ISSUE THREAD

**Issue by JaniJegoroff** [KrauseFx/fastlane#214]
Symbols used to be uploaded to HockeyApp automatically (if found) in previous releases. Now using `fastlane 0.12.2` and symbols are not uploaded automatically anymore.

Is this something that has been changed on purpose or is it a bug?

Documentation still says symbols should be uploaded automatically: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#hockeyapp

**Comment by KrauseFx** [comment]
Sorry about this, fix is on its way. Thanks again for reporting all those issues! :+1:

**Comment by KrauseFx** [comment]
Fixed with https://github.com/KrauseFx/fastlane/commit/6f0cc953a8cd969ddab615f30b3e33fe5bca87c7

**Comment by KrauseFx** [comment]
Just pushed the new version :+1:
