### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by matto1990** [KrauseFx/fastlane#227]
I'm running a lane that works fine on my development machine, but fails on our Jenkins machine. The Jenkins machine has the latest XCode (6.3.1) with ruby setup via rbenv. `bundle install` was run before running fastlane and fastlane was run using `bundle exec fastlane dev`.

The error I'm getting is:

```
[37mINFO [2015-04-24 10:19:41.60]: [0m[32m-----------------[0m
[37mINFO [2015-04-24 10:19:41.60]: [0m[32m--- [0m[32mStep: ipa[0m[32m ---[0m
[37mINFO [2015-04-24 10:19:41.60]: [0m[32m-----------------[0m
[35mDEBUG [2015-04-24 10:19:41.60]: [0mset -o pipefail && ipa build -w "<snip>.xcworkspace" -s "<snip>" -d "./build" -m "/Users/ribot/.jenkins/jobs/<snip>-ios-nightly/workspace/build/profile.mobileprovision" --verbose | xcpretty
[37mINFO [2015-04-24 10:19:41.60]: [0m[SHELL COMMAND]: [33mset -o pipefail && ipa build -w "<snip>.xcworkspace" -s "<snip>" -d "./build" -m "/Users/ribot/.jenkins/jobs/<snip>-ios-nightly/workspace/build/profile.mobileprovision" --verbose | xcpretty[0m
/Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:68:in `strip': invalid byte sequence in US-ASCII (ArgumentError)
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:68:in `block (2 levels) in sh_no_action'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:67:in `each'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:67:in `block in sh_no_action'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:66:in `popen'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:66:in `sh_no_action'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:56:in `sh'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/ipa.rb:64:in `run'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:94:in `block in method_missing'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:93:in `chdir'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:93:in `method_missing'
    from (eval):20:in `block (3 levels) in parse'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:34:in `call'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:34:in `block in execute'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:24:in `chdir'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:24:in `execute'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/bin/fastlane:39:in `block (2 levels) in run'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.3/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.3/lib/commander/runner.rb:68:in `run!'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/bin/fastlane:118:in `run'
    from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fastlane-0.12.4/bin/fastlane:124:in `<top (required)>'
    from /Users/ribot/.rbenv/versions/2.1.2/bin/fastlane:23:in `load'
    from /Users/ribot/.rbenv/versions/2.1.2/bin/fastlane:23:in `<main>'
[37mINFO [2015-04-24 10:19:46.82]: [0m[SHELL OUTPUT]: 2015-04-24 10:19:46.824 xcodebuild[5102:18549] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7f980ad0dea0 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/lib/xcpretty/parser.rb:350:in `===': invalid byte sequence in US-ASCII (ArgumentError)
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/lib/xcpretty/parser.rb:350:in `update_test_state'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/lib/xcpretty/parser.rb:247:in `parse'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/lib/xcpretty/formatters/formatter.rb:78:in `pretty_format'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/lib/xcpretty/printer.rb:15:in `pretty_print'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/bin/xcpretty:80:in `block in <top (required)>'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/bin/xcpretty:79:in `each_line'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcpretty-0.1.9/bin/xcpretty:79:in `<top (required)>'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/bin/xcpretty:23:in `load'
[37mINFO [2015-04-24 10:19:48.99]: [0m[SHELL OUTPUT]: from /Users/ribot/.rbenv/versions/2.1.2/bin/xcpretty:23:in `<main>'
[37mINFO [2015-04-24 10:20:45.70]: [0m[33mVariable Dump:[0m
[37mINFO [2015-04-24 10:20:45.70]: [0m{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dev", :GIT_NOTES_LOCATION=>"build/git_notes.txt", :CERT_FILE_PATH=>"/tmp/cert/<snip>.cer", :CERT_CERTIFICATE_ID=>"<snip>", :SIGH_PROFILE_PATH=>"/Users/ribot/.jenkins/jobs/<snip>-ios-nightly/workspace/build/profile.mobileprovision", :SIGH_UDID=>"45f742bf-9078-4112-a56b-f0cad54fb785"}
```

Any ideas what could be causing this?

**Comment by milch** [comment]
Can you run `locale` on your CI server and post the results please? Sounds like your `$LANG` is configured incorrectly on that machine.

**Comment by matto1990** [comment]
```
CI ➜  ~  locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

**Comment by milch** [comment]
Try setting `export LC_ALL="en_US.UTF-8"`and see if that works for you. If you do a search on [all fastlane repositories](https://github.com/search?q=user%3Akrausefx+invalid+byte+sequence+in+US-ASCII&type=Issues&utf8=✓), this issue has happened quite a few times before with other fastlane tools, but we don't completely know what causes it (other than having a different locale than 'en_US.UTF-8').

**Comment by matto1990** [comment]
Interesting... Adding `export LC_CTYPE=en_US.UTF-8` as suggested in https://github.com/supermarin/xcpretty/issues/73 seems to fix the issue, but the values of `locale` are exactly the same on my development machine.

**Comment by matto1990** [comment]
Ok, that fix seems to work so I'll close this. Thanks for the help!

**Comment by KrauseFx** [comment]
Thanks @milch for resolving this issue. @milch do you think there is a way to do that automatically within `fastlane`? This issue has been reported around 10 times already. At least when you google for `invalid byte sequence in US-ASCII (ArgumentError)`, the user can easily fix it, but still, it's an annoying thing. Would love to have this resolved.

I also noticed, the nomad tools are facing the exact same problem.

**Comment by milch** [comment]
Since we don't know exactly what causes it I don't know if just straight up setting the locale ourselves would work reliably. 

What if we do something similar to what home-brew does if it encounters an error? E.g. search github issues and present the user with some dialog like `fastlane noticed you encountered an error "<<error-text>>", see if it has already been solved in the following Issues: <<Issue-List>>".

**Comment by robwithhair** [comment]
+1 bit by this bug.  Don't know what changed but updating gave me this bug.  Fix above worked fine after I found it.

**Comment by matto1990** [comment]
If this got introduced recently maybe it's a good time to use [`git biset`](http://git-scm.com/docs/git-bisect) to narrow down which commit introduced it?

**Comment by milch** [comment]
If @robwithhair still knows which version he updated from, one of you might indeed be able to `git bisect` this. Any info on this, @robwithhair?

**Comment by KrauseFx** [comment]
This has probably nothing to do with the `fastlane` version as this problem has been around since version 0.1.0 of `deliver`. It's very annoying... at least when you google for it, you find a solution immediately.

**Comment by KrauseFx** [comment]
I added 
```
# We want all files to be UTF8, just in case user has it wrongly configured
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
``` 

into `fastlane_core.rb`. Since this problem occurs only when shelling out commands, this should be called in time before executing any external commands. What do you think @milch?

**Comment by KrauseFx** [comment]
Fixed with https://github.com/KrauseFx/fastlane/commit/1147d8dc149d281a4a320c54c3c0fe56e0cbcd46 :+1:

**Comment by milch** [comment]
I'm not sure about setting those, the documentation discourages it:

```
You should not set ::default_external in ruby code as strings created before changing the value may have a different encoding from strings created after the value was changed., ...
```

If we set them, they should bet set before any other strings can be created. Maybe calling `force_encode` on the strings would work as well?

**Comment by KrauseFx** [comment]
@milch does that mean you see a problem on how it is solved with my commit? It is only executed right before something gets shelled out using the fastlane `sh` action.

**Comment by milch** [comment]
I think the point the docs are trying to make is that you could be ending up with different encodings in your Strings, depending on wether they were created before or after you set `default_external` and `default_internal` (which probably would result in very hard to track down bugs). So according to that you would have to set both those properties at the start of `fastlane`, before any other `String` could be created.

**Comment by phatblat** [comment]
Just ran into this issue when running fastlane from a Jenkins build. Setting `LC_ALL=en_US.UTF-8` in the Jenkins configuration resolved the issue.

![jenkins-environment-variable](https://cloud.githubusercontent.com/assets/28851/9807026/6c9aaf8c-580a-11e5-8be9-e0ed7ed7ce56.png)

**Comment by fdovila** [comment]
I had the same error message, my locale was not UTF-8, I tried this from https://stackoverflow.com/questions/7165108/in-osx-lion-lang-is-not-set-to-utf8-how-fix and solved the issue:

1) Modified/created a '.profile'

    nano ~/.profile

2) added these two lines to .profile:

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8

change en_US.UTF-8 to whatever country you are, just check first if available via 'locale -a'

3) close the session, reopen it

4) Brew doctor clears the error message

**Comment by samskiter** [comment]
I have the exact same issue as @matto1990 - Works fine locally but doesn't when running from the same machine through my CI (i.e. I have my local machine set up as a CI runner). I'm using gitlab CI multirunner.

If I set the locales through my bash profile it is fixed, but we need keep environment variables within our builds and not globally.

So I'm using a fastlane/.env file but I end up back at the same issue - it's as if the fastlane/.env arrives too late?

**Comment by TKBurner** [comment]
@samskiter Can you create a new issue for this? That'd be wonderful! Hope you have a great day! 👍
