### ISSUE TITLE
[Feature] New action for saving .xcarchive file elsewhere

### ISSUE THREAD

**Issue by dral3x** [KrauseFx/fastlane#228]
Hi!
I'm working on a new fastlane action that compress the last `.xcarchive` (built in the same line) and save it on a specific folder (other than `/Users/alex/Library/Developer/Xcode/Archives/`).

I almost complete my work but I'm facing a problem. The destination folder is user dependent.
On my machine it is `/Users/alex/BTSync` but my colleagues have that folder in their home (or elsewhere).

I would like to check if an environment variable is set (inside a `.env` file, for example) and, if not, I should stop the lane and ask the user to set it locally.
Is there something in `fastlane_core` that helps me in doing something like

```ruby
lane :beta do
  ensure_definition 'BTSYNC_FOLDER'

  # ...
  xctool :archive, [
    "--workspace", ENV['XCODE_WORKSPACE'],
    "--scheme", ENV['XCODE_SCHEME_BETA'],
    "--configuration", "BetaRelease",
    "--sdk", "iphoneos",
    ].join(" ")

  # Save archive to BTSync folder
  backup_xcarchive({
    destination: "#{ENV['BTSYNC_FOLDER']}/iOS Studio",
    zip: true
    })

  # ...
end
```

Btw I will opensource the action so you can integreate it in fastlane :)
Thanks

**Comment by eytanbiala** [comment]
If you use the xcodebuild action, you can use `archive_path`:
```
 xcodebuild(
  archive: true,
  archive_path: '~/Desktop/MyApp/MyApp.xcarchive',
  configuration: ...,
  scheme: ...,
  workspace: ...,
  )
```

**Comment by dral3x** [comment]
Thanks @eytanbiala but that's not the problem i'm having. 
Also I need to compress the archive so expliciting the archive path does not change anything to me.

**Comment by eytanbiala** [comment]
I guess I misunderstood :)
Are you asking for a way to verify the environment variable is set before continuing? If so, you can do this at the start of a lane, or in your `before_all` if it applies to all of your lanes:
```
raise "Archive destination is not set" unless ENV['BTSYNC_FOLDER']
```

Here's how you can set environment variables - https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#environment-variables

**Comment by dral3x** [comment]
That's what i was looking for. Thanks @eytanbiala !

**Comment by eytanbiala** [comment]
Cool, glad to help :+1:

**Comment by KrauseFx** [comment]
@dral3x I'll close this issue for now, feel free to re-open if you need anything :+1:

**Comment by dral3x** [comment]
Here I am.
PR #423

**Comment by KrauseFx** [comment]
Thank you @dral3x :+1:
