### ISSUE TITLE
for_lane broken by multiple platforms

### ISSUE THREAD

**Issue by jeremiegirault** [KrauseFx/fastlane#229]
I'm not a ruby guy but I played with the source files of credentials-manager

````ENV["FASTLANE_LANE_NAME"]```` now returns something like ````ios inhouse```` with platforms
therefore my ```` for_lane :inhouse ```` does not finds the good block

````for_lane "ios inhouse"```` is also not working  because of the to_sym.
Can you either remove the to_sym or handle the platform in for_lane ?

Thanks

**Comment by jeremiegirault** [comment]
I workaround with this in my Appfile :
````
if ENV["FASTLANE_LANE_NAME"] == "ios beta" then
   .. lane settings
end
````

**Comment by KrauseFx** [comment]
This is a very nice catch - completely forgot about the `for_lane`, thank you so much for reporting @jeremiegirault. 

I'll fix this over the next few days.

**Comment by KrauseFx** [comment]
This is fixed now, working on a new release :+1:
