### ISSUE TITLE
Error if deliver has any parameters

### ISSUE THREAD

**Issue by thisiscrazy4** [KrauseFx/fastlane#231]
In my fastlane if I pass any parameters to the deliver command I get this error: `You have to pass the options for 'deliver' in a different way. Please check out the current documentation on GitHub!`

This is all I have:

    lane :deploy do
        sigh
        deliver :force
    end

If I remove the force, then deliver runs successfully but then fails for other reasons (which is why I need to pass force)

**Comment by eytanbiala** [comment]
Since version 0.12.0 there is a new way to use deliver:
```
deliver(
  force: true,# Set to true to skip PDF verification
  beta: true, # Upload a new version to TestFlight
  skip_deploy: true, # To don't submit the app for review (works with both App Store and beta builds)
  deliver_file_path: './nothere' # Specify a path to the directory containing the Deliverfile
)
```
Check it out here - https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#deliver

**Comment by milch** [comment]
Also take a look at the [Migration Guide](https://github.com/KrauseFx/fastlane/blob/master/docs/MigrationGuide.md) in case you have any other issues, everything you need to change should be listed there.

**Comment by KrauseFx** [comment]
Thanks @eytanbiala and @milch for responding so quickly. 

As pointed out, please use the updated syntax posed by @eytanbiala and everything should work as expected :+1:
