### ISSUE TITLE
Method similar to screenshots_path for metadata

### ISSUE THREAD

**Issue by thisiscrazy4** [KrauseFx/fastlane#232]
My xcode project has about 20 targets, each target is a separate app and so I need to upload a different set of screenshots and metadata for each target. I setup different .env files and in my Deliverfile I use screenshots_path to specify the screenshots path for each target, is there a way to do the same thing for metadata?

**Comment by KrauseFx** [comment]
Sorry no, there is no way to specify a path for metadata right now. Feel free to submit this issue to `snapshot`, since this does not belong to `fastlane` itself.
