### ISSUE TITLE
Can't install builds via crashlytics after updating fastlane to 0.12.5

### ISSUE THREAD

**Issue by darrarski** [KrauseFx/fastlane#239]
After updating fastlane from version 0.12.4 to 0.12.5 builds submitted to Crashlytics Beta can't be installed on device. When downloading the app, alert appears "Unable to Download App. [...] could not be installed this time", which looks like provisioning profile issue.

There are no errors or warnings during lane execution. Everything looks good. My certificates and provisioning profiles setup is correct (I double checked it). Build prepared by "Archive" function in Xcode, then uploaded manually with Crashlytics OS X tool works without an issue. 

First the problem occurred on my MacBook with fastlane 0.12.5 installed, and I didn't realise that fastlane update could break it. Then I tried on my other computer with fastlane 0.12.4 installed. Several builds of the same app were delivered to testers via Crashlytics Beta without an issue, but I have noticed that I am using outdated version of fastlane. Just after updating fastlane to 0.12.4, the builds can no longer be installed on devices.

I am using only [crashlytics action](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/crashlytics.rb) from fastlane. To prepare and sign a build, I am using [my own action](https://gist.github.com/darrarski/bfd321c7a5531724746e).

**Comment by darrarski** [comment]
After further investigation it occurred that my problem is not connected to fastlane directly, as running Crashlytics' submit script from command line doesn't solve it. I am closing this issue, as this isn't the right place to complain :-)

**Comment by KrauseFx** [comment]
Sorry, what was the problem?

**Comment by darrarski** [comment]
@KrauseFx I am almost sure the Xcode was using different provisioning profiles, somehow cached on my computer, even when I removed them permanently from `~/Library/MobileDevice/Provisioning Profiles`. Something was wrong with mobile provisioning, but it's hard to say what exactly. Regenerating the profiles once again solved the problem.
