### ISSUE TITLE
clean_build_artifacts doesn't clean for multiple sigh app identifiers

### ISSUE THREAD

**Issue by codebreaker01** [KrauseFx/fastlane#243]
@lmirosevic  I am using multiple sign actions with different app_identifiers which creates multiple provisioning profiles in the directory. I am assuming the SIGH_PROFILE_PATH variable takes into account the last sigh used and only cleans that profile. Any way I could clean all my profiles? Thanks!

**Comment by lmirosevic** [comment]
In that case I would use the action "reset_git_repo" instead, and in combination with a "ensure_git_status_clean" at the beginning of your lane.

**Comment by codebreaker01** [comment]
@lmirosevic Yup did that. Thanks!
