### ISSUE TITLE
Specify IPA path as a parameter to deliver beta

### ISSUE THREAD

**Issue by eytanbiala** [KrauseFx/fastlane#244]
Currently it seems that deliver requires the IPA to be produced in the current directory.
Is it possible to provide a path to the IPA?

**Comment by codebreaker01** [comment]
@eytanbiala I think there is way checkout this doc https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

**Comment by KrauseFx** [comment]
`
fastlane action ipa
`

You can use the `destination` option.
