### ISSUE TITLE
Where should I keep sensitive data?

### ISSUE THREAD

**Issue by sarunw** [KrauseFx/fastlane#25]
If I want to use hipchat integration which required ENV["HIPCHAT_API_TOKEN"] set in before_all what is the proper way to do this? Hardcode in Fastfile would be security issue right if I commit this into git.

**Comment by KrauseFx** [comment]
Since this is an environment variable, you can set it however you want. 

You can use [dotenv](https://github.com/bkeepers/dotenv) or any other project to securely store your environment variables. 

Does that make sense?

**Comment by sarunw** [comment]
Thanks, that make sense.
