### ISSUE TITLE
The guide mentions setting up cocoapods and xctool correctly, but this information is nowhere to be found

### ISSUE THREAD

**Issue by akaralar** [KrauseFx/fastlane#251]
Hey,

Thanks for great toolchain. I want to setup cocoapods and xctool correct way, but don't know how to do so since it is not included in the docs folder. Is there somewhere else that I can learn how to set these up correctly?

**Comment by dhagerty9009** [comment]
For xctool, go to the [xctool](https://github.com/facebook/xctool) Github repo.

As for Cocoapods, make sure you've downloaded the latest version of the gem `gem install cocoapods`, and then run `pod init` in the root of your project's directory.

**Comment by akaralar** [comment]
@dhagerty9009 So I don't have to do any fastlane specific setup, just setup cocoapods itself?

**Comment by dhagerty9009** [comment]
@akaralar exactly.

**Comment by akaralar** [comment]
@dhagerty9009 alright makes sense, thanks for the info!

**Comment by KrauseFx** [comment]
Thank you @dhagerty9009 for helping :+1: 

`fastlane` just works :rocket:
