### ISSUE TITLE
a way of listing the users and access level in the itunesconnect.apple.com and Developer.apple.com

### ISSUE THREAD

**Issue by sfransen** [KrauseFx/fastlane#252]
a way of listing the users and access level in the itunesconnect.apple.com and Developer.apple.com

 I would like an tool that would list the user and access level in the both portals if possible.
 I have to maintain a large list of users in both portals and if someone leaves the company I have to make sure they are removed from the portals.

I just need to list them for now.
 Thanks

**Comment by KrauseFx** [comment]
This could be added to [spaceship](https://spaceship.airforce), but won't be part of `fastlane` directly.
