### ISSUE TITLE
`hockey` no longer supports all available arguments

### ISSUE THREAD

**Issue by larslockefeer** [KrauseFx/fastlane#253]
The `hockey` command no longer supports all arguments shown [here](http://support.hockeyapp.net/kb/api/api-versions#upload-version). Most notably:

* `teams`
* `mandatory`
* ~~`notes_type`~~

I think that this happened when actions were refactored to introduce `available_options` et al. Is this intended? If not, I can submit a pull request that adds support for these arguments again.

I am currently running version 0.12.5. I see that `notes_type` has been added in the meantime.

**Comment by KrauseFx** [comment]
Sorry, that shouldn't happen. The action is in `hockey.rb` in case you find time to add the missing configuration. Make sure to either set a `default_value` or `optional` so the user doesn't get asked for missing values :+1:

**Comment by KrauseFx** [comment]
Here's the file: https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/hockey.rb

**Comment by postmechanical** [comment]
`tags` also.

**Comment by KrauseFx** [comment]
I'll work on this right now :+1:

**Comment by postmechanical** [comment]
See this fork: https://github.com/keatongreve/fastlane

**Comment by KrauseFx** [comment]
I just went ahead and added all that: https://github.com/KrauseFx/fastlane/commit/120f08d405f7da4405ce7f90ff0d8718c66be08e

will be in the next release :+1: 

Thanks again everybody.

**Comment by postmechanical** [comment]
Thank you!

**Comment by larslockefeer** [comment]
Great! Thanks guys! :+1:
