### ISSUE TITLE
Additional params for lane

### ISSUE THREAD

**Issue by codebreaker01** [KrauseFx/fastlane#260]
I don't see this in the docs, but is it possible to add additional params to the lane?
Like for example, ```fastlane deploy patch``` would create a patched build.

**Comment by dhagerty9009** [comment]
I haven't found anything like that in the documentation. It's something that would be neat to have. I wonder if you can nest lanes and have it work almost like the multiplatform support, like so:
```ruby
lane :deploy do
  lane :patch do
    increment_version_number
  end
  deliver
end
```

**Comment by KrauseFx** [comment]
I like the idea. With the most recent update, we introduce an additional `platform` layer, but that won't solve your problem.

Right now the only way to pass information is using environment variables or files.

When you using environment variables:

```
mode="patch" fastlane deploy
```

not as pretty, but should do the job for now. What do you think?

**Comment by codebreaker01** [comment]
@KrauseFx  Sounds good for now.
