### ISSUE TITLE
[Feature] Action to add an External Tester to TestFlight

### ISSUE THREAD

**Issue by eytanbiala** [KrauseFx/fastlane#267]
It would be great to have an easy way to add external tester(s) to TestFlight.
I imagine it would be similar to the `register_devices` action, maybe something like this:
```
register_external_testers(
    testers: [
     {"firstName" => "John", "lastName" => "Doe", "email" => "johndoe@gmail,com"},
       ...
      }
])
```

or passing a csv file with the same info.

**Comment by KrauseFx** [comment]
I just added the required API end point to [itc-api-docs](https://github.com/fastlane/itc-api-docs#register-new-external-beta-tester). Feel free to integrate it into a `fastlane` action if you have some time :+1:

**Comment by KrauseFx** [comment]
This feature is now work in progress: https://github.com/fastlane/spaceship/pull/61

**Comment by KrauseFx** [comment]
I'll close this issue for now
