### ISSUE TITLE
Shenzen broken-need to also bump Snapshot version

### ISSUE THREAD

**Issue by vrao423** [KrauseFx/fastlane#268]
I see you downgraded the Shenzen version for fastlane. Now it creates a conflict with snapshot and I cannot bundle.

```
Bundler could not find compatible versions for gem "shenzhen":
  In snapshot (Gemfile.lock):
    shenzhen (0.14.1)

  In Gemfile:
    fastlane (>= 0) ruby depends on
      shenzhen (= 0.14.0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by KrauseFx** [comment]
Do you still run into this problem? Could you try running `sudo gem update`? Are you using `rvm`?

**Comment by KrauseFx** [comment]
I'll close this issue for now, feel free to re-open if you run into any problems.
