### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by tcurdt** [KrauseFx/fastlane#274]
Would be great to have support for OSX apps, too.

**Comment by KrauseFx** [comment]
They are supported already with `1.0`: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

`deliver` can already upload Mac screenshots and hockey will be able to upload `.app` files.

**Comment by tcurdt** [comment]
Oh cool. I'll give that a try.
Didn't find the docs for it.

**Comment by KrauseFx** [comment]
Yes, it's still much work in progress. I'm working on providing an example setup.

**Comment by KrauseFx** [comment]
@tcurdt you might want to check out https://github.com/fastlane/examples/tree/master/MindNode

More information following soon.

**Comment by KrauseFx** [comment]
You can open the `Fastfile` on the top :+1:

**Comment by KrauseFx** [comment]
This is now released
