### ISSUE TITLE
Lack of feedback when installing fastlane

### ISSUE THREAD

**Issue by yuppielabel** [KrauseFx/fastlane#275]
When running "sudo gem install fastlane" in the Terminal, there is not much feedback. I aborted a couple of times because I thought the install had stalled for some reason. Would appreciate more feedback like "Starting download", a progress bar or counting up bytes downloaded, a percentage or something, Anything would be better than the long wait..
Besides this, the docs and everything is just great! Thanks for the good work!

**Comment by KrauseFx** [comment]
Yes, I completely agree with you. Unfortunately the installation process is completely out of my control and is handled by RubyGems. 

Do you think a note in the README would also help?

**Comment by yuppielabel** [comment]
Yeah, you could probably mention something like "Depending on your internet connection, it can take up to 15 minutes before some form of feedback shows up when starting the install."
I can file an issue with RubyGems for some form of feedback right after typing the install command.

**Comment by KrauseFx** [comment]
Here we go: https://github.com/KrauseFx/fastlane/blob/master/README.md#installation

using the `--verbose` flag by default :+1:
