### ISSUE TITLE
[Feature] Execute actions from the CLI

### ISSUE THREAD

**Issue by yannrouillard** [KrauseFx/fastlane#281]
Hi,

Fastlane tools are really great and we are looking into integrating with a Continuous Integration server (jenkins). Our problem is that we still want to rely on Jenkins worflow features to allow people to visualize the pipeline, introduce validation steps and so on.

Basically we don't need really the lane feature, as the lane is defined in each workflow step inside Jenkins, but we are still interested to directly use fastlane actions and its systems of passing parameters between actions (although it would need modifications so that parameters are saved between two fastlane calls).

We can try to propose a patch for this but I am not sure if this use case fit with fastlane philosophy so I am first interested in having your feedback on this.

Thanks in advance,

Yann

**Comment by KrauseFx** [comment]
Hey @yannrouillard,

I can understand your use case and what you try to achieve. I don't think there is a good way of passing the fastlane context from one Jenkins job to the next one in a build pipeline. It's a ruby based hash which might contain complex objects.

I honestly don't think Jenkins will be the CI system of the future for `fastlane` - there will be better solutions available soon (at least I hope).

Do you also want to use the built-in actions (e.g. slack action) without using `fastlane`? I was thinking about providing a CLI to call `fastlane` actions directly without having to have a `Fastfile`. What do you think?

e.g.
```sh
fastlane run slack --message "Hello"
```

Thanks for your feedback :+1:

**Comment by mathiasAichinger** [comment]
@KrauseFx  This would be cool. 👍🏻

**Comment by KrauseFx** [comment]
@yannrouillard @mathiasAichinger out of curiosity: what would you use it for? What integrations are you interested in?

**Comment by KrauseFx** [comment]
@yannrouillard still here? :smiley:

**Comment by mathiasAichinger** [comment]
@KrauseFx it would be cool to test actions independently. and it could be the case that you have to upload an ipa file to hockey without using any step before...

**Comment by KrauseFx** [comment]
@mathiasAichinger Okay, so you'd pass parameters like the API key using the shell then? Technically it's very easily possible to implement this feature, just trying to think about a way to properly describe and "sell" this feature.

**Comment by mathiasAichinger** [comment]
@KrauseFx Yes, correct. The feature is useful for 'third-party'-actions because your tools can already be used via shell. Without this feature I have to create a temporary line to test the specific action.

**Comment by KrauseFx** [comment]
Thanks for your input @mathiasAichinger :tada:

**Comment by lukaskubanek** [comment]
Hi @KrauseFx, at the last CocoaHeads meeting in Dresden I've heard that it should be possible to run actions without the need to create a lane. I'd like to ask whether this feature has already been implemented, because I can't find any documentation about it.

**Comment by KrauseFx** [comment]
@lukaskubanek It's not possible, but now you can also pass parameters to your lanes from the CLI.

**Comment by lukaskubanek** [comment]
Thanks for the info!

**Comment by lukaskubanek** [comment]
@krausefx This was implemented in [version 1.31.0](https://github.com/KrauseFx/fastlane/releases/tag/1.31.0), wasn't it?

**Comment by KrauseFx** [comment]
This is now live, yes! Let me know how you like it :+1:

**Comment by timcamber** [comment]
Just wanted to say this is a really awesome feature and I love it! 👏🏻

**Comment by KrauseFx** [comment]
Thanks @timcamber :+1:

**Comment by pjchavarria** [comment]
+1 Great feature 👏🏻

**Comment by purrrminator** [comment]
Great! so how would I pass a payload from command line?

**Comment by TKBurner** [comment]
Hi @purrrminator I think you'll need to escape your string in a few places. Let me know how it goes! 👍

**Comment by purrrminator** [comment]
@TKBurner I've tried to escape several ways. Maybe missed something. Could you help?

**Comment by TKBurner** [comment]
@purrrminator Have you tried:

"\{text:\'hi\'\}"

**Comment by purrrminator** [comment]
@TKBurner 
```
.rvm/gems/ruby-2.0.0-p598@railstutorial_rails_4_0/gems/fastlane-1.70.0/lib/fastlane/actions/slack.rb:137:in `generate_slack_attachments': [!] undefined method `map' for "{text:\\'hi\\'}":String (NoMethodError)
```

**Comment by TKBurner** [comment]
Hi @purrrminator Thanks for following up. I want to isolate this to either a string parsing issue or a syntax issue. Can you try with a normal string without special characters {} or ' and let me know if you still see the same result? Thanks 👍
