### ISSUE TITLE
iTunesConnect And developer portal credentials

### ISSUE THREAD

**Issue by ssuchanowski** [KrauseFx/fastlane#284]
What if those accounts are different?

**Comment by ssuchanowski** [comment]
OK, I see that I can have credentials per lane - just need to separate iTunes actions from signing.

**Comment by KrauseFx** [comment]
@ssuchanowski yes, see how Wikipedia is solving it: https://github.com/fastlane/examples/blob/master/Wikipedia/Appfile :+1:
