### ISSUE TITLE
Wrong dependency to Frameit

### ISSUE THREAD

**Issue by mathiasAichinger** [KrauseFx/fastlane#285]
Hi,

today I checked out your project and I had a problem during `bundle install`. It failed because of the following error:
`Could not find gem 'frameit (>= 2.0.0) ruby', which is required by gem 'fastlane (>= 0) ruby', in any of the sources.`

I think frameit 2.0.0 doesn't exist yet, so I changed it back to `'frameit', '>= 1.0.0'`

**Comment by KrauseFx** [comment]
That is true, I'll release `frameit 2.0` tonight. Sorry, I should have waited with the version bump.

**Comment by KrauseFx** [comment]
Fixed with https://github.com/KrauseFx/fastlane/pull/286 :+1:
