### ISSUE TITLE
The guide has no content for Jenkins

### ISSUE THREAD

**Issue by brennanMKE** [KrauseFx/fastlane#287]
There is a link at the top of the page but no content.

https://github.com/KrauseFx/fastlane/blob/master/docs/Guide.md#jenkins-integration

**Comment by KrauseFx** [comment]
Thank you, fixed with https://github.com/KrauseFx/fastlane/commit/b2fea0bf03257f03c8ed5e18f2d72d12c5f37268. For Jenkins check out this document: https://github.com/KrauseFx/fastlane/blob/master/docs/Jenkins.md
