### ISSUE TITLE
Fastlane enhancer should be opt-in

### ISSUE THREAD

**Issue by zachwaugh** [KrauseFx/fastlane#288]
I just noticed the latest version of Fastlane now sends usage data by default to an [external service](https://github.com/fastlane/enhancer), which you have to opt-out of with `opt_out_usage`. I only discovered this because I noticed it in the logs:

```
DEBUG [2015-05-14 14:07:53.36]: Sending Crash/Success information. More information on: https://github.com/fastlane/enhancer
DEBUG [2015-05-14 14:07:53.36]: No personal/sensitive data is sent. Only sharing the following:
DEBUG [2015-05-14 14:07:53.36]: {:fastlane_version=>1}
DEBUG [2015-05-14 14:07:53.36]: This information is used to fix failing actions and improve integrations that are often used.
DEBUG [2015-05-14 14:07:53.36]: You can disable this by adding `opt_out_usage` to your Fastfile
```

I don't see it mentioned anywhere in the readme or other docs. Even if there is no sensitive data sent, anything like this should be opt-in.

**Comment by KrauseFx** [comment]
Yes, `fastlane` does track the number of uses per action + the number of errors per action to detect integration issues and fix problems faster.

I added more information about the statistics to the [project readme](https://github.com/KrauseFx/fastlane#statistics) and also added an explanation to the setup process. 

`fastlane` will only send the number for publicly available integration and does not send information about local actions to the server.

The data is used towards making better integration and to focus on working more popular integrations with an higher error rate.

Thank you for your feedback on this, I understand your point, but I'd like to keep it this way.

**Comment by zachwaugh** [comment]
No problem, and thanks for updating the readme. I do think the service is useful, but just that it should just be a choice for the user and privacy should always be the default.

**Comment by KrauseFx** [comment]
Thanks for understanding @zachwaugh and letting me know :+1:
