### ISSUE TITLE
define timeout when using xctest

### ISSUE THREAD

**Issue by dennissterzenbach** [KrauseFx/fastlane#289]
I really like the way of fastlane to simply run a lane to generate what it needs to test and deploy my apps. But unfortunately some of my machines are a little slow and need some time to fire up the simulator and install the app. For me this means that many times fastlane fails to successfully run xctest. I didn't find an option to tell the launch timeout to xctest/xcodebuild from the Fastfile.

So I wonder if there isn't such an option to use with fastlane or if you can integrate it easily?

Thanks in advance!

**Comment by KrauseFx** [comment]
Sorry, right now there is no option for that yet.

**Comment by dennissterzenbach** [comment]
Bummer! Any plans to add that in the next versions? 
I think options like for simulator timeout handling, fresh simulator, fresh install might be a really handy improvement, especially for a syntax like:
xctest(
    ....
    testOptions: {
        freshSimulator: true,
        freshInstall: true
    },
    launchTimeout: 240 # seconds
}

**Comment by KrauseFx** [comment]
No plans for it right now. Here is the source code for the `xctest` action: https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/xcodebuild.rb#L387

if you have some time to implement this, I'll happily merge a pull request.

**Comment by dennissterzenbach** [comment]
I had a short look at the code. As far as I can see, xcodebuild only supports a destination-timeout.
xctool for example would offer some more options for a test/run-test (like freshSimulator, resetSimulator etc.).
How do you think about integrating xctool for the XctestAction or in general?

**Comment by KrauseFx** [comment]
This is now implemented thanks to @samsonjs with https://github.com/KrauseFx/fastlane/issues/374 :+1:
