### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by pedro380085** [KrauseFx/fastlane#296]
Hi Felix,

Is there a tool to automatically resize the icon to the appropriate sizes?

Thank you for bringing fastlane alive!

**Comment by jsras** [comment]
I usually use this tool: http://makeappicon.com
I believe theres a ruby version also, but havent tried it. 
https://github.com/gmkou/makeAppIcon

**Comment by pedro380085** [comment]
Hi @jsras,

I thought about the problem for a few minutes and realized how simple it is to solve it. 

You just have to get your larger image (which is iTunesArtwork@2x), copy it and then resize using sips. Runs very well.

```
// Make a copy of a large image
[[NSFileManager defaultManager] copyItemAtURL:[currentCompanyDirectory URLByAppendingPathComponent:@"iTunesArtwork@2x.png"] toURL:cloudImageURL error:nil];
// Resize it to the its appropriate size
[CommandLineController runCommand:[NSString stringWithFormat:@"sips -Z %@ '%@'", [requiredIconsSizes objectAtIndex:i], [cloudImageURL path]]];
```
