### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by niklassaers** [KrauseFx/fastlane#298]
Hey guys,
My app is called "Well Tempered". I'm just getting started with fastlane, and when I run the project I get log messages such as:

[00:15:04]: [SHELL]: ▸ Touching Well

This should've been "Touching Well Tempered.app", right? 

Cheers

   Nik

**Comment by KrauseFx** [comment]
Not sure, I assume the output you posted is the `ipa` action, right? Could you share that part of your `Fastfile` + a more complete output? 

Thanks :+1:

**Comment by niklassaers** [comment]
Hi Felix,
sorry for my very late reply. I have just made sure to update all gems so I run the most current version.

I have posted my Fastfile here: https://www.dropbox.com/s/03noct3fkvmrdea/Fastfile?dl=0
and posted a complete build log here: https://www.dropbox.com/s/aku29rfq9c6vd97/output.log?dl=0

When I do "grep Well output.log|grep -v Tempered" I get:
[21:47:00]: [SHELL]: ▸ Touching Well
[21:47:21]: [SHELL]: ▸ Touching Well
[21:47:56]: [SHELL]: ▸ Touching Well
[21:48:10]: [SHELL]: ▸ Touching Well
[21:48:12]: [SHELL]: ▸ Touching Well
[21:48:28]: [SHELL]: ▸ Touching Well
[21:48:28]: [SHELL]: ▸ Touching Well
[21:48:59]: [SHELL]: ▸ Touching Well
[21:49:06]: [SHELL]: ▸ Touching Well

Am I doing something wrong here?

Cheers

   Nik

**Comment by KrauseFx** [comment]
The output is generated by [shenzhen](https://github.com/nomad/shenzhen). Does it work? Is the output the only thing that's wrong?

**Comment by niklassaers** [comment]
Yes, it's just the output, I haven't noticed any effects, so I don't believe there are any. :-)

I didn't realize this was shenzhen, should I report it there instead?

**Comment by KrauseFx** [comment]
If it's just the output, I wouldn't spend any more time into this :wink:

**Comment by niklassaers** [comment]
&#x1f44d;
