### ISSUE TITLE
increment_version_number not working for X.XX.X versions

### ISSUE THREAD

**Issue by bachonk** [KrauseFx/fastlane#304]
I'm trying to use `increment_version_number` to increment the minor version number of an app with the version `1.10.0`

I'm doing the following:
```
increment_version_number(
      bump_type: "minor"
    )
```

If the current version number is `1.9.0`, everything works as expected.

If the current version number is `1.10.0`, I receive the following error:
```
[17:10:06]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios releaseprep"}
[17:10:06]: Your current version (1.10.0) does not respect the format A.B.C
[17:10:06]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.3/lib/fastlane/actions/increment_version_number.rb:38:in `run': Your current version (1.10.0) does not respect the format A.B.C (RuntimeError)
```

Seems that incrementing the minor version of any app in the format X.XX.X fails. So far, other formats such as XX.X.X and X.X.XX have worked.

On a related note, incrementing version numbers in the format X.X fails, but Apple suggests using 2-digit version numbers as a marketing version, so I'm curious why this is prevented.

**Comment by KrauseFx** [comment]
Thank you for letting me know, the regex was wrong, I just pushed a fix, this will be in the next release :+1:

**Comment by bachonk** [comment]
Awesome! Any thoughts on supporting X.X version numbers?

**Comment by KrauseFx** [comment]
Sorry, I don't know. If you prepare a pull request for it, I can merge it :+1:
