### ISSUE TITLE
Create a Gitter room for Fastlane?

### ISSUE THREAD

**Issue by KiranPanesar** [KrauseFx/fastlane#309]
What are the core team's thoughts on creating a [Gitter](https://gitter.im/) room for Fastlane? While building out our automation I've had a couple of questions/issues. Questions and issues should eventually make their way back to Github as tickets or entries in READMEs, but having a quick chat area would really expedite things.

**Comment by KrauseFx** [comment]
We have a Slack channel for core contributors and users interested in `fastlane`. I sent you an invite. For everyone else reading this, drop me a message if you want to join as well :+1:
