### ISSUE TITLE
Fastlane init: it should ask if I need to enable cocapods

### ISSUE THREAD

**Issue by artem-alexandrov** [KrauseFx/fastlane#31]
Right now it's enabled by default, but I don't need it at each build (it's kinda long operation you know..)
is it possible to add a question about cocapods step (like it does for deliver for example)

**Comment by KrauseFx** [comment]
It only enables CocoaPods if `fastlane` finds a `Podfile` in the current directory.

You can easily just remove the `cocoapods` line from the `Fastfile`. Or is that a problem somehow?

**Comment by artem-alexandrov** [comment]
Just don't want to touch config files after initial setup) It would be easier to make required settings on initialization

**Comment by KrauseFx** [comment]
You probably will have to touch the `Fastfile` and the other configuration files. `fastlane` will just help you to setup a sensible default configuration.
