### ISSUE TITLE
Different apple IDs for cert and deliver?

### ISSUE THREAD

**Issue by yusefnapora** [KrauseFx/fastlane#311]
Is it possible to use different Apple Ids for the `cert` and `deliver` actions?
If I set an `apple_id` in the `Appfile`, it will be used for both, but due to
Apple's insanely broken Apple Id system, I need a separate Apple ID to use
iTunes Connect with personal developer account and that of my team.

The Apple ID that works with iTunes Connect is not registered with the iOS
Developer Center, so I'd like to be able to get the certificate and profiles using
my "developer" id, and upload the app to iTunes with another.

The `cert` action log output says to set the `DELIVER_USER` environment
variable if I don't specify an `apple_id` in the `Appfile`, but that would apply
to both `cert` and `deliver`, right?

Also, here it looks like `cert` is checking the `CERT_USERNAME` env variable
instead of `DELIVER_USER`: https://github.com/fastlane/cert/blob/0.2.0/lib/cert/options.rb#L14

But setting `CERT_USERNAME` doesn't seem to have an effect when running
`cert` from the command line or in fastlane.

Thanks!

**Comment by yusefnapora** [comment]
After reading some more docs, it looks like I can just pass a `username: user@place.com` argument into the `cert` action, which I can derive from an environment variable if need be.

I'm going to close this, sorry to bug you :smile:

**Comment by KrauseFx** [comment]
Great to hear :+1:
