### ISSUE TITLE
How to set Environment Variables and how to use them

### ISSUE THREAD

**Issue by Darkreaper101** [KrauseFx/fastlane#319]
Hi,
Sorry this is probably a stupid question, I'm new to ruby and fastlane.

But can someone maybe help me and tell me how I can use the DELIVER_USER and DELIVER_PASSWORD in my fastfile.

- How do I set them?
- How do I use them in a lane?
- Can I specify different username's and passwords for different lanes?
- Will this environment variables be available to the entire lane/lanes?

Again sorry for the noob questions. :smiley: 

Regards

**Comment by KrauseFx** [comment]
Environment variables are not fastlane specific. 

You can set them like this:

```
DELIVER_USER="felix@krausefx.com" fastlane test
```

or

```
export DELIVER_USER="felix@krausefx.com";
fastlane test
```

Within your `Fastfile` you can also set environment variables:

```
ENV["DELIVER_USER"] = "felix@krausefx.com"
```

Or in most actions you can just pass the username:

```
fastlane action sigh
```

will show you that you can use

```
sigh(username: "felix@krausefx.com")
```

in your `Fastfile`

Does that help?

**Comment by Darkreaper101** [comment]
Hi Felix,

Yes that helps a lot thank you very much.
I do appreciate it a lot. :smile: 

Regards
