### ISSUE TITLE
ensure_git_branch action

### ISSUE THREAD

**Issue by dbachrach** [KrauseFx/fastlane#323]
I'm wondering if there's interest in a `ensure_git_branch` action that would enforce that a lane can only be run on a certain branch.

As an example, we may want a `fastlane appstore` to only work on `master`.

I can go ahead and work on this if we think there's shared value.

**Comment by KrauseFx** [comment]
No, there is no such action right now. I like the idea.

Would be great if you could implement it. Use the `fastlane new_action` command to create a local template.

Take a look at how to access the used branch [here](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/slack.rb#L138), should be easy to add :+1:

**Comment by dbachrach** [comment]
This was merged in  https://github.com/KrauseFx/fastlane/pull/332

Closing.
