### ISSUE TITLE
[Feature] Action to change App group identifier in the Entitlements files

### ISSUE THREAD

**Issue by mathiasAichinger** [KrauseFx/fastlane#328]
This can be used to change Apps from an App Store account to an Enterprise account(Inhouse-Distribution). The app groups are used for communication between app and extensions.

I will implement this after WWDC.

**Comment by KrauseFx** [comment]
Great, looking forward :+1:

**Comment by mathiasAichinger** [comment]
Closed with b93235ff1e788235e110412b8e23af064e128ec6 .

**Comment by mathiasAichinger** [comment]
@KrauseFx should this stay open until it's released?

**Comment by KrauseFx** [comment]
Thanks, we'll leave it closed :+1:
