### ISSUE TITLE
Possible to pass fastlane a .app or .zip?

### ISSUE THREAD

**Issue by Darkreaper101** [KrauseFx/fastlane#330]
Good Day,

I would like to know if it's possible to pass fastlane a <b>.app or .zip</b> file that contains the app instead of passing a <b>.ipa</b> file through for the <b>App Store side of things</b>?

This would be awesome if it's possible would solve so many of my problems...

Regards

**Comment by KrauseFx** [comment]
Hey @darkreaper101, an `ipa` file is just a compressed `.app` folder. You can easily add this to your `Fastfile`:

```ruby
lane :beta
  `zip .....` # your custom shell command to prepare the ipa file
  deliver
end
```

**Comment by Darkreaper101** [comment]
Ah okay cool thanks sorry still new to the whole IOS thing. :smile:
