### ISSUE TITLE
Archive successfully created, but fastlane reports build error

### ISSUE THREAD

**Issue by Ziewvater** [KrauseFx/fastlane#331]
Trying to build and deploy a beta version of an app to iTunesConnect using fastlane. The lane declaration looks like:

```
before_all do
    cocoapods
    increment_build_number
    cert
    sigh
end

lane :beta do
    ipa(
	workspace: "[APP NAME].xcworkspace",
   	scheme: "[APP NAME]-demo" 
    )
    # commented out `deliver` to see if it is causing errors, determined that it's not.
    #deliver(
    #	skip_deploy: true,
    #	beta: true
    #)
end
```

Running `fastlane beta` results in 

```
// lots of compiling files, warnings, etc.
▸ Copying [APP NAME]/[APP NAME]-source.sqlite
▸ Processing [APP NAME]-Info.plist
▸ Generating '[APP NAME]-demo.app.dSYM'
▸ Running script 'Copy Pods Resources'
▸ Touching [APP NAME]
▸ Signing /Users/JeremyYL/Library/Developer/Xcode/DerivedData/[APP NAME]-aojamicklltpjsbgcavnjdsoxrjo/Build/Intermediates/ArchiveIntermediates/[APP NAME]-demo/InstallationBuildProductsLocation/Applications/[APP NAME]-demo.app
▸ Touching [APP NAME]
** ARCHIVE FAILED **


[11:25:02]: A build error occured. This can have many reasons, usually
[11:25:02]: it has something to do with code signing. The `ipa` action
[11:25:02]: uses `shenzhen` under the hood: https://github.com/nomad/shenzhen
[11:25:02]: The command that was used by fastlane:
[11:25:02]: krausefx-ipa build -w "[APP NAME].xcworkspace" -s "[APP NAME]-demo" -m "/Users/JeremyYL/Developer/[PROJECT FOLDER]/Distribution_[PROVISIONING PROFILE NAME].mobileprovision" --verbose | xcpretty
[11:25:02]: -------------------------------------------------------
[11:25:02]: Variable Dump:
[11:25:02]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>46, :CERT_FILE_PATH=>"/tmp/cert/2Y5RBGP8SW-R58UK2EWSO.cer", :CERT_CERTIFICATE_ID=>"2Y5RBGP8SW", :SIGH_PROFILE_PATH=>"/Users/JeremyYL/Developer/[PROJECT FOLDER]/Distribution_[PROVISIONING PROFILE NAME].mobileprovision", :SIGH_UDID=>"5226c81a-3e67-48e6-9763-cf6628755803"}
[11:25:02]: A build error occured, this is usually related to code signing. Take a look at the error above
[11:25:03]: fastlane finished with errors
/Users/JeremyYL/.rvm/gems/ruby-2.2.0/gems/fastlane-1.3.2/lib/fastlane/actions/ipa.rb:94:in `rescue in run': A build error occured, this is usually related to code signing. Take a look at the error above (RuntimeError)
// ruby stacktrace
```

No extra info on what the error is. Stranger still, the archive doesn't actually fail; each time I run this a new archive appears in the Projects organizer's Archives tab. I've even uploaded one to iTunesConnect to see if it was built correctly, and iTC doesn't seem to have any issues with it. 

Any tips on how to get a little more info on what's going on here? I tried to look and see if the `ipa` action had more verbose output, but it didn't seem like it.

**Comment by KrauseFx** [comment]
Can you run
```
krausefx-ipa build -w "[APP NAME].xcworkspace" -s "[APP NAME]-demo" -m "/Users/JeremyYL/Developer/[PROJECT FOLDER]/Distribution_[PROVISIONING PROFILE NAME].mobileprovision" --verbose | xcpretty
```

and 

```
krausefx-ipa build -w "[APP NAME].xcworkspace" -s "[APP NAME]-demo" -m "/Users/JeremyYL/Developer/[PROJECT FOLDER]/Distribution_[PROVISIONING PROFILE NAME].mobileprovision" --verbose
```

yourself and see if you get any useful output?

**Comment by Ziewvater** [comment]
Running the first command results in similar output to running `fastlane beta`:

```
// Lots of output
▸ Processing [APP NAME]-Info.plist
▸ Generating '[APP NAME]-demo.app.dSYM'
▸ Running script 'Copy Pods Resources'
▸ Touching [APP NAME]
▸ Signing /Users/JeremyYL/Library/Developer/Xcode/DerivedData/[APP NAME]-aojamicklltpjsbgcavnjdsoxrjo/Build/Intermediates/ArchiveIntermediates/[APP NAME]-demo/InstallationBuildProductsLocation/Applications/[APP NAME]-demo.app
▸ Touching [APP NAME]
** ARCHIVE FAILED **
```

Running the second give a bit more detail, but nothing that helps me very much. The final part that runs is the `touch` command:
```
Touch /Users/JeremyYL/Library/Developer/Xcode/DerivedData/[APP NAME]-aojamicklltpjsbgcavnjdsoxrjo/Build/Intermediates/ArchiveIntermediates/[APP NAME]-demo/BuildProductsPath/Release-iphoneos/[APP NAME]-demo.app.dSYM
    cd /Users/JeremyYL/Developer/[PROJECT FOLDER]
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/JeremyYL/.rvm/gems/ruby-2.2.0/bin:/Users/JeremyYL/.rvm/gems/ruby-2.2.0@global/bin:/Users/JeremyYL/.rvm/rubies/ruby-2.2.0/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/Users/JeremyYL/.scripts:/usr/local/bin:/Users/JeremyYL/.rvm/bin"
    /usr/bin/touch -c /Users/JeremyYL/Library/Developer/Xcode/DerivedData/[APP NAME]-aojamicklltpjsbgcavnjdsoxrjo/Build/Intermediates/ArchiveIntermediates/[APP NAME]-demo/BuildProductsPath/Release-iphoneos/[APP NAME]-demo.app.dSYM

** ARCHIVE FAILED **
```

Both commands resulted in an archive being built that is recognized by Xcode in it's Organizer.

Perhaps `touch` is exiting with an error code? If you need more context, I can get you more of the console output, but there is quite a bit to copy over. I wasn't sure how much would actually be helpful.

**Comment by KrauseFx** [comment]
@Ziewvater Thanks for the information. You'll even see the `xcodebuild` command when executing the command without the `xcprety`. Can you try running the `xcodebuild` command only? It will be printed out right after running the command.

**Comment by Ziewvater** [comment]
`xcodebuild` command I found was 
``` bash
xcodebuild -sdk iphoneos -workspace "[APP NAME].xcworkspace" -scheme "[APP NAME]-demo" -configuration 'Release' clean build archive
```

The archive still reports as failing, but the archive appears in Xcode's Organizer. The console printout seems to be the same as when running through fastlane. Is there anything I can look for that would help better diagnose this issue?

**Comment by rmischook** [comment]
I'm seeing the exact same thing as reported above. Here's a slightly redacted version of what I see.

krausefx-ipa build -s "[REDACTED SCHEME NAME]" -c "Release" -m "[REDACTED].mobileprovision" -i "iPhone Distribution: [REDACTED] ([REDACTED])" --verbose

.... 

Touch /Users/richmischook/Library/Developer/Xcode/DerivedData/[REDACTED SCHEME NAME]-hiifyztwiozhldbqaanwwdzpjsbr/Build/Intermediates/ArchiveIntermediates/[REDACTED SCHEME NAME]/BuildProductsPath/Release-iphoneos/[REDACTED APP NAME].app.dSYM
    cd /Users/richmischook/development/github/[REDACTED APP NAME]
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/richmischook/gradle-2.4/bin/"
     /usr/bin/touch -c /Users/richmischook/Library/Developer/Xcode/DerivedData/[REDACTED SCHEME NAME]-hiifyztwiozhldbqaanwwdzpjsbr/Build/Intermediates/ArchiveIntermediates/[REDACTED SCHEME NAME]/BuildProductsPath/Release-iphoneos/[REDACTED APP NAME].app.dSYM

** ARCHIVE FAILED **

As reported by @Ziewvater the archive IS created and shows up in Organiser and indeed Crashlytics App sees it.

Further info:

richmischook$ krausefx-ipa --version
krausefx-ipa 0.14.2

richmischook$ deliver --version
deliver 0.12.0

richmischook$ fastlane --version
fastlane 1.3.2

**Comment by rmischook** [comment]
UPDATE: turns out my Scheme was building my 'Acceptance Tests' target - which was un-signable due to bundle id conflict. Removing that led to new issues. It seems that 'fastlane deploy' is ignoring the 'embed' parameter for ipa as specified in the Fastfile. In the 'krausefx-ipa build' command that is generated it is referencing - I think - the NAME of the mobile provisioning file specified in Xcode but perhaps expecting it to exist in the project directory. So the following error is generated:

▸ Touching [REDACTED APP NAME].app.dSYM
error: Unable to copy '[REDACTED PROVISIONING PROFILE FILE NAME].mobileprovision' to '/var/folders/j1/m7n83v850wj1yf40zj7f0jv00000gn/T/gOgsPzbffM/Payload/[[REDACTED APP NAME]].app/embedded.mobileprovision'
 
If I call 'krausefx-ipa build ....' directly and specify the mobile provisioning profile to use with the -m switch - it works. Alternatively if I rename the .mobileprovision file pulled down by SIGH it works.

**Comment by rmischook** [comment]
Maybe I should be using SPACESHIP to pull down the Profile I need and write it out to the file name @KrauseFx?

**Comment by samsonjs** [comment]
Thanks @rmischook, that was my problem too. I had to uncheck the test target under Run in the build section of my scheme.

**Comment by ivanguajana** [comment]
@samsonjs @rmischook unchecking the test target under Run in the build section of my scheme fixed it for me too. Thanks!

**Comment by KrauseFx** [comment]
Great to hear this issue is resolved now. Feel free to submit a new one if you run into any more problems.

**Comment by craigmarvelley** [comment]
@KrauseFx I had this issue too - out of interest, why does Fastlane/shenzhen uses the 'run' process to create the IPA? I'd have assumed it would use the archive one?

**Comment by KrauseFx** [comment]
@craigmarvelley no reason, that's just how `shenzhen` works right now. I'm working on a new tool that will replace `shenzhen` soon :+1:

**Comment by angelolloqui** [comment]
Same issue here! I was also expecting an archive operation. @KrauseFx, when you say you are working now in a new tool, do you expect it within weeks time or months time to be released? I am setting up a new CI server and I would love to see this in there :) 

Thank you so much for your awesome work!

**Comment by KrauseFx** [comment]
@angelolloqui You can already give the new tool a try [here](https://github.com/fastlane/gym). Let me know of anything that should be improved before the initial release :+1:

**Comment by angelolloqui** [comment]
I just tried and I get an error:

```
Results at '/var/folders/30/1czz094d4wg6mqy86n3pkj_c0000gp/T/864E0865-D95C-4856-A8F2-B5B8318D0FFB-9526-00001BA6C8548725/TheCorner.ipa'
Moving exported product to '/Users/Angel/Library/Developer/Xcode/Archives/2015-08-10/TheCorner.ipa'
** EXPORT SUCCEEDED **
/Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/error_handler.rb:74:in `handle_package_error': Error packaging up the application (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/runner.rb:78:in `block in package_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/runner.rb:162:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/runner.rb:162:in `execute_command'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/runner.rb:77:in `package_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/commands_generator.rb:46:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/commands_generator.rb:63:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/lib/gym/commands_generator.rb:19:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.0.1/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'
```


but the nice thing about your tool vs shenzhen is that I got a better message just before this error:

```
### Checking original app
+ /usr/bin/codesign --verify -vvvv /var/folders/30/1czz094d4wg6mqy86n3pkj_c0000gp/T/864E0865-D95C-4856-A8F2-B5B8318D0FFB-9526-00001BA6C8548725/TheCorner.app
Program /usr/bin/codesign returned 1 : [/var/folders/30/1czz094d4wg6mqy86n3pkj_c0000gp/T/864E0865-D95C-4856-A8F2-B5B8318D0FFB-9526-00001BA6C8548725/TheCorner.app: a sealed resource is missing or invalid
file missing: /private/var/folders/30/1czz094d4wg6mqy86n3pkj_c0000gp/T/864E0865-D95C-4856-A8F2-B5B8318D0FFB-9526-00001BA6C8548725/TheCorner.app/archived-expanded-entitlements.xcent
]
Codesign check fails : /var/folders/30/1czz094d4wg6mqy86n3pkj_c0000gp/T/864E0865-D95C-4856-A8F2-B5B8318D0FFB-9526-00001BA6C8548725/TheCorner.app: a sealed resource is missing or invalid
file missing: /private/var/folders/30/1czz094d4wg6mqy86n3pkj_c0000gp/T/864E0865-D95C-4856-A8F2-B5B8318D0FFB-9526-00001BA6C8548725/TheCorner.app/archived-expanded-entitlements.xcent
```

So at least it is providing me with valuable feedback... I will continue checking why this happens later this week (I have no time now).

Thanks!

**Comment by KrauseFx** [comment]
@angelolloqui yes, that was the goal of `gym`: You get a minimal output when everything works fine and get as much relevant information as possible if the build fails.
