### ISSUE TITLE
Always get "ERROR ITMS-90046" while deliver to iTunesConnect

### ISSUE THREAD

**Issue by syshen** [KrauseFx/fastlane#336]
I am always running into an error in the "deliver" action:

    [17:16:11]: [Transporter Error Output]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/EMQ.app/EMQ' is not supported."

I googled around, and tried sigh and resign actions, but that doesn't help. I double check the provisioning profile that the "sigh" action downloads, it looks fine, the "maps-environment" in the provisioning profile is "production", not "development". Is there anyone has similar issue like me? 

And here is the Fastfile

    lane :deliver_demo do
    #   increment_build_number
        sigh(output_path: "./fastlane/profiles")
        ipa(
          workspace: 'EMQ.xcworkspace',
          configuration: 'Debug',
          scheme: 'EMQ-Demo',
          ipa: 'EMQ-Demo.ipa',
          embed: './fastlane/profiles/Distribution_com.emq.emqapp.mobileprovision',
          identity: 'iPhone Distribution: EMQ Limited (28HUT34N52)',
          clean: true,
        )
        resign(
          ipa: 'EMQ-Demo.ipa',
          signing_identity: 'iPhone Distribution: EMQ Limited (28HUT34N52)',
        )
        deliver(
          beta: true,
          skip_deploy: true,
        )
    end

**Comment by KrauseFx** [comment]
The best way to do code signing right is to set the provisioning profile in the project settings, since there is a bug in the `xcodebuild` command. Please update your project file and try again. You'll not need resigning or specifying the `embed` and `identity` any more.

**Comment by syshen** [comment]
@KrauseFx Thanks. The solution works!

**Comment by KrauseFx** [comment]
Where should I put this information to make it easier for new users?

**Comment by syshen** [comment]
Maybe a FAQ document?
