### ISSUE TITLE
How exactly does one specify provisioning-profile and signing-identity for a Release-build?

### ISSUE THREAD

**Issue by lukas2** [KrauseFx/fastlane#337]
Sorry if this is a newbie question, but how exactly do I tell Fastlane to generate a Release-app and also include the ad-hoc mobile provisioning-profile so it can be installed on our test-devices?

I tried setting the "embed" parameter in Fastfile, but no matter what string I tried for the identity-parameter, it would not work. When I dragged the generated ida-file onto my phone using Xcode it would complain that either "no valid provisioning profile" is found or the entitlements don't match the provisioning profile.

Any help is very appreciated.

**Comment by KrauseFx** [comment]
The easiest and best way is to configure the provisioning profile and code signing identity in your Xcode project and code signing will work automatically :+1:

**Comment by lukas2** [comment]
Hmm. Ok some progress. 

If I manually run the command `krausefx-ipa build -d "./ipa"` it works. It asks me what Scheme I want and what Configuration I want. The resulting .ipa can be installed on my phone.

However, if I specify everything in the command, by typing `krausefx-ipa build -s "Release" -c "Release" -d "./ipa"` it creates an .ipa with bad signing. It won't run on the phone.

I want to build in Jenkins so I need to specify it in one line. Is this a bug? I will try using an older version of fastlane next.

**Comment by lukas2** [comment]
Ok, same problem with version 1.2.1.

I don't see how there's a difference between specifying scheme and configuration or being asked for it.

**Comment by lukas2** [comment]
Hm won't work, because in the end the signing is not correct. It could have something to do with https://github.com/nomad/shenzhen/issues/165 , but not sure.

**Comment by mathiasAichinger** [comment]
@lukas2 you can look into the example from mindnode: https://github.com/fastlane/examples/blob/master/MindNode/Fastfile There the udid of the right provisioning profile is set via environment variable. Another solutions would be to use the `update_project_code_signing`-action

**Comment by mathiasAichinger** [comment]
@lukas2 @KrauseFx just saw that there is a new readme about codesigning: https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md 👍🏻

**Comment by KrauseFx** [comment]
Thanks @mathiasAichinger, I'll close this issue for now :+1:

**Comment by Ben-G** [comment]
This link is dead: https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md
Is setting the profile directly in Xcode still the recommended way of handling this? I would like to switch the profile for different lanes but can also accomplish it with a separate script.

**Comment by KrauseFx** [comment]
The most up to date documentation on how to do that is using https://codesigning.guide
