### ISSUE TITLE
Permission denied - fork failed

### ISSUE THREAD

**Issue by kdawgwilk** [KrauseFx/fastlane#34]
Trying to run my own custom shell script and I'm getting permission denied:

[SHELL COMMAND]: ./ipa.sh
INFO [2015-02-06 11:43:31.74]: Variable Dump:
INFO [2015-02-06 11:43:31.74]: {:LANE_NAME=>:beta, :START_TIME=>2015-02-06 11:42:01 -0700, :BUILD_NUMBER=>0, :SIGH_PROFILE_PATH=>"path/to/app.mobileprovision"}
FATAL [2015-02-06 11:43:31.74]: Permission denied - fork failed
FATAL [2015-02-06 11:43:31.75]: fastlane finished with errors

What am I doing wrong?

**Comment by kdawgwilk** [comment]
refer to isuse #27

**Comment by KrauseFx** [comment]
What's the current status of this problem? I'll close the issue for now, feel free to re-open if you're still experiencing problems.
