### ISSUE TITLE
How do you use with multiple targets

### ISSUE THREAD

**Issue by walsht** [KrauseFx/fastlane#341]
I have one project with multiple targets.  Each target is a different app, how do I use fastlane for each app?

**Comment by KrauseFx** [comment]
Take a look at previous issues: https://github.com/KrauseFx/fastlane/issues/88 and https://github.com/KrauseFx/fastlane/issues/8

I guess I'll have to update the documentation to make this more clear.

**Comment by KrauseFx** [comment]
@joshdholtz If you find some time, it would be amazing if you could add a new `.md` file to `./docs` briefly explaining your method :+1:

**Comment by walsht** [comment]
#88 worked perfectly thanks.  Only thing I have to figure out is how to populate the meta data in the delivery file. I have 7 languages, guess I can make a ENV veriable for each, but that could be a pain for the keywords.  @KrauseFx any thoughts on that?

**Comment by KrauseFx** [comment]
@walsht where does the metadata come from? From a remote server? If so, you can put the web requests right into your `Deliverfile` :+1:

**Comment by walsht** [comment]
@KrauseFx I was just going to put it into the ```Deliverfile``` like so
```
title(
  "en-US" => "title en", 
   "cmn-Hans" => "title cmn-Hans", 
   "es-ES" => "title es", 
   "fr-FR" => "title fr", 
   "it-IT" => "title it",
   "de-DE" => "localized detail",
    "ja-JP" => "localized detail", 
    "ko-KR" => "localized detail", 
    "pt-PT" => "localized detail", 
    "ru-RU" => "localized detail" 
) 
```
Do you know if the .env file can handle dictionary arrays, like this?
```
title(ENV['TITLE'])
```

**Comment by KrauseFx** [comment]
Environment variables are simple string values and cannot contain dictionaries. Where does the metadata come from?

**Comment by walsht** [comment]
I am actually going to follow one of the examples https://github.com/fastlane/examples/blob/master/BeMyEyes/Deliverfile
Looks like a good solution for me.
Thanks,

**Comment by KrauseFx** [comment]
For people coming from Google, check out the [Guide to use fastlane for apps with multiple targets](https://docs.fastlane.tools/faqs/#multiple-targets-of-the-same-underlying-app).
