### ISSUE TITLE
How to select provisioning profile for signing?

### ISSUE THREAD

**Issue by sneps85** [KrauseFx/fastlane#345]
I'm trying to set the provisioning profile for signing the app manually. I tried to set the cert_owner_name in the Fastfile configuration as parameter for the sigh command. But it does not work.
I also tried to set provisioning_name, but everytime it generates a new provisioning profile (with com.vendor.app as bundle id) instead of using the desired existing one (which uses * as bundle identifier).

How to force using a specific provisioning profile instead of creating one?

**Comment by KrauseFx** [comment]
I assume you're talking about [sigh](https://github.com/KrauseFx/sigh)? `sigh` will automatically download an existing profile if it's valid and can be downloaded.

**Comment by KrauseFx** [comment]
Also, I just recently published a guide on how to do code signing [here](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) :+1:
