### ISSUE TITLE
fastlane not responsive

### ISSUE THREAD

**Issue by gbasile** [KrauseFx/fastlane#346]
In my environment fastlane is not responsive for the first 10/20 seconds after I execute any command.
After this time, the command is executed normally.

**Comment by KrauseFx** [comment]
True, this has to do with an old version of gem, which you have installed. If you know a bit about Ruby you can update using `rvm`. If not, I hope Apple updated the Ruby dependencies with the new Mac OS X. This is out of my control unfortunately.

**Comment by gbasile** [comment]
Ok, thanks for the information. Can you tell me exactly what to update?

**Comment by gbasile** [comment]
Fixed using rvm
