### ISSUE TITLE
Nil Exception

### ISSUE THREAD

**Issue by thedamfr** [KrauseFx/fastlane#352]
```
[12:36:09]: Original Error:
[12:36:09]:  => Exit status of command 'set -o pipefail && krausefx-ipa build -w "Tripndrive.xcworkspace" -s "Tripndrive-Inte2" --clean --archive --verbose | xcpretty' was 256 instead of 0.
error: undefined method `include?' for nil:NilClass. Use --trace to view backtrace
```
Looks like a corner case line 27 in shenzhen-0.3.1/lib/shenzhen/commands/build.rb

```
    determine_configuration! unless @configuration
    say_error "Configuration #{@configuration} not found" and abort unless @xcodebuild_info.build_configurations.include?(@configuration)
```

**Comment by KrauseFx** [comment]
Nice catch, thanks :+1:

**Comment by KrauseFx** [comment]
Oh, that's an issue of [shenzhen](https://github.com/nomad/shenzhen) which is used under the hood to build and sign your app. You can submit the issue over there :+1:

**Comment by thedamfr** [comment]
Yeah I noticed I had Shenzen installed. I removed it and I don't have it on
your fork. You can close. Sorry.

Le mer. 17 juin 2015 à 13:47, Felix Krause <notifications@github.com> a
écrit :

**Comment by KrauseFx** [comment]
Thanks :+1:
