### ISSUE TITLE
Feature - MailGun should have a template

### ISSUE THREAD

**Issue by thiagolioy** [KrauseFx/fastlane#353]
Would be nice to have a mail template , i should have done this when i've created the mailgun action .

**Comment by thiagolioy** [comment]
Resolved here => https://github.com/KrauseFx/fastlane/pull/355

**Comment by KrauseFx** [comment]
Thanks for providing this pull request. I'll close this issue for now to move further discussion to https://github.com/KrauseFx/fastlane/pull/355 :+1:
