### ISSUE TITLE
Is it possible to test the configuration?

### ISSUE THREAD

**Issue by mortenholmgaard** [KrauseFx/fastlane#354]
Is it possible to test the configuration without it actually does any thing?
Something like compile the script to check for errors and mabye also run it where results will be written to the terminal but the action will not be fully executed.

**Comment by KrauseFx** [comment]
> the terminal but the action will not be fully executed.

Which action are you referring to? All actions?

Sorry, that's not possible right now. I see a use case for just verifying that a `Fastfile` is valid, but executing `fastlane` in a read-only mode wouldn't work probably, as this would require all integrations to implement a read-only mode. Additionally, some actions depends on other action's results.

**Comment by mortenholmgaard** [comment]
Yes all actions. But yes I understand that it is not an easy task to implement.

**Comment by KrauseFx** [comment]
I'll close this issue for now, as it's not on my roadmap. Thanks for your feedback though.
