### ISSUE TITLE
Hockey command doesn't support "users" option.

### ISSUE THREAD

**Issue by Nicorhns** [KrauseFx/fastlane#358]
In the latest Hockey API, they now support a "users" parameter. Fastlane doesn't seem to support this.

<code>users - optional, restrict download to comma-separated list of user IDs; example:
users=1224,5678 with 1224 and 5678 being the database IDs of your users</code>

Fastlane throws the following error:
<code>Could not find available option 'users' in the list of available options: api_token, ipa, dsym, notes, notify, status, notes_type, release_type, mandatory, teams, tags, public_identifier, commit_sha, repository_url, build_server_url</code>

**Comment by KrauseFx** [comment]
Thanks, I just implemented this. It will be available with the next update :+1:

**Comment by Nicorhns** [comment]
Awesome, thx!
