### ISSUE TITLE
Multiple apps with same code - setup apple_id and app_identifier dynamically

### ISSUE THREAD

**Issue by mortenholmgaard** [KrauseFx/fastlane#364]
I have tried with this in both fastlane file and Appfile. In the fastlane file I get undefined method apple_id error and in the Appfile it is like the code is never called, even though I have tried to include it in the platform og lane specific configuration.

How to I get my method set_context executed in Appfile or how do I set apple_id and app_identifier in the fastlane file?
I have looked at the SunApps setup which is a bit similar, but I do not get their setup with folders. Is all the files duplicated in each folder? I see that it might be needed to have metadata and screenshots in folders per app, but I guess that path is configurable in those modules, so the I only need the have the module files in one location - right?

Code:
```Ruby
def set_1_apple_account
  apple_id "my@email.com"
end
def set_2_apple_account
  apple_id "my2@email.com"
end

def set_context
  puts "Write the app name:"
  app_name = gets.chomp

  case app_name
  when "MyAppName"
    app_identifier "my.app.id"
    set_1_apple_account
  when "MyAppName2"
    app_identifier "my.app.id2"
    set_2_apple_account
  else
    raise "Context is not setup for this app in fastfile - add the app to the switch statement in method 'set_context'"
  end
end
```

**Comment by KrauseFx** [comment]
The `apple_id` cannot be defined in the Appfile. Instead you only provide the bundle identifier (as you already do) and the `apple_id` will be determined automatically :+1:

**Comment by mortenholmgaard** [comment]
But my problem is that I can't get `set_context`called in the Appfile at all. `puts "Write the app name:"
  app_name = gets.chomp`is never called.
How to call it?
And what about the case of creating a new app - the the apple_id needs to be set!?
Is there another way it is possible to use the `set_context`in Fastfile?

**Comment by KrauseFx** [comment]
`set_context` is never called, you can just add it to your `Appfile`:

```ruby
def set_1_apple_account
  apple_id "my@email.com"
end
def set_2_apple_account
  apple_id "my2@email.com"
end

def set_context
  puts "Write the app name:"
  app_name = gets.chomp

  case app_name
  when "MyAppName"
    app_identifier "my.app.id"
    set_1_apple_account
  when "MyAppName2"
    app_identifier "my.app.id2"
    set_2_apple_account
  else
    raise "Context is not setup for this app in fastfile - add the app to the switch statement in method 'set_context'"
  end
end

set_context
```

**Comment by mortenholmgaard** [comment]
As I stated in the first comment I have tried that, also inside platform and lane configuration scopes. And i have tried exactly what you suggest but the `puts`and `gets.chomp`is never called.
I have also tried a puts as the first line in the file but that is not called either.
How to get this working?

**Comment by mortenholmgaard** [comment]
I have ended handling it in the Fastfile and creating my own Environment variables to set data in.

Do you have any way to get the version number from the Xcode target? 

If any one are interested here is my code:
```
def set_context
    apps = JSON.parse(open("http://url").read)
    i = 1
    puts "Select app:"
    apps.each do |app|
      title = app["Title"]
      puts "#{i}) #{title}"
      i += 1 
    end 
    app_index = gets.chomp
    app = apps.at(app_index.to_i()-1)

    ENV["APP_IDENTIFIER"] = app["AppPublishId"]
    ENV["TARGET"] = app["XcodeTarget"]
    ENV["APPLE_ID"] = app["AppleId"]
    ENV["APP_VERSION_NUMBER"] = "1.0.0" #TODO get from xcode

    title = app["Title"]
    say "Acount context for #{title} set with success"
  end
```

**Comment by KrauseFx** [comment]
Do you mean something like [this](https://github.com/fastlane/examples/blob/master/Wikipedia/Fastfile#L48)?

**Comment by mortenholmgaard** [comment]
Yes exactly - thanks

When I have this:
SNAPSHOT_BREAK_ON_FIRST_ERROR=1 snapshot --noclean
I get this error:
`eval': (eval):26: syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)

It should be supported..

**Comment by KrauseFx** [comment]
You cannot just add terminal commands in your `Fastfile`. Instead you can call them by using `sh "command here"` or by using Ruby code to execute other tools. For example: 

````ruby
snapshot(noclean: true)
```

**Comment by mortenholmgaard** [comment]
Okay - thanks
