### ISSUE TITLE
"No IPA file given" but IPA exists

### ISSUE THREAD

**Issue by chdi** [KrauseFx/fastlane#368]
I would like to build an IPA und deliver it to ITC. 
The IPA is created without errors, Hockey-Upload and snaphot is also running fine. 
In the last step I want to upload the binary but only the metadata is being updated. 

My Fastfile:
```ruby
fastlane_version "1.5.0"
default_platform :ios

#The scheme name in Xcode
appName = ENV["BAF_FASTLANE_APP_NAME"]

#The configuration in Xcode (Release, Debug or Hockey)
appConfiguration = ENV["BAF_FASTLANE_CONFIGURATION"]

platform :ios do

  before_all do
    cocoapods
    ipa(scheme: "#{appName}", configuration: "#{appConfiguration}")
  end

  desc "Runs all the tests"
  lane :snapshot do
    snapshot
  end


  desc "Uploads an App to Hockey"
  lane  :hockey do 
      hockey({
        api_token: 'XXX',
        notes: "Automatic Upload via fastlane "  
      })
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :appstore do
    #snapshot
    #sigh
    deliver(skip_deploy: true, force: true) 
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

end
```

My Deliverfile:
```ruby
appName = ENV["BAF_FASTLANE_APP_NAME"]
appConfiguration = ENV["BAF_FASTLANE_CONFIGURATION"]

screenshots_path "./screenshots/#{appName}/#{appConfiguration}"

apple_id "XXX"
```

I get the Answer "Successfully uploaded package to iTunesConnect..." but there is the warning "No IPA file given. Only the metadata was uploaded."

How could I upload this IPA?

**Comment by KrauseFx** [comment]
That's interesting, so you get the `ipa` file in the current directory when running `fastlane` but you still get the warning? Could you try adding the following to your `Deliverfile`:

```ruby
ipa "./[your_ipa].ipa"
```
To be sure, you can temporary use an absolute path just to try this.

Usually this should all be handled by `fastlane` automatically, sorry for the troubles.

**Comment by chdi** [comment]
This command don`t works:
```ruby
ipa "./[your_ipa].ipa"
```
But this works:
```ruby
ipa "../[your_ipa].ipa"
```

Yes, the ipa is located at the root of the project. Is it correct?
After this test I printed the Environment Variables IPA_OUTPUT_PATH and DSYM_OUTPUT_PATH and both a correct. Finally I tried to deliver the ipa with the following configuration:

```ruby
ipa ENV["IPA_OUTPUT_PATH"]
```

.. and it works! In my last try I removed the last added line and it magically submitted the app. I don´t know why. Any Ideas?

**Comment by KrauseFx** [comment]
By default, `fastlane` will use this for you:
```ruby
ipa ENV["IPA_OUTPUT_PATH"]
```
that's why you can just remove this line and it should still work :+1:

**Comment by KrauseFx** [comment]
So this issue is resolved now, right?

**Comment by chdi** [comment]
Yep. Thanks ;)

**Comment by KrauseFx** [comment]
:+1:
