### ISSUE TITLE
Missing parameters for snapshot action in fastlane

### ISSUE THREAD

**Issue by carlosefonseca** [KrauseFx/fastlane#37]
Hi!

I can't seem to find a way to tell `snapshot` which `Snapfile` to use inside a lane, like `$ snapshot --snapfile Snapfile1`…
After looking at the action code, I think there is no way to do it. I'm tempted to try the `sh` action to do it.
Using a environment var would work too.

EDIT: sh works :grinning:

**Comment by KrauseFx** [comment]
Yah, I'm not yet 100% happy with the differences between the CLI of the individual tools and the fastlane integration.

Might need something like:
```
snapshot({
  snapfile: "SpecialSnapfile",
  option: 123
})
```

**Comment by joshdholtz** [comment]
@carlosefonseca Just checking in to see if this issue is resolved for you. Felt like doing some issue house cleaning tonight :innocent:

**Comment by KrauseFx** [comment]
I don't think this is resolved, since the `snapshot` actions in `fastlane` still doesn't allow passing of parameters, right? 

But yah, this really is related to https://github.com/KrauseFx/fastlane/issues/45

**Comment by carlosefonseca** [comment]
If you want you can close this and keep everything on #45.

**Comment by KrauseFx** [comment]
Probably makes sense, thanks :+1:
