### ISSUE TITLE
update_fastlane and check_version_conflict

### ISSUE THREAD

**Issue by zakhej** [KrauseFx/fastlane#379]
Hi,

I'm running fastlane ios release with update_fastlane option then getting this stack trace:
(EDIT: even without update_fastlane option I still getting this error)
```
fastlane ios release
-----------------------------
--- Step: update_fastlane ---
-----------------------------
Updating produce from 0.3.4 to 0.3.5 ... 🚀
Finished updating produce
fastlane.tools succesfully updated! I will now restart myself... 😴
/Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.6.1, already activated mime-types-1.25.1 (Gem::LoadError)
from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:216:in `block in finish_resolve'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:215:in `each'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:215:in `finish_resolve'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:129:in `block in load_default_actions'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `each'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `load_default_actions'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane.rb:18:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/bin/fastlane:5:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `load'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `<main>'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

I do not know what is mime-types and why I got two versions on my system, but after uninstalling mime-types-2.6.1 fastlane command goes well.
Does anyone know how to fix this and explain such situation?

**Comment by scibidoo** [comment]
I'm encountering similar issues.. I have tried to uninstall and i'm getting nowhere.

MobileGoo:~ jamiesciban$ fastlane --v
/Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.6.1, already activated mime-types-1.25.1 (Gem::LoadError)
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:216:in `block in finish_resolve'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:215:in `each'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:215:in `finish_resolve'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:129:in `block in load_default_actions'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `each'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `load_default_actions'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane.rb:18:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/bin/fastlane:5:in `<top (required)>'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
MobileGoo:~ jamiesciban$ sudo gem uninstall fastlane
Password:
MobileGoo:~ jamiesciban$ fastlane --v
/Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.6.1, already activated mime-types-1.25.1 (Gem::LoadError)
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:216:in `block in finish_resolve'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:215:in `each'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:215:in `finish_resolve'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:129:in `block in load_default_actions'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `each'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `load_default_actions'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/lib/fastlane.rb:18:in `<top (required)>'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jamiesciban/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/gems/fastlane-1.6.0/bin/fastlane:5:in `<top (required)>'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jamiesciban/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by KrauseFx** [comment]
Can you try running `sudo gem cleanup`?

**Comment by MarkMolina** [comment]
The cleanup doesn't seem to work for me. 

```
Cleaning up installed gems...
Clean Up Complete
```

Still same error.

**Comment by KrauseFx** [comment]
Maybe @milch can help? :smiley:

**Comment by milch** [comment]
Hmm, interesting. I've now also encountered this error when running on a CI, even without `update_fastlane`. I'll look into it.

**Comment by milch** [comment]
It seems to work if we put an explicit dependency on `mime-types` 1.25 in the gem specification. I sent a pull request over at #392. 

As far as I can tell, this is a bug in the `rubygems` dependency resolver. The crash occurs when we try to load the `rubygems` package, which is when `rubygems` tries to resolve all unmet dependencies. For some reason, it thinks that `mime-types` isn't loaded yet and then crashes with that error message, because `mime-types` IS loaded with a different version (that already satisfies the requirements).

**Comment by MarkMolina** [comment]
I got it working by deleting everything and reinstalling. However after 1-2 days it start giving that error again without us touching the config.
