### ISSUE TITLE
S3 uploading plist and html to different AWS regions

### ISSUE THREAD

**Issue by alexspark** [KrauseFx/fastlane#388]
Specifying a region for the **s3** action does not get reflected when uploading of the generated plist and html. It always attempts to upload to US-East-1. I hope it's not crazy to expect the plist and html to be uploaded to the same region the bucket specified resides.

Briefly digging through, I believe the culprit is in
**lib/fastlane/actions/s3.rb** Line 184, where the S3 client is created without a region specified.

```ruby
require 'aws-sdk'
s3_client = AWS::S3.new(
  access_key_id: s3_access_key,
  secret_access_key: s3_secret_access_key
)
```

We can specify the region in the S3 client like so:

```ruby
AWS.config(
  region: 'us-west-2'
)
```

**Comment by KrauseFx** [comment]
Would you mind preparing and testing a pull request? If not, I can take over this issue.

**Comment by alexspark** [comment]
will do.

**Comment by alexspark** [comment]
Oddly, After I forked and pointed my project to use Master, I can no longer reproduce this issue. Using fastlane 1.7.

**Comment by KrauseFx** [comment]
So this issue is resolved in the latest release? :+1:

**Comment by alexspark** [comment]
When it wasn't working, I was definitely on 1.6.0, but after the upgrade to 1.7.0, both version use the correct region.
