### ISSUE TITLE
Just upload the binary with Deliver

### ISSUE THREAD

**Issue by chdi** [KrauseFx/fastlane#391]
I would like to upload only the IPA with Deliver. I am using the following command in my Fastfile:

```ruby
deliver(skip_deploy: true, force: true)
```

And my Deliverfile contains following statements: 

```ruby
ENV["DELIVER_USER"] = "XXXX"
ENV["DELIVER_PASSWORD"] = "XXXX"

version ENV["BAF_CURRENT_APP_VERSION"]
app_identifier ENV["BAF_BUNDLE_IDENTIFIER"]
```

The binary is being uploaded successfuly. But I don´t want change the existing Metadata. Is it maybe possible to set Environment-Variables to suppress this behavior?

fyi: I have got a folder with existing Metadata of an other scheme in the fastlane/Metadata/de-DE folder.

**Comment by KrauseFx** [comment]
There is, but it's probably not really well documented. Use the following call:

```ruby
deliver(skip_deploy: true, force: true, beta: true)
```

**Comment by mRs-** [comment]
I just implemented this, because @chdi is busy right now. It's working now, maybe a documentation about this would be really cool.

@KrauseFx you can close this issue :beers:

**Comment by chdi** [comment]
Thanks @KrauseFx  and @mRs-

**Comment by KrauseFx** [comment]
Thanks :+1:

**Comment by KrauseFx** [comment]
Updated the documentation :+1:

**Comment by toshi0383** [comment]
How do you do this in command-line directly ?
Here is what I tried and failed with invalid Phone Number error.

```
$ deliver --ipa App.ipa -u ${itc_user} --skip_screenshots --skip_metadata -f
~
~
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:163:in `handle_itc_response': The phone number must be in a valid format. Preface the phone number with ‘+’ followed by the country code (for example, +44 844 209 0611) There are one or more errors on the page. (Spaceship::TunesClient::ITunesConnectError)
```

deliver 1.5.1

**Comment by toshi0383** [comment]
Hi, any update on this ?

**Comment by mRs-** [comment]
That's a meta data exception in iTunes Connect. Just go there and add a country code with a + on your phone numbers.

**Comment by toshi0383** [comment]
I'd like to **just upload the binary** without any checking. Is that possible in command-line ?

**Comment by mRs-** [comment]
No because apples backend is here limiting your upload. You have to do it one time manual. 

Von meinem iPhone gesendet
