### ISSUE TITLE
PlistBuddy set method

### ISSUE THREAD

**Issue by rolandleth** [KrauseFx/fastlane#393]
The increment version/build methods were really nice additions, but some people (like me, of course :)) use a script to increment these values in the plist, so the `agvtool` isn't really helpful. 

```sh
buildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFOPLIST_FILE")
buildNumber=$(($buildNumber + 1))
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "$INFOPLIST_FILE"
```

Adding a set method to the `PlistBuddy` module would be really nice for us.

```ruby
def set(file, key, value)
  output = `/usr/libexec/PlistBuddy -c "Set #{key} #{value}" "#{file}" 2>&1`
  output == "" ? value : nil
end
```

So we can do stuff like:

```ruby
version = Shenzhen::PlistBuddy.print(plist, 'CFBundleShortVersionString')
[...]
Shenzhen::PlistBuddy.set(plist, 'CFBundleShortVersionString', newVersion)
```

Credit goes to [Nassim's gist](https://gist.github.com/nkammah/7d1de3e132d7061352a7).

**Comment by KrauseFx** [comment]
@rolandleth Cool, feel free to submit a pull request if you have some time :+1:

**Comment by rolandleth** [comment]
@KrauseFx Hmm, that would be my pleasure, but it should be added to the `krausefx-shenzhen` gem, and I don't know where to do that. Open a PR [here](https://github.com/fastlane/shenzhen)?

**Comment by KrauseFx** [comment]
Yes, the link is correct. Right now, only through environment variables.

**Comment by rolandleth** [comment]
Opened a PR! As for the params, I was thinking about passing arguments from the command line, for example `fastlane release --minor`

**Comment by KrauseFx** [comment]
Thanks again for your contribution @rolandleth :+1:
