### ISSUE TITLE
Change facebook id dynamically

### ISSUE THREAD

**Issue by diogomaximo** [KrauseFx/fastlane#404]
Hi, congratulation for this awesome project.
On my app the user can login with facebook account.
I have two facebook apps(development and production).
I need to change my FacebookAppID(defined in my info.plist file) depending of my lane.
Do you know can i do that?
I want to do the same thing i do with app_identifer(CFBundleIdentifier).
I have the following lanes and i would like to to something like this.
```ruby
if ENV["FASTLANE_LANE_NAME"] == :stage.to_s then
    app_identifier "app_id_enterprise"
    plistInstance['FacebookAppID'] = 'FACEBOOK_ID_DEV'
end

if ENV["FASTLANE_LANE_NAME"] == :production.to_s then
    app_identifier "app_id_app_store"
  plistInstance['FacebookAppID'] = 'FACEBOOK_ID_PRODUCTION'
end
```
Thank You in Advance.

**Comment by KrauseFx** [comment]
Thanks @diogomaximo.

There are multiple ways to do that. Always keep in mind, the `Fastfile` is just a Ruby file allowing you to do *anything*, including updating a `plist` file.

Inside your lane definition just add your custom code:

```
lane :stage do
  ...
  plistInstance['FacebookAppID'] = 'FACEBOOK_ID_DEV'
  ...
end
```

You can parse a plist file using:
```
require 'plist'

plist = Plist::parse_xml(path)
```

**Comment by diogomaximo** [comment]
Thanks @KrauseFx.
Done!

**Comment by KrauseFx** [comment]
:+1:
