### ISSUE TITLE
Multiple Appfiles

### ISSUE THREAD

**Issue by ophirharpaz** [KrauseFx/fastlane#407]
Hi,
Since I'm dealing with creating and submitting many apps a day, I was wondering what would be the best working method:
Editing the Appfile every time I'm working on a new app, or perhaps copying this file (one per app) and editing it separately.

Is the second option even possible? I mean, can I have multiple Appfiles - one per each app? And if so, how do I direct fastlane to work with a specific one?

Many thanks.

**Comment by KrauseFx** [comment]
You can change your `Appfile` to look like this:
```ruby
app_identifier ENV["APP_IDENTIFIER"]
```
and then call `fastlane` like this: 
```
APP_IDENTIFIER="com.krausefx.app" fastlane ios beta
```

All configuration files are standard Ruby files, so it's easy to customise them.

**Comment by KrauseFx** [comment]
I'll close this issue for now. Let me know if there is anything else I can help you with :+1:
