### ISSUE TITLE
How to manage dynamic NSString variable?

### ISSUE THREAD

**Issue by ersentekin** [KrauseFx/fastlane#408]
Hey all faslaners,
How to manage dynamic NSString variable for different types of deliveries like Development, Stage & Production environments?

Is there any kind of lane action to use?

Thanks so much!

**Comment by KrauseFx** [comment]
You can pass preprocessor macros when building, not sure how the majority of `fastlane` users solve this issue.

**Comment by milch** [comment]
You can pass additional arguments to be used as preprocessor macro when building your ipa like this: 

```ruby
server_url = '@\"http://beta.example.org\"'
ipa (
# ...
xcargs: "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) X_SERVER_URL=#{url}'"
)
```
(it's important to have that `$(inherited)` in there so flags that are set by Xcode are set correctly)

And then in your code:

```objective-c
#ifdef X_SERVER_URL
    kServerBaseUrl = [NSURL URLWithString:X_SERVER_URL];
#else
    // Handle the case where no server URL is passed in from the build, e.g. on a developer machine
    // ... 
#endif
```

Of course, you can put as many preprocessor macros as you want in that file.

**Comment by ersentekin** [comment]
@KrauseFx & @milch 
Thanks so much, macros probably the best choice 👍

**Comment by KrauseFx** [comment]
Thanks again @milch for providing the solution :+1:

**Comment by mortenholmgaard** [comment]
Use this in swift:
´OTHER_SWIFT_FLAGS='$(inherited) -DVARNAME=1'´

**Comment by ersentekin** [comment]
@mortenholmgaard thanks for Swift support ! 🐤
