### ISSUE TITLE
Hockey upload fails to find dSYM.zip file if there is a space in the filename

### ISSUE THREAD

**Issue by egold** [KrauseFx/fastlane#41]
I have a generated dSYM zip file called 

    ./MyAppName Beta.app.dSYM.zip

(note the space in the name)

However, during Hockey upload I get this error:

    Symbols not found on path /Users/eric/my-apps-directory/MyAppNameBeta.app.dSYM.zip. Crashes won't be symbolicated properly

(note the lack of a space in the error's description of the filename)

The .dSYM.zip gets generated just fine. I checked the datestamp, unzipped the archive, etc. It just has a space in the name, so the Hockey upload of the dSYM fails.

**Comment by champo** [comment]
This is wierd, I've just configured hockey to use an app with a space in the name and it doesn't complain. Can you post your Fastile?

**Comment by KrauseFx** [comment]
`fastlane` uses [shenzhen](https://github.com/nomad/shenzhen) under the hood to upload builds to `hockey`.

**Comment by egold** [comment]
```
# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  # sh "./customShellScript.sh"

  increment_build_number

  cocoapods

  # xctool
end

lane :test do
  # snapshot
end

lane :beta do
  # snapshot
  sigh
  # deliver :skip_deploy, :beta
  # sh "your_script.sh"
  sh "cd ../;ipa build --scheme \"My Scheme\" --configuration \"AdHoc\" --ipa \"MyIPA.ipa\" "
  hockey({
    api_token: 'XXXXXXXXX',
    ipa: './MyIPA.ipa',
    notes: 'Automatically generated build'
  })
end

lane :deploy do
  # snapshot
  sigh
  # deliver :skip_deploy, :force
  # frameit
end

lane :inhouse do
  # insert your code here
end

# You can define as many lanes as you want

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
```

**Comment by egold** [comment]
Ah okay, so this is a shenzen issue. I'll post there. Thanks

**Comment by egold** [comment]
Actually re-opening, I think it's a fastlane issue in hockey.rb:

```
        if options[:dsym]
          options[:dsym_filename] = options[:dsym]
        else  
          dsym_path = options[:ipa].gsub("ipa", "app.dSYM.zip")
          if File.exists?(dsym_path)
            options[:dsym_filename] = dsym_path
          else
            Helper.log.info "Symbols not found on path #{File.expand_path(dsym_path)}. Crashes won't be symbolicated properly".yellow
          end
        end

```

**Comment by KrauseFx** [comment]
Okay, please just pass the path to your `dsym` to hockey.

```ruby
hockeyapp({dsym: "path"})
```

Also, check out the README, there is now an `ipa` action, which uses `shenzhen` to build your app, without having to use `sh 'ipa build'`

**Comment by egold** [comment]
OK great, thanks @KrauseFx. I'll check into that

**Comment by joshdholtz** [comment]
@egold Is this issue resolved for you? If not, I can look into it further :grin:

**Comment by KrauseFx** [comment]
Feel free to re-open the issue if you're still experiencing this issue :+1:

**Comment by egold** [comment]
Yeah things are fine now that I specify the `dsym` param like you suggested above. Thanks! :+1:
