### ISSUE TITLE
Different accounts for sigh and ipa

### ISSUE THREAD

**Issue by chdi** [KrauseFx/fastlane#410]
I would like to use a different account for the actions "sigh" and "ipa".
I´ve got the lane "appstore":

```ruby
  lane :appstore do

    cocoapods

    #snapshot
    sigh 
    
    ipa(scheme: "#{appName}", configuration: "#{appConfiguration}") 

    #Upload it but no review
    deliver(skip_deploy: true, force: true, beta: true)
   # frameit

    hockey({
        notes: "Neue Store-Version vorhanden. Bitte updaten Sie Ihre App regelmäßig.",
        release_type: "1"
    })

    hipchat( message: "Neue Version im App Store hochgeladen und bei Hockey veröffentlicht: #{appName} (Version: #{currentAppVersion})" )
  end
```

I call this lane with the following command:

SIGH_TEAM_ID="XXX" SIGH_APP_IDENTIFIER="XXX" SIGH_USERNAME="MAIL1"  DELIVER_USER="MAIL2" fastlane appstore

The problem is that the action "sigh" is using the Variable "DELIVER_USER" (MAIL2) instead of "SIGH_USERNAME" (MAIL2). When I remove the "DELIVER_USER" the sigh-command works fine (and uses SIGH_USERNAME), but the delivering to the app store fails (wrong Account). 

Any ideas to solve this problem?

**Comment by KrauseFx** [comment]
You can pass custom values to the actions, like this:

```ruby
sigh(username: 'felix@sunapps.net')
```
Does that solve the problem?

**Comment by chdi** [comment]
Yes, this fixed it. Everything works fine now :+1: 
Thank @KrauseFx

**Comment by KrauseFx** [comment]
Great to hear :+1:
