### ISSUE TITLE
Double output for 'Cruising back to lane x`

### ISSUE THREAD

**Issue by rolandleth** [KrauseFx/fastlane#416]
The `Cruising back to lane [original_lane]` message is shown twice. Here is a simple Fastfile:

```
# opt_out_usage
update_fastlane
default_platform :ios

platform :ios do
  lane :lane1 do |options|
    puts 'On lane 1'

    lane2 from: :lane1
  end

  lane :lane2 do |options|
    puts "On lane 2, from #{options[:from]}"

    lane3 from: :lane2
  end

  lane :lane3 do |options|
    puts "On lane 3, from #{options[:from]}"
  end
end
```

And the output for `fastlane lane` is this:
<img width="434" alt="screen shot 2015-07-16 08 36 16 0000" src="https://cloud.githubusercontent.com/assets/1858700/8718744/5109c906-2baf-11e5-8e44-14e6a76e8e38.png">

**Comment by KrauseFx** [comment]
This is fixed with the recent refactoring. Thanks again! :+1:

**Comment by rolandleth** [comment]
yay :)
