### ISSUE TITLE
Wrong new lines on ipa action

### ISSUE THREAD

**Issue by carlosefonseca** [KrauseFx/fastlane#42]
Hi!

I'm doing `sh "ipa…"` on fastlane and I'm getting weird wrapping on the logs… not sure what could be happening…

![](https://dl.dropboxusercontent.com/s/0ifct141e1alq2t/Screen%20Shot%202015-02-13%20at%2009.46.19.png?dl=0)

I am using joshdholtz's pull request but I have my doubts that he touched on print code… also I am aware that you've added an `ipa` command to `Fastfile` but the pull request hasn't been updated… anyway, something seems weird with `sh` and I thought you might have some ideas…
Thanks

**Comment by KrauseFx** [comment]
Thanks, I saw the same problem, but haven't had the time to look into it (it still works, it just looks odd)
