### ISSUE TITLE
Could not find action or lane 'produce'

### ISSUE THREAD

**Issue by gfpacheco** [KrauseFx/fastlane#421]
Weird error after starting the produce action (I guess it's after since it start logging then throws the error):

    [15:57:08]: --- Step: produce ---
    [15:57:08]: ---------------------
    [15:57:13]: App 'XXX' already exists, nothing to do on the Dev Center
    [15:57:16]: Logging into iTunesConnect
    [15:57:31]: Successfully logged into iTunesConnect
    [15:57:42]: Variable Dump:
    [15:57:42]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios publish"}
    [15:57:42]: Could not find action or lane 'produce'. Check out the README for more details: https://github.com/KrauseFx/fastlane
    [15:57:42]: fastlane finished with errors
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:109:in `try_switch_to_lane': Could not find action or lane 'produce'. Check out the README for more details: https://github.com/KrauseFx/fastlane (RuntimeError)
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/fast_file.rb:92:in `rescue in method_missing'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/fast_file.rb:81:in `method_missing'
    	from (eval):11:in `create_app'
    	from (eval):52:in `block (3 levels) in parse'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane.rb:25:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane.rb:25:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:48:in `block in execute'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:38:in `chdir'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:38:in `execute'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:35:in `block (2 levels) in run'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:124:in `run'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:130:in `<top (required)>'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `load'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `<main>'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by KrauseFx** [comment]
Sorry about that @gfpacheco. Could you download the latest code from GitHub and execute `sudo bundle install && sudo rake install`, run it again and post the log output?

**Comment by gfpacheco** [comment]
I feel sorry for just report the issues without trying to solve them first. I'm gonna try the latest code and come back with the results.

**Comment by KrauseFx** [comment]
No, this was my problem for sure, someone on Twitter mentioned it as well. I added more debug information in the last commit and would be thankful if you could try it :+1:

**Comment by gfpacheco** [comment]
New log:

    [16:36:45]: ---------------------
    [16:36:45]: --- Step: produce ---
    [16:36:45]: ---------------------
    [16:36:49]: App 'XXX' already exists, nothing to do on the Dev Center
    [16:36:52]: Logging into iTunesConnect
    [16:37:04]: Successfully logged into iTunesConnect
    [16:37:16]: App 'XXX' exists already, nothing to do on iTunes Connect
    [16:37:28]: /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/fast_file.rb:92:in `rescue in method_missing'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/fast_file.rb:81:in `method_missing'
    (eval):11:in `create_app'
    (eval):52:in `block (3 levels) in parse'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane.rb:25:in `call'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane.rb:25:in `call'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:48:in `block in execute'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:38:in `chdir'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:38:in `execute'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:35:in `block (2 levels) in run'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:124:in `run'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:130:in `<top (required)>'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `load'
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `<main>'
    [16:37:28]: Variable Dump:
    [16:37:28]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios publish"}
    [16:37:28]: Could not find action or lane 'produce'. Check out the README for more details: https://github.com/KrauseFx/fastlane
    [16:37:28]: fastlane finished with errors
    /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane': Could not find action or lane 'produce'. Check out the README for more details: https://github.com/KrauseFx/fastlane (RuntimeError)
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/fast_file.rb:92:in `rescue in method_missing'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/fast_file.rb:81:in `method_missing'
    	from (eval):11:in `create_app'
    	from (eval):52:in `block (3 levels) in parse'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane.rb:25:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane.rb:25:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:48:in `block in execute'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:38:in `chdir'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/runner.rb:38:in `execute'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:35:in `block (2 levels) in run'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:124:in `run'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/gems/fastlane-1.9.0/bin/fastlane:130:in `<top (required)>'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `load'
    	from /Users/gfpacheco/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `<main>'

**Comment by gfpacheco** [comment]
I'm using RVM so I didn't need the `sudo`, but is there a way I can be sure I'm running the correct (latest) version?

**Comment by KrauseFx** [comment]
That's odd. Can you share the part of your `Fastfile` using `produce`?

**Comment by KrauseFx** [comment]
In particular row 11 and 52 (if I saw that correctly)

**Comment by gfpacheco** [comment]
It's inside a function that receive the parameters, nothing special:

    produce(
      produce_username: username,
      produce_app_identifier: identifier,
      produce_app_name: name,
      produce_language: language,
      produce_version: version,
      produce_sku: identifier,
      produce_company_name: ''
    )

**Comment by KrauseFx** [comment]
Is that line 52? If so, what's on line 11?

**Comment by gfpacheco** [comment]
@KrauseFx trying again worked fine with the version you told me to use, sorry about that

**Comment by KrauseFx** [comment]
Uh, that's odd, sorry about that. I wonder why that happened...

**Comment by KrauseFx** [comment]
Found the issue, pushing a fix in a few minutes :+1:
