### ISSUE TITLE
lane_context[...] shorthand syntax adds unneeded step output

### ISSUE THREAD

**Issue by jeanregisser** [KrauseFx/fastlane#425]
Not a big deal, but there's another bug introduced by the shorthand `lane_context` syntax.
Now whenever I use it, it outputs:

```nohighlight
--------------------------
--- Step: lane_context ---
--------------------------
```

**Comment by KrauseFx** [comment]
Ohhh, nice catch, thanks!

**Comment by KrauseFx** [comment]
Thanks again, this is fixed now, I'll ship a new version today :+1:

**Comment by jeanregisser** [comment]
Nice! Continue your awesome work!

**Comment by KrauseFx** [comment]
Thanks @jeanregisser, it's live now :+1: fastlane] https://github.com/KrauseFx/fastlane/releases/tag/1.10.0
