### ISSUE TITLE
Ipa build on 10.11 (El Capitan beta)

### ISSUE THREAD

**Issue by alextud** [KrauseFx/fastlane#426]
After installing fastlane on El Capitan, the krausefx-ipa scrip isn't available from command line. 

Is anyone having the same issue as me ?

**Comment by KrauseFx** [comment]
Have you tried installing it using `sudo gem install fastlane` and/or `sudo gem install krausefx-ipa`

**Comment by alextud** [comment]
sudo gem install krausefx-ipa
Password:
ERROR:  Could not find a valid gem 'krausefx-ipa' (>= 0) in any repository

**Comment by alextud** [comment]
I did update fastlane version to 1.9.0

**Comment by KrauseFx** [comment]
Sorry, I meant `sudo gem install krausefx-shenzhen`. Also, try running it without `sudo`

**Comment by alextud** [comment]
Thanks @KrauseFx is working for me.
