### ISSUE TITLE
Connection reset by peer - recvfrom(2)

### ISSUE THREAD

**Issue by Allansk2** [KrauseFx/fastlane#434]
I am using fastlane 1.11.0. I got an error "Connection reset by peer - recvfrom(2)" when deliver is executed. Below attached my fastfile and Deliverfile. And then if I change the Deliverfile apple_id ENV['PRODUCE_APPLE_ID'] to apple_id "<apple_id>", and execute deliver again. I got another error 
`update_price_tier': No initial pricing found, please set the pricing at least once on iTunes Connect. I'm publishing a new app, do I still have to put update_price_tier 0?

My Fastfile is like this:
lane :appstore do
  produce({
    username: 'xxxxxxx',
    app_identifier: 'xxxxxxx',
    app_name: 'xxxxxxx',
    language: 'English',
    version: '0.0.1',
    sku: 156,
    team_name: 'xxxxxxx'  
  })

  cert
  pem(generate_p12: true, save_private_key: true)
  sigh
  snapshot
  deliver  
end

Deliverfile file like this:
apple_id ENV['PRODUCE_APPLE_ID']
version "0.0.1" 
screenshots_path "./screenshots"
app_icon "./icon_1024.png"

title({
  "en-US" => "xxxxxxx"
})

keywords(
  "en-US" => ["xx", "xx","xx"]
)

support_url(
  "en-US" => "xxx"
)
 
description({
  "en-US" => "xxxxx."
})

copyright "xxx"
automatic_release true
skip_pdf(
  "en-US" => true
)
app_review_information({
  first_name: "xx",
  last_name: "xx",
  phone_number: "xx",
  email_address: "xx",
  demo_user: "Demo Account",
  demo_password: "",
  notes: "xx."
})

primary_category "Business"
secondary_category "Productivity"
ratings_config_path "./ratings.json"
price_tier 0

error message 1
[08:13:45]: --- Step: deliver ---
[08:13:45]: Got all information needed to deploy a new update ('0.0.1') for app 'xxxxx'
[08:13:45]: Connection reset by peer - recvfrom(2)
[08:13:45]: fastlane finished with errors
 
error message 2
`update_price_tier': No initial pricing found, please set the pricing at least once on iTunes Connect. (RuntimeError)

Does any one have any idea?
Thanks,

**Comment by KrauseFx** [comment]
The pricing error message just tells you, that you need to set the initial pricing manually on iTunes Connect. Moving further discussion to https://github.com/KrauseFx/deliver/issues/277
