### ISSUE TITLE
fastlane not changing bundle id

### ISSUE THREAD

**Issue by buscarini** [KrauseFx/fastlane#437]
I have a beta lane with this info:

    cert

    pem(generate_p12: true)

    sigh(output_path: "./fastlane/profiles",
          force: true) # Distribution Profile
    
    
    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = Actions.lane_context[Actions::SharedValues::SIGH_UDID]
    
    ipa({
      scheme: "MyScheme"
    })

The problem is is fails building because it's not changing the bundle identifier, and so it complains that the prov. profile has a different app id than the bundle identifier. I am using Appfile and it has a app_identifier set. Should this just work, or is there any way to force ipa to change the project bundle identifier?

**Comment by KrauseFx** [comment]
What do you mean `it's not changing the bundle identifier`? Where should it change the bundle identifier and why?

**Comment by buscarini** [comment]
Nevermind, I thought that it would change the bundle identifier to match the app_identifier, and then I could just change the app_identifier and it would work. I have made a script to do that, so now I don't need it.
