### ISSUE TITLE
CopySwiftLibs error when running fastlane over non-interactive ssh session

### ISSUE THREAD

**Issue by philippevannuys** [KrauseFx/fastlane#438]
When running fastlane over non-interactive ssh session, it fails with a CopySwiftLibs error. It works fine when running the same command locally with a regular ssh session.

ssh user@ip_address 'fastlane sandbox'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | increment_build_number              | 0           |
| 5    | xcarchive                           | 104         |
+------+-------------------------------------+-------------+

[10:08:51]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/actions_helper.rb:113:in `sh_no_action': Exit status of command 'set -o pipefail && xcodebuild -archivePath "Stormy Temple.xcarchive" -configuration "Sandbox" -scheme "Stormy Temple" -workspace "StormyTemple.xcworkspace" CODE_SIGN_IDENTITY="iPhone Distribution: Company Inc" JOBS="16" archive clean | xcpretty --no-utf --simple' was 16640 instead of 0.  (RuntimeError)
> Building Pods/Pods-StormyTemple-CXAlertView [Sandbox]
> Compiling CXAlertButtonContainerView.m
> Compiling CXAlertButtonItem.m
> Compiling CXAlertView.m
> Compiling CXAlertViewController.m
> Compiling CXBlurView.m
> Compiling Pods-StormyTemple-CXAlertView-dummy.m
> Compiling CXAlertButtonContainerView.m
> Compiling CXAlertButtonItem.m
> Compiling CXAlertView.m
> Compiling CXAlertViewController.m
> Compiling CXBlurView.m
> Compiling Pods-StormyTemple-CXAlertView-dummy.m
> Building library libPods-StormyTemple-CXAlertView.a
> Building library libPods-StormyTemple-CXAlertView.a
> Building Pods/Pods-StormyTemple-FXBlurView [Sandbox]
> Compiling FXBlurView.m
> Compiling Pods-StormyTemple-FXBlurView-dummy.m
> Compiling FXBlurView.m
> Compiling Pods-StormyTemple-FXBlurView-dummy.m
> Building library libPods-StormyTemple-FXBlurView.a
> Building library libPods-StormyTemple-FXBlurView.a
> Building Pods/Pods-StormyTemple-KAProgressLabel [Sandbox]
> Compiling KAProgressLabel.m
> Compiling Pods-StormyTemple-KAProgressLabel-dummy.m
> Compiling TPPropertyAnimation.m
> Compiling KAProgressLabel.m
> Compiling Pods-StormyTemple-KAProgressLabel-dummy.m
> Compiling TPPropertyAnimation.m
> Building library libPods-StormyTemple-KAProgressLabel.a
> Building library libPods-StormyTemple-KAProgressLabel.a
> Building Pods/Pods-StormyTemple-ReactiveCocoa [Sandbox]
> Compiling NSArray+RACSequenceAdditions.m
> Compiling NSData+RACSupport.m
> Compiling NSDictionary+RACSequenceAdditions.m
> Compiling NSEnumerator+RACSequenceAdditions.m
> Compiling NSFileHandle+RACSupport.m
> Compiling NSIndexSet+RACSequenceAdditions.m
> Compiling NSInvocation+RACTypeParsing.m
> Compiling NSNotificationCenter+RACSupport.m
> Compiling NSObject+RACDeallocating.m
> Compiling NSObject+RACDescription.m
> Compiling NSObject+RACKVOWrapper.m
> Compiling NSObject+RACLifting.m
> Compiling NSObject+RACPropertySubscribing.m
> Compiling NSObject+RACSelectorSignal.m
> Compiling NSOrderedSet+RACSequenceAdditions.m
> Compiling NSSet+RACSequenceAdditions.m
> Compiling NSString+RACKeyPathUtilities.m
> Compiling NSString+RACSequenceAdditions.m
> Compiling NSString+RACSupport.m
> Compiling NSURLConnection+RACSupport.m
> Compiling NSUserDefaults+RACSupport.m
> Compiling Pods-StormyTemple-ReactiveCocoa-dummy.m
> Compiling RACArraySequence.m
> Compiling RACBacktrace.m
> Compiling RACBehaviorSubject.m
> Compiling RACBlockTrampoline.m
> Compiling RACChannel.m
> Compiling RACCommand.m
> Compiling RACCompoundDisposable.m
> Compiling RACDelegateProxy.m
> Compiling RACDisposable.m
> Compiling RACDynamicSequence.m
> Compiling RACDynamicSignal.m
> Compiling RACEXTRuntimeExtensions.m
> Compiling RACEagerSequence.m
> Compiling RACEmptySequence.m
> Compiling RACEmptySignal.m
> Compiling RACErrorSignal.m
> Compiling RACEvent.m
> Compiling RACGroupedSignal.m
> Compiling RACImmediateScheduler.m
> Compiling RACIndexSetSequence.m
> Compiling RACKVOChannel.m
> Compiling RACKVOProxy.m
> Compiling RACKVOTrampoline.m
> Compiling RACMulticastConnection.m
> Compiling RACObjCRuntime.m
> Compiling RACPassthroughSubscriber.m
> Compiling RACQueueScheduler.m
> Compiling RACReplaySubject.m
> Compiling RACReturnSignal.m
> Compiling RACScheduler.m
> Compiling RACScopedDisposable.m
> Compiling RACSequence.m
> Compiling RACSerialDisposable.m
> Compiling RACSignal+Operations.m
> Compiling RACSignal.m
> Compiling RACSignalSequence.m
> Compiling RACStream.m
> Compiling RACStringSequence.m
> Compiling RACSubject.m
> Compiling RACSubscriber.m
> Compiling RACSubscriptingAssignmentTrampoline.m
> Compiling RACSubscriptionScheduler.m
> Compiling RACTargetQueueScheduler.m
> Compiling RACTestScheduler.m
> Compiling RACTuple.m
> Compiling RACTupleSequence.m
> Compiling RACUnarySequence.m
> Compiling RACUnit.m
> Compiling RACValueTransformer.m
> Compiling UIActionSheet+RACSignalSupport.m
> Compiling UIAlertView+RACSignalSupport.m
> Compiling UIBarButtonItem+RACCommandSupport.m
> Compiling UIButton+RACCommandSupport.m
> Compiling UICollectionReusableView+RACSignalSupport.m
> Compiling UIControl+RACSignalSupport.m
> Compiling UIControl+RACSignalSupportPrivate.m
> Compiling UIDatePicker+RACSignalSupport.m
> Compiling UIGestureRecognizer+RACSignalSupport.m
> Compiling UIImagePickerController+RACSignalSupport.m
> Compiling UIRefreshControl+RACCommandSupport.m
> Compiling UISegmentedControl+RACSignalSupport.m
> Compiling UISlider+RACSignalSupport.m
> Compiling UIStepper+RACSignalSupport.m
> Compiling UISwitch+RACSignalSupport.m
> Compiling UITableViewCell+RACSignalSupport.m
> Compiling UITableViewHeaderFooterView+RACSignalSupport.m
> Compiling UITextField+RACSignalSupport.m
> Compiling UITextView+RACSignalSupport.m
> Compiling NSArray+RACSequenceAdditions.m
> Compiling NSData+RACSupport.m
> Compiling NSDictionary+RACSequenceAdditions.m
> Compiling NSEnumerator+RACSequenceAdditions.m
> Compiling NSFileHandle+RACSupport.m
> Compiling NSIndexSet+RACSequenceAdditions.m
> Compiling NSInvocation+RACTypeParsing.m
> Compiling NSNotificationCenter+RACSupport.m
> Compiling NSObject+RACDeallocating.m
> Compiling NSObject+RACDescription.m
> Compiling NSObject+RACKVOWrapper.m
> Compiling NSObject+RACLifting.m
> Compiling NSObject+RACPropertySubscribing.m
> Compiling NSObject+RACSelectorSignal.m
> Compiling NSOrderedSet+RACSequenceAdditions.m
> Compiling NSSet+RACSequenceAdditions.m
> Compiling NSString+RACKeyPathUtilities.m
> Compiling NSString+RACSequenceAdditions.m
> Compiling NSString+RACSupport.m
> Compiling NSURLConnection+RACSupport.m
> Compiling NSUserDefaults+RACSupport.m
> Compiling Pods-StormyTemple-ReactiveCocoa-dummy.m
> Compiling RACArraySequence.m
> Compiling RACBacktrace.m
> Compiling RACBehaviorSubject.m
> Compiling RACBlockTrampoline.m
> Compiling RACChannel.m
> Compiling RACCommand.m
> Compiling RACCompoundDisposable.m
> Compiling RACDelegateProxy.m
> Compiling RACDisposable.m
> Compiling RACDynamicSequence.m
> Compiling RACDynamicSignal.m
> Compiling RACEXTRuntimeExtensions.m
> Compiling RACEagerSequence.m
> Compiling RACEmptySequence.m
> Compiling RACEmptySignal.m
> Compiling RACErrorSignal.m
> Compiling RACEvent.m
> Compiling RACGroupedSignal.m
> Compiling RACImmediateScheduler.m
> Compiling RACIndexSetSequence.m
> Compiling RACKVOChannel.m
> Compiling RACKVOProxy.m
> Compiling RACKVOTrampoline.m
> Compiling RACMulticastConnection.m
> Compiling RACObjCRuntime.m
> Compiling RACPassthroughSubscriber.m
> Compiling RACQueueScheduler.m
> Compiling RACReplaySubject.m
> Compiling RACReturnSignal.m
> Compiling RACScheduler.m
> Compiling RACScopedDisposable.m
> Compiling RACSequence.m
> Compiling RACSerialDisposable.m
> Compiling RACSignal+Operations.m
> Compiling RACSignal.m
> Compiling RACSignalSequence.m
> Compiling RACStream.m
> Compiling RACStringSequence.m
> Compiling RACSubject.m
> Compiling RACSubscriber.m
> Compiling RACSubscriptingAssignmentTrampoline.m
> Compiling RACSubscriptionScheduler.m
> Compiling RACTargetQueueScheduler.m
> Compiling RACTestScheduler.m
> Compiling RACTuple.m
> Compiling RACTupleSequence.m
> Compiling RACUnarySequence.m
> Compiling RACUnit.m
> Compiling RACValueTransformer.m
> Compiling UIActionSheet+RACSignalSupport.m
> Compiling UIAlertView+RACSignalSupport.m
> Compiling UIBarButtonItem+RACCommandSupport.m
> Compiling UIButton+RACCommandSupport.m
> Compiling UICollectionReusableView+RACSignalSupport.m
> Compiling UIControl+RACSignalSupport.m
> Compiling UIControl+RACSignalSupportPrivate.m
> Compiling UIDatePicker+RACSignalSupport.m
> Compiling UIGestureRecognizer+RACSignalSupport.m
> Compiling UIImagePickerController+RACSignalSupport.m
> Compiling UIRefreshControl+RACCommandSupport.m
> Compiling UISegmentedControl+RACSignalSupport.m
> Compiling UISlider+RACSignalSupport.m
> Compiling UIStepper+RACSignalSupport.m
> Compiling UISwitch+RACSignalSupport.m
> Compiling UITableViewCell+RACSignalSupport.m
> Compiling UITableViewHeaderFooterView+RACSignalSupport.m
> Compiling UITextField+RACSignalSupport.m
> Compiling UITextView+RACSignalSupport.m
> Building library libPods-StormyTemple-ReactiveCocoa.a
> Building library libPods-StormyTemple-ReactiveCocoa.a
> Building Pods/Pods-StormyTemple [Sandbox]
> Compiling Pods-StormyTemple-dummy.m
> Compiling Pods-StormyTemple-dummy.m
> Building library libPods-StormyTemple.a
> Building library libPods-StormyTemple.a
> Building StormyTemple/StormyTemple [Sandbox]
> Copying Info.plist
> Running script 'Check Pods Manifest.lock'
> Compiling NSString+STAdditions.m
> Compiling STAccount.m
> Compiling STUtils.m
> Compiling UIImageUtils.m
> Compiling STAccount.m
> Compiling NSString+STAdditions.m
> Compiling STUtils.m
> Compiling UIImageUtils.m
> Linking StormyTemple
> Linking StormyTemple
> Copying Stormy\ Temple/AvenirLTStd-Light.otf
> Copying Stormy\ Temple/AvenirLTStd-Book.otf
> Copying Stormy\ Temple/AvenirLTStd-Heavy.otf
> Compiling ThankYouViewController.xib
> Compiling WrittenFeedbackCardViewController.xib
> Copying Stormy\ Temple/zugi_alert.aiff
> Copying Stormy\ Temple/AvenirLTStd-HeavyOblique.otf
> Copying Stormy\ Temple/GooglePlus.bundle
> Copying Stormy\ Temple/AvenirLTStd-MediumOblique.otf
> Compiling FeedbackHelpfulViewController.xib
> Compiling CategoryFeedbackViewController.xib
> Compiling LaunchScreen.xib
> Copying quotes.plist
> Copying Stormy\ Temple/AvenirLTStd-Roman.otf
> Copying Stormy\ Temple/AvenirLTStd-Medium.otf
> Copying Stormy\ Temple/AvenirLTStd-LightOblique.otf
> Copying Stormy\ Temple/AvenirLTStd-BookOblique.otf
> Copying Stormy\ Temple/AvenirLTStd-BlackOblique.otf
> Copying Stormy\ Temple/AvenirLTStd-Black.otf
> Copying Stormy\ Temple/AvenirLTStd-Oblique.otf
> Processing Info.plist
> Generating 'StormyTemple.app.dSYM'
> Running script 'Copy Pods Resources'
> Running script 'Run Script'
> Touching StormyTemple.app
** ARCHIVE FAILED **

The following build commands failed:
	CopySwiftLibs /Users/deploy/Library/Developer/Xcode/DerivedData/StormyTemple-bldpsoadbnixpjdwezakjgggafjg/Build/Intermediates/ArchiveIntermediates/Stormy\ Temple/InstallationBuildProductsLocation/Applications/StormyTemple.app
(1 failure)
> Cleaning Pods/Pods-StormyTemple-CXAlertView [Sandbox]
> Cleaning Pods/Pods-StormyTemple-FXBlurView [Sandbox]
> Cleaning Pods/Pods-StormyTemple-KAProgressLabel [Sandbox]
> Cleaning Pods/Pods-StormyTemple-ReactiveCocoa [Sandbox]
> Cleaning Pods/Pods-StormyTemple [Sandbox]
> Cleaning StormyTemple/StormyTemple [Sandbox]
** CLEAN FAILED **

	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/actions_helper.rb:87:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/xcodebuild.rb:201:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/xcodebuild.rb:269:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/fast_file.rb:120:in `method_missing'
	from (eval):31:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.12.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by gfpacheco** [comment]
Same here, I'm facing this issue running fastlane through Jenkins

**Comment by philippevannuys** [comment]
Found the solution to this. 

1. Make sure your keys are in the System keychain and not the login keychain or any other keychain.

2. Next, right click on the key that needs to be accessible with your build, select "Get Info"  -> Access Control. And Select "Allow All Applications to access this item"

![screen shot 2015-07-27 at 9 04 55 am](https://cloud.githubusercontent.com/assets/12972116/8911085/226236b8-343f-11e5-8ddd-bb164645a201.png)

**Comment by nAviram** [comment]
make sure you have the certificates (distribution/development) in the keychain. 
I got this fail when I tried to build it on another mac without having the certificates...
