### ISSUE TITLE
Shared lanes (feature-request)

### ISSUE THREAD

**Issue by skywinder** [KrauseFx/fastlane#439]
In continue of #428 I would like to propose to implement some mechanism to share lanes between projects. 
Now I have to copy `Fastfile` from one well-configured project to another and manually change some local variables. But it's hard to keep them updated.
So, if I want to implement new lane or change old one - I have to remember to put changes  in all my projects's Fastfiles. It would much easy to maintain it in one place for all common lanes and implement in local `Fastfile` only app-specified lanes.

**Comment by skywinder** [comment]
Wow-wow! You read my minds! Just found new release and new topic https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#importing-another-fastfile

So it already implemented, thanks! 
So, then another additional addition:
What do you thinks to make some default place with all base lanes?

i.e. start every `Fastfile` with 
```
import "~/.fastlane/GeneralFastfile"
import "~/.fastlane/UserFastfile"
```

Thougs?

**Comment by KrauseFx** [comment]
Yes, already implemented :+1: I replied to the other issue
