### ISSUE TITLE
Error while running sigh

### ISSUE THREAD

**Issue by ohoachuck** [KrauseFx/fastlane#442]
Hello guys,
any idea why I can't run sigh ?

oho ~/Documents/Dev/fastlane/sigh $ sigh
/usr/local/lib/ruby/gems/2.1.0/gems/fastlane_core-0.11.1/lib/fastlane_core/configuration/commander_generator.rb:14:in `block in generate': Short option -d already taken for key cert_date (RuntimeError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane_core-0.11.1/lib/fastlane_core/configuration/commander_generator.rb:9:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/fastlane_core-0.11.1/lib/fastlane_core/configuration/commander_generator.rb:9:in `generate'
	from /usr/local/lib/ruby/gems/2.1.0/gems/sigh-1.0.0.beta6/bin/sigh:28:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/sigh-1.0.0.beta6/bin/sigh:74:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'

Is it my ruby version ? Why am I using sigh-1.0.0.beta6 ???

O.

**Comment by KrauseFx** [comment]
Could you please update using `sudo gem update sigh`?

**Comment by KrauseFx** [comment]
Oh sorry, I don't know how that happened. Please uninstall using `sudo gem uninstall sigh` (select all versions of `sigh`) and install again using `sudo gem install sigh`

**Comment by ohoachuck** [comment]
Hello Félix,
sorry I could have tried this before ask. And bring overhead to you.
Removing All and install it again did the trick. It's up and running.

Let me take this opportunity to congratulate you. Your fastlane initiative rocks.
In my day job, I do manage more than 20 iOS developper accounts and does submit all the apps for those account. So we might have good testcases for your project. Unfortunately we are not that good in Ruby. We'll try to contribute if we can. At least for finding issues.

O.

On 24 Jul 2015, at 14:48:10, Felix Krause <notifications@github.com> wrote:

Oh sorry, I don't know how that happened. Please uninstall using sudo gem uninstall sigh (select all versions of sigh) and install again using sudo gem install sigh

**Comment by KrauseFx** [comment]
That's great to hear, thanks for the kind words @ohoachuck :+1:
