### ISSUE TITLE
List of all the available environment variables

### ISSUE THREAD

**Issue by Darkreaper101** [KrauseFx/fastlane#444]
Good Day,

Is there somewhere like documentation on all the environment variables that fastlane uses in all of the tools so that we maybe know what we can set and what the usage is for each of them.

I'll be happy to help setup this documentation if I have a list of all the environment variables. :smile:

**Comment by KrauseFx** [comment]
Hey @Darkreaper101,

Sorry, that doesn't exist right now. All tools that are already migrated to the new configuration system show you the available environment variable when you use `sigh --help`

If you quickly want to generate a list, clone all main repositories, including `credentials_manager` and `fastlane_core` and search for `ENV[`. 

If you decide to aggregate all of them, it would be great if you could create a markdown file in the `docs` folder of this repository :+1:

**Comment by Darkreaper101** [comment]
Hi @KrauseFx,

No worries just wondering. I'll see if I can do that over the weekend. :smile: 

Thanks for the response.
