### ISSUE TITLE
"cert" action should read defaults from Appfile

### ISSUE THREAD

**Issue by ide** [KrauseFx/fastlane#445]
When an Apple ID, team ID, etc. aren't explicitly defined as CERT_* env variables or arguments passed to the `cert` action, it should use the values specified in the Appfile so that cert, sigh, and deliver use consistent values.

**Comment by KrauseFx** [comment]
`cert` action **does** read the Apple ID from the `Appfile`: 

```ruby
default_value: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id),
```

Can you share more information about your setup, e.g. your `Appfile`

**Comment by ide** [comment]
I misspoke --  I believe it was just the team ID that is not read from the Appfile. Sorry about the mix up. My Appfile looks like this:

```ruby
app_identifier "com.example.App"
team_id "AAAAAAAAAA"

for_platform :ios do
  for_lane :beta do
    app_identifier "com.example.AppBeta"
    team_id "BBBBBBBBBB"
  end
end
```
---

Regarding the Apple ID, I would like to define it in one environment variable that is used everywhere (I want it outside of the Appfile so each team member can use their own Apple ID). For example, it would be convenient for `FASTLANE_USERNAME` to provide the default value for deliver, cert, etc. while still allowing users to override the fastlane-wide default with the more specific env vars like `DELIVER_USER` and `CERT_USERNAME`. This is a separate issue from the original one I filed and it's just some feedback I have.

For now, I will add this to my Appfile: `apple_id ENV["FASTLANE_USERNAME"]` =)

**Comment by KrauseFx** [comment]
I just pushed a new version that should fix those issues, please update using `sudo gem update credentials_manager` :+1:

**Comment by ide** [comment]
@KrauseFx thanks!
