### ISSUE TITLE
[Important] Improve passing of parameters for all tools

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/fastlane#45]
Some tools, like `sigh` can only be passed some of the available command like options, not all of them.

Also, sometimes users want to have a parameter for a tool, for which there is already an environment variable available (https://github.com/KrauseFx/sigh/issues/45)

There needs to be a more unified way:

There are 5 ways to pass configuration to the individual fastlane tools (ordered):

- Command line parameter (e.g. `deliver -u felix@krausefx.com`)
- Passing options with `fastlane`
- Configuration file (only for `snapshot` and `deliver`)
- Environment variables
- Asking for information if missing

The user should be able to set every option in all 5 ways.

Any other ideas? Concerns?

**Comment by KrauseFx** [comment]
This would result in **one** class of each tool, defining all available options, with a short description of what they're for. 

We then iterate through all available options and pass it to `commander`

**Comment by joshdholtz** [comment]
@KrauseFx How does this effect #28 since that is added listening in an the `--env` option? I'm all for improving this! Just curious :grin:

**Comment by KrauseFx** [comment]
There are 3 ways to pass configuration to the individual fastlane tools:

- Configuration file (only for `snapshot` and `deliver`)
- Command line parameter (e.g. `deliver -u felix@krausefx.com`)
- Environment variables

The user should be able to set every option in all 3 ways.

**Comment by dfranzi** [comment]
I'm finding this to be particularly important with sigh, as it'd be great to be able to specify the file name and output directory from within fastlane when fetching provisioning profiles.

**Comment by KrauseFx** [comment]
I completely agree. Any feedback appreciated! I want to get this right when working on this issue.

**Comment by dfranzi** [comment]
I've just started diving into developing a pipeline with fastlane, so I don't have the best insight into all use cases yet. With sigh in particular, I'd want to be able to define parameters per lane. The usage that I see would involve updating the sigh action to work with parameters in a similar manner to produce. This would enable me to define the parameters inline to the call, or as environment variables externally first.

**Comment by KrauseFx** [comment]
Right now, it's not clear which environment variables to use: https://github.com/KrauseFx/cert/issues/1#issuecomment-74852448

**Comment by KrauseFx** [comment]
The current plan is to provide a `ConfigurationManager`-Class in the `fastlane_core`, which each individual tool can call with its available options.

From then on, each tool can call the `ConfigurationManager` and ask for specific values. If there was no command line option given, no configuration in the configuration file and no environment variable, it will ask the user for the value and show information on how to set this value programatically.

Thanks @joshdholtz :+1:

**Comment by almassapargali** [comment]
Hello, I think it may be a little late, since we already make a big use of `ENV`, but I'd propose to use `ENV` only for sensitive information.

For other information I think we should take from configuration file, fastlane options, and command line arguments (the latter overwrites former). What do you think of this?

**Comment by KrauseFx** [comment]
Why wouldn't we also allow passing of **any** information from the environment?

**Comment by almassapargali** [comment]
I don't know, just think would be nice to have one place of input.

**Comment by almassapargali** [comment]
Also maybe use something like [this](https://github.com/KrauseFx/produce/blob/master/lib/produce/config.rb) but generalised for all tools?

**Comment by almassapargali** [comment]
Ok, I'll check out how other established tools (`cocoapods`, `homebrew`, etc.) handles this and write back.

**Comment by KrauseFx** [comment]
Started with the pull request: https://github.com/KrauseFx/fastlane_core/pull/8

Will take a few more days until fully finished :rocket:

**Comment by KrauseFx** [comment]
Everything except for the configuration file is finished :rocket:
