### ISSUE TITLE
Passing WHAT_TO_TEST environment variable to deliver from fastlane

### ISSUE THREAD

**Issue by DenHeadless** [KrauseFx/fastlane#457]
Hi!

In my CI setup i'm trying to automatically parse my changelog file, and pass latest version changes to WHAT_TO_TEST environment variable for deliver gem. The way i do this, is call 

ENV['DELIVER_WHAT_TO_TEST'] = release_notes

in one of the lanes. Unfortunately, it does not seem like deliver is picking up this environment variable and "What to test" field turns out empty on iTunesConnect. Maybe i'm doing something wrong? How can i pass this environment variable to deliver?

p.s. I'm using this command to upload build: deliver( beta: true, skip_deploy: false)

**Comment by KrauseFx** [comment]
`deliver` should use the `DELIVER_WHAT_TO_TEST` variable. Make sure the environment variable is properly set. 

Do you set it in your `Fastfile`? If so, you can add a `puts ENV['DELIVER_WHAT_TO_TEST']` right before the `deliver` action.

**Comment by DenHeadless** [comment]
Yes, i tried putting this right before calling deliver action in Fastfile, and it correctly printed envrironment variable:

Fastfile:
```
 puts ENV['DELIVER_WHAT_TO_TEST']
 deliver( beta: true, skip_deploy: false, force:true)
```

Output in console:
```
[11:47:27]: ## 1.1.2 July 28 2015

* Fix issue, that prevented user from sharing artwork, when artwork was opened from user profile screen.
* Attempt to fix rare WebCore crash, that was introduced in 1.1.1 release on iOS 8.
[11:47:27]: ---------------------
[11:47:27]: --- Step: deliver ---
[11:47:27]: ---------------------
```

**Comment by DenHeadless** [comment]
@KrauseFx  This is really interesting. Not only environment variable is getting set, but deliver itself prints WHAT_TO_TEST correctly:

```
[11:58:34]: Build is ready 3.2.1...
[11:58:35]: Setting the following information for this build:
[11:58:35]: DELIVER_WHAT_TO_TEST: '## 1.2.0 July 30 2015 Sprint 10

* Implemented sliding side menu with simple parallax and shadowing effects
* Currently working buttons - Sign in, Sign out, Discover and Profile.'
[11:58:35]: DELIVER_BETA_DESCRIPTION: ''
[11:58:35]: DELIVER_BETA_FEEDBACK_EMAIL: ''
[11:58:37]: Successfully distributed latest beta build
```

However What to test field on TestFlight is empty.

p.s. i'm using fastlane 0.13.1(deliver has version 0.13.0).

**Comment by DenHeadless** [comment]
@KrauseFx Latest fastlane(1.16.0) works correctly and updates What to test section in TestFlight. 

Thank you!

**Comment by KrauseFx** [comment]
Great to hear :+1:
