### ISSUE TITLE
You have to pass a valid version number using the Deliver file. (e.g. 'version "1.0"')

### ISSUE THREAD

**Issue by rais38** [KrauseFx/fastlane#47]
I'm trying to send version to TestFlight (iTunes Connect) with this `lane`:

```ruby
lane :appstore do
  sigh :skip_install
  system("cd ..; ipa build --verbose --configuration AppStore")
  deliver :skip_deploy, :force, ipa: "../jobandtalent.ipa"
end
```

And this `Deliverfile`:

```ruby
########################################
# App Metadata
########################################

# The app identifier is required
app_identifier "mycompany.identifier"
apple_id "*****"


# This folder has to include one folder for each language
# More information about automatic screenshot upload:
# https://github.com/KrauseFx/deliver#upload-screenshots-to-itunes-connect
screenshots_path "./deliver/screenshots/"


# version '1.2' # you can pass this if you want to verify the version number with the ipa file

config_json_folder './deliver'

success do
  system("say 'Successfully deployed a new version.'")
end

error do |exception|
  # custom exception handling here
  raise "Something went wrong: #{exception}"
end
```

A few days ago I could upload version without problems ...Now is required to specified the version in `Deliverfile`?

**Comment by rais38** [comment]
If I include the version in the `Deliverfile` if it works ... This is correct?

**Comment by KrauseFx** [comment]
Well, it should fetch the version number from the `ipa` file. Looks like `deliver` has issues detecting the version number.

**Comment by KrauseFx** [comment]
Might be caused by too many plist files:

https://github.com/KrauseFx/deliver/issues/73

I need more information about the extracted ipa file to solve this problem.

**Comment by rais38** [comment]
I can see in generated `ipa` file there are some `plist` files:

* For own consumption of the app in the root of `.app` folder
* Inside each storyboards of the app
* In the localization folders (`en.lproj`, `es.lproj`...)
* And only one Info.plist in the root folder with the relevant information `CFBundleShortVersionString`, `CFBundleVersion`...

This information can help you?

**Comment by patoroco** [comment]
Same here with last fastlane version

**Comment by KrauseFx** [comment]
Sorry about that, you can pass the version number manually and provide your own automatic detection of the version number using `PlistBuddy` :disappointed:

**Comment by patoroco** [comment]
It's possible to send version as parameter? Or we should update DeliverFile programmatically?

**Comment by KrauseFx** [comment]
Yes, of course: https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md#version

Just add
```ruby
version "1.0"
```

or something like
```ruby
version File.read("file.txt")
```

or your own script

**Comment by patoroco** [comment]
Oh, nice approach! Maybe I'll do one action for that :)

**Comment by KrauseFx** [comment]
Change it to just

```ruby
version `"/usr/libexec/plistbuddy -c Print:CFBundleShortVersionString '../myProject-Info.plist'`
```

and remove the `before_all`

:rocket:

**Comment by patoroco** [comment]
:clap:

**Comment by KrauseFx** [comment]
This is also improved with the latest version :+1:
