### ISSUE TITLE
Can't create a beta build

### ISSUE THREAD

**Issue by besi** [KrauseFx/fastlane#471]
When I upload my beta build I get the following error:

    fastlane beta

> [19:01:22]: [Transporter]: DBG-X:   parameter Warnings = [WARNING ITMS-90191: "Missing beta entitlement. Your app does not include the beta-reports-active entitlement. If you intend to distribute this build via TestFlight for beta testing, please re-build this app with a newly generated provisioning profile."]

I did a couple of builds and only one of them was successful:

<img width="916" alt="screen shot 2015-08-04 at 19 18 44" src="https://cloud.githubusercontent.com/assets/160412/9059565/b6a74a26-3add-11e5-9f31-d4dc913ed673.png">

I have an `AppStore_XY.mobileprovision` file which I can run through:

     security cms -D -i AppStore_XY.mobileprovision > Profile.xml

The file includes the BETA Entitlements:

    <key>beta-reports-active</key>
    <true/>

This ist my `Fastfile`:

```ruby
platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    #cocoapods
    increment_build_number
    commit_version_bump
    push_to_git_remote
    
    ipa(scheme: 'Cards')
    # xctool # run the tests of your app
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    snapshot
    
    # TODO: `cert` causes a prompt during execution
    # See https://github.com/fastlane/cert/issues/28
    cert
    sigh
    deliver(beta: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
```

Things I tried:

- Delete all the certs and provisioning profiles

**Comment by KrauseFx** [comment]
@besi As far as I know the build should still work, it's just a warning. Can you verify that?

**Comment by besi** [comment]
The build seems to work, that is true, but my testers can't test the new builds unless they contain the BETA Entitlement.

**Comment by KrauseFx** [comment]
@besi I worked on a new tool called [gym](https://github.com/fastlane/gym), if you have some time try building using `gym` and uploading the resulting ipa file.

**Comment by besi** [comment]
@KrauseFx Thanks, I did revoke all the certificates and provisioning profiles again and now I have another "valid" beta build.

Can I test `gym` with fastlane already? I assume I just add an `sh` call to my `Fastfile`?

**Comment by KrauseFx** [comment]
@besi Yes, there is no integration yet, so you'll have to call it from via the `sh` command :+1:
