### ISSUE TITLE
Crash on put_build_into_beta_testing! 

### ISSUE THREAD

**Issue by rrecio** [KrauseFx/fastlane#475]
![screen shot 2015-08-05 at 12 33 14 pm](https://cloud.githubusercontent.com/assets/52694/9089979/513c3c64-3b6e-11e5-8911-d9abcceff96b.png)

**Comment by rrecio** [comment]
happened again

![screen shot 2015-08-05 at 6 27 13 pm](https://cloud.githubusercontent.com/assets/52694/9098399/0ebb9eac-3ba0-11e5-9d46-f77c7efeb1e5.png)

**Comment by KrauseFx** [comment]
Sorry, submitting the app for review is not very stable right now as it doesn't use `spaceship` yet, I'm already working on it: https://github.com/KrauseFx/deliver/pull/259

**Comment by KrauseFx** [comment]
Check out https://github.com/KrauseFx/deliver/releases/tag/1.0.0.beta as this will fix your issue :+1:

**Comment by rrecio** [comment]
Thanks. You're amazing!

**Comment by KrauseFx** [comment]
That's what I'm here for :rocket:
