### ISSUE TITLE
Fastlane's error output

### ISSUE THREAD

**Issue by Khronoss** [KrauseFx/fastlane#479]
Hello :)

I've been stuck for a while on build failure using Fastlane. In fact, everything went great when I tried using it on my local computer, but when I launched a build on a distant server, the build directly failed each time.
It seems you override the ipa's error output tu write yours : 
```
[31m[11:05:33]: [0m[33mA build error occured. This can have many reasons, usually[0m
[31m[11:05:33]: [0m[33mit has something to do with code signing. The `ipa` action[0m
[31m[11:05:33]: [0m[33muses `shenzhen` under the hood: https://github.com/nomad/shenzhen[0m
[31m[11:05:33]: [0m[33mFor code signing related issues, check out this guide:[0m
[31m[11:05:33]: [0m[33mhttps://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md[0m
[31m[11:05:33]: [0m[33mThe command that was used by fastlane:[0m
[31m[11:05:33]: [0m[33mkrausefx-ipa build -s "smarty" -c "Release" -m "/Users/admin/.jenkins/jobs/SMARTY_iOS_Dev/workspace/InHouse_com.prismamedia.smarty.dev.mobileprovision" --verbose | xcpretty[0m
```

But actually, this time it wasn't caused by a bad provisioning profile ! (Yes, it can happen some times :p)
So I tried to launch the command line on my server using ssh, and the error was simply as follow : 
"Could not find the scheme <scheme name>"

And then I figured out that I had to share my schemes on the repository, and...tadam ! Everything worked well :)

So I think that at first sight, writing you error is not bad because it's true that the build phase usually fails because of the provisioning profile, but when it's not because of that...it's just not possible to find why it failed without launching the same command manually. Maybe it would be nice to not override the error, but just concatenate your ? :)

Thank you, and as always : Your tool chain is awesome :)

**Comment by KrauseFx** [comment]
Thanks for reporting this @Khronoss. You will be very happy to hear, that is exactly what I've been working on the last few days/weeks with [gym](https://github.com/fastlane/gym). `gym` will soon replace `shenzhen` does shows you exactly those kind of error messages. 

Please try `gym` and let me know how it works for you :+1:

**Comment by Khronoss** [comment]
Oh great ! :D I didn't see the doc of Gym until now =X

I can't promise you now for testing Gym, because (as an internship) I don't really want to take the risk of breaking the building process of our apps. But I'll talk about it to my tutor :)

Thank you ! \o

**Comment by KrauseFx** [comment]
@Khronoss `gym` is not announced yet, that's why it's not in the docs. You don't need to integrate it into the build process - instead just run it manually for your project just by running `gym -s "scheme"`

**Comment by Khronoss** [comment]
Okay, why not ? :)

**Comment by KrauseFx** [comment]
Cool, thanks! I'll close this issue for now, feel free to add comments here :+1:
