### ISSUE TITLE
Introduce an automated translation toolchain

### ISSUE THREAD

**Issue by bhagyas** [KrauseFx/fastlane#480]
The new tool in the fastlane chain should add translation and localization support for the existing apps and app store publishing process.

At minimum, it should support for the following.
- Defining languages to be translated into in configuration.
- Configuration of Google Translate API keys.
- Extraction of Strings from code for localisation.
- Modifying code to support localizable strings.
- Create translation string files (Localizable.strings)
- Generate pseudo localization files for extracted strings.
- Generate App description and screenshot description metadata.

**Comment by KrauseFx** [comment]
Thanks for your suggestion, but this feature is currently not planned. I'll close this issue for now, feel free to submit another issue :+1:
