### ISSUE TITLE
dsym_zip action should allow zipping of all dsyms, not just the app dsym

### ISSUE THREAD

**Issue by robertjpayne** [KrauseFx/fastlane#484]
Currently if you feed an xcarchive to `dsym_zip` action it will only pull out the app dsym. With iOS 8 and prevalence of dynamic frameworks there's typically loads of dsyms that need to be included for proper symbolication.

Was curious if this is something that should be a flag `all: true` or just a default?

**Comment by KrauseFx** [comment]
Sounds good, the action can be found [here](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/dsym_zip.rb) if you want to add this functionality :+1:

**Comment by KrauseFx** [comment]
Probably a `all: true` would be a good idea as we don't want to break/change existing setups.

**Comment by robertjpayne** [comment]
@KrauseFx done via the PR, it's an optional and defaults to false.

**Comment by KrauseFx** [comment]
Thanks for the pull request @robertjpayne! Fastest response time :rocket:
