### ISSUE TITLE
Produce not fetching app_name automatically from Fastlane

### ISSUE THREAD

**Issue by Srthk** [KrauseFx/fastlane#492]
On running `fastlane deploy app_name:McDonaldsZom version:1.0`, the fastlane detects the app_name automatically but the produce command prompts for the app_name again as seen in the screenshot. On explicitly provide app_name inside `produce ( ... )`, it detects the app_name. So, is it possible to pass the app_name directly via fastlane deploy or is the app_name stored somewhere in an Environment variable?

![screen shot 2015-08-11 at 11 31 55 am](https://cloud.githubusercontent.com/assets/7152922/9191378/45de8796-401e-11e5-8621-71e4c8aba897.png)

**Comment by KrauseFx** [comment]
You didn't share your `deploy.sh` or `Fastfile`, but I assume: Try passing the name to the `produce` action:
```ruby
produce(app_name: options[:app_name])
```

**Comment by Srthk** [comment]
Thanks. Adding this to my fastfile worked -
`lane :deploy do |options|   
    #cert
    produce(
    app_name: options[:app_name]
    )`

**Comment by KrauseFx** [comment]
Great to hear :+1:
