### ISSUE TITLE
Select Xcode Version

### ISSUE THREAD

**Issue by bassrock** [KrauseFx/fastlane#50]
With all the latest Xcode betas it would be great if we could have an option to select the Xcode version to use.

**Comment by KrauseFx** [comment]
As far as I know you can set it using `xcode-select --switch <path>`. Does that work for you?

**Comment by bassrock** [comment]
That could work but I believe that needs to be run as sudo. will fastlane support that?

**Comment by KrauseFx** [comment]
It should. Can you try: `sh "xcode-select --switch ..."` and run fastlane with `sudo`? If that won't work, try adding `sudo` in front of `xcode-select`.

**Comment by bassrock** [comment]
AH! better option that can be added to the readme: https://github.com/facebook/xctool/issues/193
Just add the following in the before all:

```
ENV['DEVELOPER_DIR'] = '/Applications/Xcode-Beta6.3.app/Contents/Developer'
```

**Comment by KrauseFx** [comment]
Wow, nice find! Where could I add this to the documentation? `fastlane` README?

**Comment by bassrock** [comment]
Yea probably the best place.

**Comment by KrauseFx** [comment]
Here we go: https://github.com/KrauseFx/fastlane/commit/ed6e7f493c5a5c7dcee1ac4ceb8e455587d0cd68

Thanks for letting me know :+1:
