### ISSUE TITLE
beta_pa path is relative to the fastlane directory, not the project directory

### ISSUE THREAD

**Issue by ellucianBret** [KrauseFx/fastlane#500]
To have deliver(beta: true) pick up my ipa file that was exported to ./build by xcexport. I had to set beta_ipa in Deliverfile and its path was relative to the ./fastlane directory.

I had to use "../build/My App.ipa"

Also, I see that xcexport sets Actions.lane_context[SharedValues::IPA_OUTPUT_PATH], however it doesn't seem to get picked up by Deliver. Should it?

**Comment by KrauseFx** [comment]
Regarding the `IPA_OUTPUT_PATH`: does that work in the latest version for you?

About the folder: Yes, that's an issue I'm aware of, I'm not sure if I should change that behaviour, as there are existing setups that might break.

When `fastlane` passes paths, like the `ipa_output_path` it usually resolves the path to be absolute to not run into this issue.

**Comment by ellucianBret** [comment]
How about adding an ENV variable with the full path?

Though I am not sure it works to use a ENV var in the Deliverfile. Does it?

**Comment by apouche** [comment]
I agree this should probably be solved in a nice manner, I had to use `sh ENV['PWD']+"/scripts_path"` to work around this. This is not ideal.

**Comment by KrauseFx** [comment]
I agree with you, but this is not something we can change without breaking all existing setups.
