### ISSUE TITLE
Get current build number  and current version number

### ISSUE THREAD

**Issue by sduperron-viadeo** [KrauseFx/fastlane#501]
In our workflow, I want to be able to tag git using the current version and build numbers, then increment the build number.
Right now, it is not possible in fastlane to access these informations without incrementing first.

In my Fastfile, I have setup a workaround using these (hacky) functions:
```ruby
def current_build_number
  build_number = `pushd .. > /dev/null; agvtool what-version -terse; popd > /dev/null`.strip
  return build_number
end

def current_version
  version = `pushd .. > /dev/null; agvtool what-marketing-version -terse1; popd > /dev/null`.strip
  return version
end
```

It would be nice to have these as actions in fastlane (e.g. `get_build_number` and `get_version_number`).
Or maybe let fastlane fetch these informations and set them up as `increment_version_number` and `increment_build_number` do.

**Comment by KrauseFx** [comment]
Great idea, you can follow this short [guide](https://github.com/KrauseFx/fastlane/tree/master/docs#extensions), let me know if you need any help :+1:
