### ISSUE TITLE
Fastlane should stop at the first error

### ISSUE THREAD

**Issue by pvegh** [KrauseFx/fastlane#510]
For example:
```
INFO [2015-08-17 10:18:28.99]: [SHELL OUTPUT]: ⌦  clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO [2015-08-17 10:18:28.99]: [SHELL OUTPUT]:
INFO [2015-08-17 10:18:28.99]: [SHELL OUTPUT]:
INFO [2015-08-17 10:18:28.99]: [SHELL OUTPUT]: ▸ Building Pods/Realm [Release]
INFO [2015-08-17 10:18:28.99]: [SHELL OUTPUT]: ▸ Processing Info.plist
INFO [2015-08-17 10:18:28.99]: [SHELL OUTPUT]: ▸ Compiling RLMAccessor.mm
```

I think since the first line produces an error, everything below it should not be executed (Building a pod, processing and compiling).
It seems to be a waste of time since the build is broken anyway. I'm not sure exactly how fastlane works, so it may not be possible or I might be reading the output incorrectly, but I thought it is worth opening an issue.
Fail fast!

**Comment by KrauseFx** [comment]
@pvegh I agree. Can you share more information about your setup? Do you use the `ipa` or the `gym` action to build your app? Also, it looks like you're using an outdated version of `fastlane`, can you share `fastlane -v`?

**Comment by pvegh** [comment]
Let's not worry about this right now, I think I will just switch to gym, the description is very promising.
All I wanted to say with the issue is the tool should fail faster and print better errors, which is exactly what gym is all about :)

**Comment by KrauseFx** [comment]
Okay, great to hear :+1: I'll close the issue then
