### ISSUE TITLE
Reduce size of HipChat icon image.

### ISSUE THREAD

**Issue by dfranzi** [KrauseFx/fastlane#52]
Using the HipChat action, the messages sent include the fastlane icon. This icon is huge and often much larger than the contents of a message, excluding errors with long stack traces. It'd be great to reduce the size of the image used for this to more cleanly fit with more average-sized messages.

![fastlane_hipchat_icon](https://cloud.githubusercontent.com/assets/1900547/6236283/23e45120-b69e-11e4-8fa4-5daf5e5c3d01.jpg)

**Comment by KrauseFx** [comment]
Looking at the code, its width should only be 50px: https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/hipchat.rb#L30

Maybe @jingx23 can help?

**Comment by dfranzi** [comment]
A quick test seemed to show that the style section of the img tag was not taking effect. I replaced the tag with:

```
<img src=\"https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png\" width=\"50\" height=\"50\">
```
and the image was properly resized with the next message. This isn't as future-proof, since it's explicitly setting the dimensions of the height as well, but does the trick.

**Comment by dfranzi** [comment]
Ah, this is a bit old, but may indicate the issue: https://twitter.com/hipchat/status/309704328229298177

I'll create a pull request with the update.

**Comment by KrauseFx** [comment]
I think it's quite odd to just put in HTML code. Thanks for providing a pull request :+1:
