### ISSUE TITLE
No codesigning identities found

### ISSUE THREAD

**Issue by aloifolia** [KrauseFx/fastlane#523]
When I try to deploy my app with fastlane I get the following error message (I replaced the actual profile name by a dummy name):

    Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and private key pairs) that match the provisioning profile specified in your build settings (“eu.company.app XXXX”) were found.

Why is fastlane not able to find the identity?

This is my fastlane configuration:
```
fastlane_version "1.18.0"
default_platform :ios
platform :ios do

  before_all do
    cocoapods
  end

  lane :deploy do
    sigh

    # extract the version number from git's tags
    lastStoreVersionStripped = '0'
    lastStoreVersion = `git tag | sort -n | grep 'store'`.split("\n").last
    if lastStoreVersion.match(/^store\/(.*)/)
      lastStoreVersionStripped = $1
    end

    increment_version_number(
      version_number: lastStoreVersionStripped
    )
    increment_build_number(
      build_number: ENV['BUILD_NUMBER'].to_i || 0
    )

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    gym(scheme: "myScheme") # Build your app - more options available
    deliver(skip_deploy: true, force: true)
  end

end
```

So I let fastlane [set the provisioning profile](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) to overcome another error message that [I got before](https://github.com/KrauseFx/fastlane/issues/385).

**Comment by KrauseFx** [comment]
You can follow the code signing guide https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md that should help you resolve this issue :+1:

**Comment by aloifolia** [comment]
Well, this is what I did which is why I added the link to this page at the end of my post. Any further ideas?

**Comment by KrauseFx** [comment]
What have you set as the code signing identity value in the project file? Select your code signing identity and try if that helps :+1:

**Comment by aloifolia** [comment]
I just checked the signing identities and saw that for the Release build, the signing entities were set to iPhone Developer instead of iPhone Distribution. So I changed it to the latter:

![bildschirmfoto 2015-08-21 um 13 12 57](https://cloud.githubusercontent.com/assets/1295054/9407038/21a3a8ee-4806-11e5-83cf-6d91799c2c39.png)

However, the error message remains.

Also, I noticed that fastlane (sigh) seems to be generating a new provisioning profile each time it runs:
````
[13:10:52]: No existing profiles, creating a new one for you
[13:10:56]: The name 'eu.company.app AppStore' is already taken, using another one. 
`````
As a result, Apple Member Center now already lists 5 active profiles for 'eu.company.app AppStore'

![bildschirmfoto 2015-08-21 um 13 20 45](https://cloud.githubusercontent.com/assets/1295054/9407163/0d2e53b8-4807-11e5-848a-147c89c22bdf.png)

I am confused...

**Comment by KrauseFx** [comment]
Can you also run `cert`? You seem to not have the code signing identity installed that's required to sign your application. 

Make sure you have the certificate + private key installed which is used in the provisioning profiles.

**Comment by aloifolia** [comment]
Ok, with `cert` fastlane does not show this error message any more. When reading the cert guide I wondered whether I should actually use `sigh(force: true)`. Wouldn't  this option clutter up the list of provisioning files in Member Center?

**Comment by KrauseFx** [comment]
No, the `:force` option will re-use existing profiles, but will make sure to re-generate the profile (under the same name) to have the most up to date code signing identity.
