### ISSUE TITLE
auto-increment build version number: There does not seem to be a CURRENT_PROJECT_VERSION

### ISSUE THREAD

**Issue by aloifolia** [KrauseFx/fastlane#525]
Usually, we use the Jenkins build number also for the app build. So, for instance, the version 1.2.3 would get the build number 53. Now if I use fastlane on a different machine than the Jenkins server, e.g. my own laptop, for testing purposes I would like to use an arbitrary build number (the actual upload for the release would later on be managed by Jenkins). Therefore, I used the following setting:
`````
    if buildVersion
      increment_build_number(build_number: buildVersion)
    else
      randomNumber = 5000 + rand(5000)
      increment_build_number(build_number: randomNumber)
      puts "try to increment"
    end
`````
=> The number is generated randomly. However, this does not work in the long run, because each time I trigger another test run `fastlane deploy` the build number has to increase. Otherwise you get this:
`````
[17:38:06]: ERROR ITMS-90188: "Invalid Pre-Release Build. The build version (CFBundleVersion) '5821' in the Info.plist file must be higher than the build version (CFBundleVersion) '8883' of the latest build within train version (CFBundleShortVersionString) '1.3.4'."
````
Since it is not possible to delete old builds in iTunesConnect I was wondering if fastlane can somehow check iTunesConnect for the latest uploaded build number. I would like to have a setting like this
`````
    if buildVersion
      increment_build_number(build_number: buildVersion)
    else
      increment_latest_itunesconnect_build_number
    end
`````
The usual `increment_build_number` call does not work since I do not manage this number via XCode (it is always 0).

**Comment by Liquidsoul** [comment]
Hi @aloifolia!
Why wouldn't you use `commit_version_bump` and `push_to_git_remote` to share the increments from your Jenkins configuration ?
This way, you can track your releases in your repository and will be able to deploy new releases from different computers :smiley:

**Comment by aloifolia** [comment]
@Liquidsoul: Thank you for this hint. I will try this as soon as I get [another thing fixed](https://github.com/KrauseFx/fastlane/issues/532).

**Comment by Liquidsoul** [comment]
@aloifolia: with #532 closed, did you have time to test this ? :smiley:

**Comment by aloifolia** [comment]
@Liquidsoul Thank you, it seems to work now. I did not acutally test it with Jenkins, but on my local machine the process behaves as expected. I guess, it will also do so on the server.

**Comment by KrauseFx** [comment]
:rocket:

**Comment by besi** [comment]
@KrauseFx I run into this with every new project, could the task `increment_build_numnber` not check for `CURRENT_PROJECT_VERSION = X` and set it if necessary?
