### ISSUE TITLE
lane support within the deliver file?

### ISSUE THREAD

**Issue by mark5422** [KrauseFx/fastlane#526]
Is there support for lanes within the deliver file? I want to submit two different build identifier IPAs within the same fastlane set up. What I’m looking for is setting up a deliver file to use certain details when using one of these IPAs based on what lane I’m running fastlane on and want to know if that’s possible.

Thanks

**Comment by KrauseFx** [comment]
Sorry, no lanes in the `Deliverfile`. You can easily pass information from the `Fastfile` to the `Deliverfile` using environment variables:
```ruby
ENV["KEY"] = "value"
```

Does that help? :+1:

**Comment by mark5422** [comment]
It does, thanks
