### ISSUE TITLE
cocoapods command and Pods not git-ignored

### ISSUE THREAD

**Issue by masa-beheim** [KrauseFx/fastlane#529]
Running `cocoapods` after `ensure_git_status_clean` makes `commit_version_bump` fail since `pod install` at minimum changes the `project.pbxproj`. I have projects where the pods need to be checked in. So in that case I am doing:
```ruby
ensure_git_status_clean    # this is in addition to the one in before_all, just to make sure
cocoapods
sh "git add -A && git commit -m 'pod install'"
```
Is there a better way? I had a look at the examples but they are using plain `cocoapods` so I am wondering what I am missing here.
I'd love to have something like:
```ruby
cocoapods(
  commit: true,    # optional, default: false, in my case this flag would be sufficient
  commit_message: 'your message',    # optional, default: 'pod install'
  skip_ensure_git_status_clean: false,    # optional, default: true
)
```
Also this would make it easier for new users to understand the impact of the `cocoapods` command in the fastlane.

**Comment by KrauseFx** [comment]
It wouldn't make sense for the `cocoapods` action to commit something, this could be quite dangerous in my opinion. 

How about you first `ensure_git_status_clean`, then the version bump, then the `commit_version_bump` then the `cocoapods`? This way the commit will work without any problems.

**Comment by masa-beheim** [comment]
Thanks for the input. You are right, changing the order makes `commit_version_bump` go through, but I still have to commit manually after `cocoapods`, which is my point.

For me it makes sense to commit, as long as a clean git state is ensured at entry. So you are only tracking changes caused by `cocoapods`. And I (have to) trust `pod install` and its changes (speaking about dangerous). This would not change the entry and exit condition with regards to the git state. And side effects to other commands like `commit_version_bump` would not happen. 

So I think currently there is no better way than just do the commit manually (in projects where pods need to be checked in at least otherwise this is not a problem)...

**Comment by Liquidsoul** [comment]
Hi @masa-beheim !

Maybe I am wrong, but I think @KrauseFx's point is that it would be dangerous to do that automatically in your CI workflow. And I agree with this because I think you need to have full control over the evolution of your dependencies.

However, I suppose that, because you're checking in your pods, you want to have a `fastlane` lane that do a `pod install` to update your pods and then commit the changes. This way, when you want to update your dependencies, you just need to call your lane. Is that your goal here?

**Comment by masa-beheim** [comment]
I understand what you guys mean now. I agree. And your input got me thinking. Obviously I do not need to run `pod install` at all on the server when checking pods in. This was my misunderstanding. Thank you @KrauseFx and @Liquidsoul for the help. You can close this now.

**Comment by KrauseFx** [comment]
Great to hear :+1:
