### ISSUE TITLE
Build number is correctly set but not correctly propagated to environment variables

### ISSUE THREAD

**Issue by vittoriom** [KrauseFx/fastlane#530]
Not sure what I'm doing wrong, but I get this output after setting the build number:

```
Setting version of project [REDACTED] to:
[08:57:15]: [SHELL]: 2015.8.24.8.57
```

This is correct, and the build number is correctly set in the info.plist

Later, though:

```
[09:29:02]: {
    :ENVIRONMENT=>nil, 
    :PLATFORM_NAME=>nil, 
    :LANE_NAME=>"beta", 
    :BUILD_NUMBER=>2015,
    :IPA_OUTPUT_PATH=>"/Users/jenkins/slave_jenkins/workspace/[REDACTED].ipa", 
    :DSYM_OUTPUT_PATH=>"/Users/jenkins/slave_jenkins/workspace/[REDACTED].app.dSYM.zip", 
}
```
As you can see the build number is set to **2015** instead of **2015.8.24.8.57**

This results in the wrong tag being pushed when the `add_git_tag` step is executed. Do you know if I should correct something here?

**Comment by KrauseFx** [comment]
Are you using the `increment_build_number`, right?

**Comment by KrauseFx** [comment]
Found the issue!

**Comment by vittoriom** [comment]
Yes, I'm doing

```
private_lane :prepare do
  build_number = Time.new.strftime("%Y.%-m.%-d.%-H.%-M") # we need to remove leading zeros from every version component or testflight may complain
  increment_build_number build_number: build_number
end
```

**Comment by KrauseFx** [comment]
Fixed it, this will be in the next release :+1:

**Comment by vittoriom** [comment]
wow, that was fast! Thanks a lot ^^

**Comment by KrauseFx** [comment]
In the mean time, you can pass the new version number to the `git_tag` action :+1:
