### ISSUE TITLE
 ensure_git_branch with regex

### ISSUE THREAD

**Issue by kylejm** [KrauseFx/fastlane#534]
This would be super useful for ensuring branches that are suffixed (e.g. `hotfix/__VERSION__` or `release/__VERSION__`)

**Comment by KrauseFx** [comment]
:+1:

**Comment by Liquidsoul** [comment]
The regex support has been released in 1.23.0. Maybe this issue can be closed @KrauseFx ? :rocket:

**Comment by KrauseFx** [comment]
Thanks @Liquidsoul :+1:

**Comment by KrauseFx** [comment]
@Liquidsoul Can you drop me a super short email (you can find it on my profile)
