### ISSUE TITLE
How do i sign build using identity having name with single quotes

### ISSUE THREAD

**Issue by Gimungagap** [KrauseFx/fastlane#540]
I want to sign an IPA file via GYM with a specified local provisioning profile. This requires code signing identity to work. I tried to do it this way (from Fastfile):

```
  gym(
    workspace: "gitlab-ci-test.xcworkspace",
    ....
    provisioning_profile_path: 'fastlane/provisioning/profile.mobileprovision',
    codesigning_identity: "iPhone Distribution: 'My company' Ltd."
  )
```

The build succeeds but when code signing begins, the the codesign parameter looks like this:

```
--sign iPhone Distribution: My Company Ltd.
```

There are no quotes so identity is not found. I tried escaping quote marks with \ and \\\ and  so the first way didn't change anything at all, and the second one made an error. 
Can I escape the quotes somehow or use something else to sign the build correctly in this case? I tried to use IPA util and the same issue occurred. The pure codesign doesn't look good because it requires the locations of entitlements and build files. Maybe there is another nice way?

**Comment by KrauseFx** [comment]
Where do you have the `--sign iPhone Distribution: My Company Ltd.` from? 

The code I found in `gym`:
```ruby
        if Gym.config[:codesigning_identity]
          options << "--sign '#{Gym.config[:codesigning_identity]}'"
        end
```

**Comment by Gimungagap** [comment]
I mean console output. It looks like this:

```
### Codesigning 'fastlane/provisioning/profile.mobileprovision' with 'iPhone Distribution: My company Ltd.'
+ /usr/bin/codesign --force --preserve-metadata=identifier,entitlements --sign iPhone Distribution: My company Ltd. --entitlements /var/folders/6m/djd59_8n3x7f1v0x1ww2t_j80000gp/T/Lv8yN7Jw84/entitlements_plistHKSGvZRQ /var/folders/6m/djd59_8n3x7f1v0x1ww2t_j80000gp/T/Lv8yN7Jw84/Payload/gitlab-ci-test.app
Program /usr/bin/codesign returned 1 : [iPhone Distribution: My company Ltd.: no identity found
]
error: /usr/bin/codesign --force --preserve-metadata=identifier,entitlements --sign iPhone Distribution: My company Ltd. --entitlements /var/folders/6m/djd59_8n3x7f1v0x1ww2t_j80000gp/T/Lv8yN7Jw84/entitlements_plistHKSGvZRQ /var/folders/6m/djd59_8n3x7f1v0x1ww2t_j80000gp/T/Lv8yN7Jw84/Payload/gitlab-ci-test.app failed with error 1. Output: iPhone Distribution: My company Ltd.: no identity found
```

**Comment by KrauseFx** [comment]
That's a tool that is built-in into Xcode. I'll take a look, maybe we can patch that too /cc @fabiomassimo :+1:

**Comment by KrauseFx** [comment]
You can take a look at the [code signing guide](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) to update your project to make this work :+1:

**Comment by Gimungagap** [comment]
Actially the problem is:
What I write and what is passed to codesign util:
```
iPhone Distribution: 'My company' Ltd.
iPhone Distribution: My company Ltd.
```
See the difference? The quotes are removed somewhere inside gym or one of its components. 
I didn't understand, you mean patching codesign itself or something inside gym that uses it?

For now I found a solution by use of update_project_provisioning but I'm afraid of using it because it translates project into JSON format. It would be much better to sign builds right from gym.

**Comment by fabiomassimo** [comment]
The way `codesign` tool takes the scene is through an ad hoc patched version of PackageApplication, a Perl script used by Xcode under the hood when exporting an IPA from an archive.

The quotes are removed indeed but I'm not sure that could actually be the problem.

@Gimungagap why do you specify the codesign identity to `gym`? Will it suit you to just specify it in the project build settings?

@KrauseFx not sure we need a new patch for this. After all the error doesn't truncate the certificate name : ```Program /usr/bin/codesign returned 1 : [iPhone Distribution: My company Ltd.: no identity found ```

**Comment by Gimungagap** [comment]
My goal is Fastlane usage by CI on several build nodes so I'd like to use commited provisioning profile because it seems to be easier to maintain. 
I saw `sigh` util but didn't like it because as I understood the idea, the profiles are generated and downloaded each time. Also I couldn't find options for inhouse distribution.

I found a solution by using `resign` tool. It doesn't remove quotes and does the work well. I guess, the issue can be closed. Thank you.

**Comment by KrauseFx** [comment]
@Gimungagap `sigh` only creates the profile if it doesn't exist yet. If it's there it gets downloaded. Of course `sigh` also supports Enterprise Profiles, it's very clearly shown on the landing page: https://github.com/krausefx/sigh#features
