### ISSUE TITLE
unable to toggle beta test flight

### ISSUE THREAD

**Issue by moses-gangipogu** [KrauseFx/fastlane#543]
`Sorry, we have to wait for iTunesConnect, since it's still processing the uploaded ipa file
If this takes longer than 45 minutes, you have to re-upload the ipa file again.
You can always open the browser page yourself: 'https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/972066031/pre/builds'
Passed time: ~47 minute(s)`

and this keeps on going the app is update to iTunes connect but i am unable to toggle the button 
TestFlight Beta Testing

lane select `ios beta`

**Comment by KrauseFx** [comment]
If you want to upload builds to TestFlight I recommend using the `pilot` action instead, more information `fastlane action pilot` :+1:

**Comment by edwardvalentini** [comment]
the example Fastfile shows deliver... is there an example to use pilot in the Fastfile?

**Comment by KrauseFx** [comment]
I just pushed an update of `deliver`, please update to `0.13.2` using `sudo gem update deliver`

I'm working on a brand new version of `deliver` that uses `spaceship` to communicate with iTunes Connect (you can follow the progress here: https://github.com/KrauseFx/deliver/pull/259), in the mean-time please try the latest release and let me know if that works for you :+1:

**Comment by moses-gangipogu** [comment]
sure thank you

**Comment by edwardvalentini** [comment]
so should we be using deliver or pilot in the Fastfile?

**Comment by KrauseFx** [comment]
@edwardsdl I know the current documentation is not 100% clear in that regard. For TestFlight build uploads please use `pilot`, for App Store builds + metadata use `deliver`
