### ISSUE TITLE
Recommendations on how to share custom actions

### ISSUE THREAD

**Issue by pmhood** [KrauseFx/fastlane#544]
Hi, I'm looking into how we can share custom actions across various apps so that I can make updates in one central location. I'm thinking I need to put the actions in a separate repo and clone that using the "sh" action?  Has anyone done this before?

Thanks!

**Comment by KrauseFx** [comment]
Something like that is already built in:
```
fastlane action import_from_git
```

You put the `Fastfile` (can be empty) and the `actions` folder on any of the repos (can be its own repo). 

The action will fetch the latest version :+1: `fastlane` tools are deployed using `fastlane` too and use this technique: https://github.com/KrauseFx/deliver/blob/master/fastlane/Fastfile

Let me know if that helps :+1:

**Comment by pmhood** [comment]
Thanks, I'll give it a shot and reopen if necessary!
