### ISSUE TITLE
update_fastlane

### ISSUE THREAD

**Issue by RomainBoulay** [KrauseFx/fastlane#545]
Hey,

Is there a difference between `update_fastlane` and `gem update fastlane` ?

Cheers,
Romain

**Comment by KrauseFx** [comment]
Hey,

`update_fastlane` is an action you can add to your `Fastfile` to automatically update `fastlane` if required, while `gem update fastlane` is executed by you manually. 

Does that make sense?

**Comment by RomainBoulay** [comment]
Sure but my question is more : is the result of both command identical?

**Comment by KrauseFx** [comment]
It should be, yes.

**Comment by RomainBoulay** [comment]
Thanks

**Comment by KrauseFx** [comment]
:+1:
