### ISSUE TITLE
In-App Purchase

### ISSUE THREAD

**Issue by guidev** [KrauseFx/fastlane#550]
Is it possible to create and/or manage In-App Purchases using fastlane?

**Comment by KrauseFx** [comment]
That's not possible right now, but would be part of the [deliver](https://github.com/KrauseFx/deliver) project.

**Comment by guidev** [comment]
Great!

**Comment by KrauseFx** [comment]
Closing in favour of https://github.com/KrauseFx/deliver/issues/35, please subscribe to https://github.com/KrauseFx/deliver/issues/35
