### ISSUE TITLE
is there documentation on how this could be used with post-build scripts in an Xcode Bot?

### ISSUE THREAD

**Issue by skydivedan** [KrauseFx/fastlane#555]
I just got my projects building with Xcode Server. I've got a handful of bots working, and I like the web page that shows the list of projects, and the data about the warnings, code-coverage, etc.

Is there documentation about how some fastlane features could be used in a post-build script of an Xcode Bot?

I was thinking some things, like changing the signing of an app from ad-hoc to distribution or something. Or posting to slack, or just a small subset of operations that could be performed _after_ the app is built?

**Comment by czechboy0** [comment]
Hi @skydivedan, I actually wrote an article on scripts in Xcode Server and used fastlane as an example: http://honzadvorsky.com/articles/2015-08-17-17-30-xcode_server_tutorials_3_prebuild__postbuild_scripts/ Is this what you're looking for?

**Comment by skydivedan** [comment]
yes, sorry about that. I should've read more closely on that.
