### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by souravray** [KrauseFx/fastlane#559]
I did
```
 geme install fastlane
```
but it got stuck here forever
```
GET https://rubygems.org/quick/Marshal.4.8/dotenv-1.0.0.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/dotenv-1.0.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/dotenv-1.0.1.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/dotenv-1.0.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/dotenv-1.0.2.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/dotenv-1.0.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/dotenv-2.0.0.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/dotenv-2.0.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/dotenv-2.0.1.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/dotenv-2.0.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/dotenv-2.0.2.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/dotenv-2.0.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/aws-sdk-1.0.0.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/aws-sdk-1.0.0.gemspec.rz
```
Looks like some kind bad dependency. 

Disclaimer: I'm not a Ruby guy

**Comment by souravray** [comment]
md fix

**Comment by KrauseFx** [comment]
Is that the complete output? Could you run `ruby -v`? Did you install any other ruby environment using `homebrew`, `rbenv` or `rvm`?

**Comment by KrauseFx** [comment]
The output was generated by appending `--verbose` right?

**Comment by souravray** [comment]
yes I used --verbose. The complete output is just an infinite log of the same o/p.
Ruby version output looks like bellow
```
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```
never set any other ruby environment using homebrew, rbenv or rvm kowingly.

**Comment by KrauseFx** [comment]
@souravray Have you tried letting the `install` command run for a longer time? Are you connected to a fast internet connection?

**Comment by souravray** [comment]
@KrauseFx I tried letting the install run for good 30-45min on a 100 MBPS connection.

**Comment by souravray** [comment]
@KrauseFx tried to run installation using a different connection (intact slower than the earlier one), and it was successful. So it was a network problem :)

**Comment by akki7017** [comment]
Facing this issue since few hours. At first i thought the process is really long then came across this issue. I have tried on a 100 Mbps and 10 Mbps connections. both working perfectly. How to proceed now?

I am also not a ruby guy! :)

**Comment by KrauseFx** [comment]
@akki7017 It just takes very long, make sure to use the `--verbose` flag

**Comment by akki7017** [comment]
@KrauseFx  I tried again and again and it worked. Took only 10 minutes. on 3G connection. Thanks.

There were many warnings of "302 Moved temporarily".
