### ISSUE TITLE
Using fastlane with multiple schemes

### ISSUE THREAD

**Issue by bkrijgsman** [KrauseFx/fastlane#563]
Hi,

Is it possible to use fastlane with multiple schemes? I've searched the documentation and tried some different things, but it couldn't find the answer. Maybe i have to create the deliver file each time i want to upload by myself?

I'm using the same xcodeproject for multiple apps (and they have different app ID's). 

Thank you for your help!

Regards,
Bas

**Comment by KrauseFx** [comment]
Hi Bas,

Does this guide help you? https://github.com/KrauseFx/fastlane/blob/master/docs/FAQs.md#multiple-targets-of-the-same-underlying-app

In general @joshdholtz is an expert in that field :+1: 

Also, check out this example `fastlane` setup: https://github.com/fastlane/examples/tree/master/SunApps

**Comment by joshdholtz** [comment]
I am an expert in that field :grin: That FAQ should be enough but let me know if you have any other questions on it :blush:

**Comment by KrauseFx** [comment]
@joshdholtz Is there anything different between schemes and targets when using this setup?

**Comment by joshdholtz** [comment]
@KrauseFx Depends on how you have your Xcode project setup :innocent: I, personally, just keep `Debug` and `Release` as targets for all my different schemes so I never have to set that in my `.env` files

**Comment by bkrijgsman** [comment]
Ah thats a great example thank you! I'll try to make it work ;)

**Comment by KrauseFx** [comment]
@bkrijgsman Great to hear :+1: 

> I've searched the documentation and tried some different things, but it couldn't find the answer.

So where would you expect this part of the documentation? Anything I can improve to make it easier for new users?

**Comment by bkrijgsman** [comment]
A link to the SunApps example :)

**Comment by bkrijgsman** [comment]
I successfully used the tools of fastlane and all the functions with multiple schemes.

Only one strange thing is happening: i can't upload anymore.

I got the following error message:

Return status of iTunes Transporter was 1: ERROR ITMS-4064: "File extension of file '7831df527cc49504cd3b301167effc05' is invalid for this software; use 'zip,ipa' instead."

I opened the .itmsp file in the /tmp/ folder. There are two files inhere:
-7831df527cc49504cd3b301167effc05
-metadata.xml

Does somebody know if this is normal?

**Comment by KrauseFx** [comment]
`7831df527cc49504cd3b301167effc05`, that's odd, it should be `7831df527cc49504cd3b301167effc05.ipa`.

Did this work before? Are you using `gym` with `deliver`?

**Comment by bkrijgsman** [comment]
Yes i do. If i change the name of the output ipa (instead of ./.ipa --> test.ipa) this bug is somehow fixed.

**Comment by KrauseFx** [comment]
So does it work now in an automated manner? Or do you need to manually update it?

**Comment by bkrijgsman** [comment]
It's the automated. I had some problems with the code signing.
I used --xcargs PROVISIONING_PROFILE = "{UUID}" to automatically select the right profile.

I used this script to find the UUID:
def profile_uuid(provisioning_profile_path)
  profile_contents = File.open(provisioning_profile_path).read
  profile_contents = profile_contents.slice(profile_contents.index('<?'), profile_contents.length)
  doc = Nokogiri.XML(profile_contents)
  return doc.xpath('//key[text()="UUID"]')[0].next_element.text
end
