### ISSUE TITLE
Podfile in a different folder

### ISSUE THREAD

**Issue by xfreebird** [KrauseFx/fastlane#565]
Hi,

I'm trying to figure out how can I tell fastlane to run cocoapods (e.g. pod install) in different folder than the current location.
By default it is expecting it to find in the current location.

Any pointers would be helpful.

Cheers,
Nicolae

**Comment by Liquidsoul** [comment]
Hi @xfreebird 
From the [current implementation](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/install_cocoapods.rb#L5-L18) I do not think it's possible right now. You need to have your `Podfile` located alongside your `fastlane` folder.

However, note that I may be missing some clever Ruby trick :art:

**Comment by KrauseFx** [comment]
@xfreebird Correct, you can easily solve this using some very basic Ruby, basically you add this to your `Fastfile`

```ruby
lane :beta do
  ...
  Dir.chdir("my/folder") do
    cocoapods
  end
  ...
end
```

**Comment by xfreebird** [comment]
Thanks @KrauseFx, I think in this case it would be reasonable to add an option to the cocoapods action.
Something similar to what there is in TavisCI,
podfile, that would point tot the location of the Podfile.
If not defined then one from the current location would be used. 

In meantime I could just use the basic Ruby code.

Cheers,
Nicolae

**Comment by KrauseFx** [comment]
:+1:

**Comment by Liquidsoul** [comment]
@xfreebird I'll try to work on that feature today 🔧

**Comment by xfreebird** [comment]
@Liquidsoul thanks !

**Comment by Liquidsoul** [comment]
@xfreebird : the `podfile` option is available in version 1.25.0 of `Fastlane` :rocket:

**Comment by xfreebird** [comment]
Thanks !

**Comment by KrauseFx** [comment]
:rocket:
