### ISSUE TITLE
Support the resign command of Sigh

### ISSUE THREAD

**Issue by barrettj** [KrauseFx/fastlane#58]
It'd be nice if we could use the resign command of sigh without having to call the command manually with system.

**Comment by KrauseFx** [comment]
Sorry for not answering earlier. Absolutely, I totally agree. This should be fixed once we decided how to further work on the API of all tools: https://github.com/KrauseFx/fastlane/issues/45

**Comment by KrauseFx** [comment]
Implemented thanks to @lmirosevic: https://github.com/KrauseFx/fastlane/pull/94 :+1: 

Expect a new release soon.
