### ISSUE TITLE
Using crashlytics and settings notifications to "NO" or false, triggers notifications

### ISSUE THREAD

**Issue by natanrolnik** [KrauseFx/fastlane#583]
Using the latest fastlane (v. 1.25.0), after building the app with gym, I call the following:

```
crashlytics(groups: "Internal", notifications: "NO")
```

Strangely, I end up receiving the e-mail notifications (and the groups parameter works as expected). Am I doing something wrong here, or maybe it's a bug?

**Comment by KrauseFx** [comment]
Could you try passing a boolean instead?

```ruby
crashlytics(notifications: false)
```

**Comment by KrauseFx** [comment]
Did some part of the documentation state to use `"NO"`?

**Comment by natanrolnik** [comment]
I just tried using a boolean now, and it fired the emails.

The documentation [here](https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#crashlytics-beta) just mentions about notifications, without specifying parameters. So I checked the crashlitycs.rb [action these lines](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/crashlytics.rb#L29-L43) and concluded that I can use string as a parameter.

**Comment by KrauseFx** [comment]
I worked on an updated version of the `crashlytics` action - will push an update later today!

**Comment by KrauseFx** [comment]
Sorry it took so long.

**Comment by natanrolnik** [comment]
Fantastic, thanks for fixing it!
What exactly was the problem there?

**Comment by KrauseFx** [comment]
I don't know I just rewrote the whole integration :wink:

**Comment by KrauseFx** [comment]
Could you update to the latest release and make sure it works as expected? :+1:

**Comment by natanrolnik** [comment]
Something is failing for me, so I'm not getting to the crashlytics action. Opened an issue here https://github.com/fastlane/gym/issues/104

**Comment by KrauseFx** [comment]
So we can close this issue now, right?

**Comment by natanrolnik** [comment]
Yay, the new action worked like a charm, without notifications 😃
Viva Felix!

**Comment by KrauseFx** [comment]
:rocket:
