### ISSUE TITLE
sh helper hang after update from 1.22 to 1.25

### ISSUE THREAD

**Issue by rrecio** [KrauseFx/fastlane#586]
It was working fine before updating :(

<img width="1440" alt="screen shot 2015-09-08 at 10 55 25 pm" src="https://cloud.githubusercontent.com/assets/52694/9751573/dc746e0e-567c-11e5-87db-0ec4380addbf.png">

**Comment by rrecio** [comment]
I run it as 

`ENV['DELIVER_WHAT_TO_TEST'] = sh("git log --oneline #{version_number}-1..HEAD")`

**Comment by KrauseFx** [comment]
Thanks for reporting, I'm aware of this issue and hope to push a new version today.

**Comment by KrauseFx** [comment]
I just pushed a new version, please let me know if that works for you :rocket:

**Comment by rrecio** [comment]
@KrauseFx yeah it woked :+1:  thanks.
