### ISSUE TITLE
set_github_release keeps reporting release on tag already exists

### ISSUE THREAD

**Issue by ksm** [KrauseFx/fastlane#587]
`set_github_release` has stopped working for me as expected for two of my previous fastlane deployments.

What my lane does:
1) `commit_version_bump`
2) `add_git_tag tag: v1.0`
3) `push_to_git_remote`
4) `set_github_release` where I pass `v1.0` to `tag_name` parameter

This results in an error in the `set_github_release` step:
`Release on tag v1.0 already exists!`

A while ago these steps worked as expected, but since a fastlane version upgrade (I don't remember which) I'm getting that error. I've already tried skipping step number 2, since `set_github_release` documentation says it will create the tag if it doesn't exist, but that leads to the very same error.

I've checked and the `v1.0` tag (just an example) did not ever exist in my local or remote repo, so this error doesn't make sense to me.

cc @czechboy0

**Comment by KrauseFx** [comment]
I actually ran into the same issue a few days ago, as seen here: https://github.com/KrauseFx/fastlane/issues/575

Have you updated to the latest version of fastlane?

**Comment by KrauseFx** [comment]
Let's move further discussion to https://github.com/KrauseFx/fastlane/issues/587

**Comment by ksm** [comment]
Thanks. Updating now. Will let you know if it continues.

**Comment by KrauseFx** [comment]
Sorry, wrong link before, I mean https://github.com/KrauseFx/fastlane/issues/575. Please subscribe to the other issue or add a comment to join the discussion :+1:
