### ISSUE TITLE
After Transporter is finished, fastlane says I do not have access to the apps.

### ISSUE THREAD

**Issue by rrecio** [KrauseFx/fastlane#593]
It happened twice.

I'm using El Captain GM + Xcode 7 GM + fastlane 1.25.1

![fastlane error](https://cloud.githubusercontent.com/assets/52694/9831886/ba3a2274-593e-11e5-97cc-4f41862e5bcc.png)

**Comment by KrauseFx** [comment]
Sorry, this is a problem of `deliver`, if it's okay to only upload the builds and not submit them for review, feel free to use the skip_deploy action.

I'm working on a new version of `deliver`, which will fix this issue: https://github.com/KrauseFx/deliver/pull/259

**Comment by rrecio** [comment]
Actually, what matter for me most is filling up "What To Test"

**Comment by KrauseFx** [comment]
Do you want to distribute builds to your beta testers? If so, please switch to [pilot](https://github.com/fastlane/pilot)

**Comment by rrecio** [comment]
Thanks. I'll do it

**Comment by KrauseFx** [comment]
Cool :+1: For App Store and metadata you can use `deliver`
