### ISSUE TITLE
Multiple target or Multiple branded app

### ISSUE THREAD

**Issue by ianwhite2** [KrauseFx/fastlane#597]
Hi @KrauseFx 
First of all this tool has surely saved my lots of time !! Thanks for this awesome tool.

How can I run multiple scheme in a lane means If one lane is completed it should automatic start the other lane which has different scheme 

Any guidance for this ?

Thanks

**Comment by truth3** [comment]
Hey Ian, if you want to keep separate lanes you can pass something like this through the command line.

fastlane lane1 && fastlane lane2

Otherwise, you can
![screen shot 2015-09-14 at 9 05 47 am](https://cloud.githubusercontent.com/assets/7986768/9850315/d0f28588-5abf-11e5-9bca-d94ccd0d42c9.png)
 just call gym several times within the same lane and pass in a different scheme in each one

**Comment by KrauseFx** [comment]
@ianwhite2 I assume you have more than a few apps you want to run through, right?

You can easily do something like this in your `Fastfile`:

```ruby
["Scheme1", "Scheme2", "Scheme3"].each do |scheme_name|
  gym(scheme: scheme_name)
end
```

Also, check out [this guide](https://github.com/KrauseFx/fastlane/blob/master/docs/FAQs.md#multiple-targets-of-the-same-underlying-app) about having multiple targets/schemes

**Comment by KrauseFx** [comment]
@truth3 You can use the GitHub flavored markdown to add code blocks, so you don't have to create and upload screenshots :smiley:

**Comment by truth3** [comment]
Thanks @KrauseFx , you are always looking out for everyone's best interest :+1:

**Comment by ianwhite2** [comment]
@KrauseFx thanks ,you are the best ,Yes I have multiple target/Scheme and m new to ruby and this so sorry for the noob question.
["Scheme1", "Scheme2", "Scheme3"].each do |scheme_name|
  gym(scheme: scheme_name)

this will just create the build as per my understanding but how can I taking snapshot and deliver the ipa using this for loop ?

**Comment by xfreebird** [comment]
Hi @ianwhite2, I think you could just add the deliver and snapshot in that block:

```ruby
["Scheme1", "Scheme2", "Scheme3"].each do |scheme_name|
  gym(scheme: scheme_name)
  snapshot
  deliver
end
```

**Comment by ianwhite2** [comment]
@xfreebird  but how to i pass the scheme name to snapshot file ?,or does it automatically takes care of it

**Comment by xfreebird** [comment]
You could create a Snapfile file per scheme:

```
fastlane/Scheme1/Snapfile
fastlane/Scheme2/Snapfile
```

and in the ```Fastfile```:

```ruby
["Scheme1", "Scheme2", "Scheme3"].each do |scheme_name|
  gym(scheme: scheme_name)
  snapshot(snapshot_file_path: "#{scheme_name}/Snapfile"
  deliver
end
```

May be there are easier ruby tricks to pass the Scheme name to snapshot, but I'm not aware of it.

**Comment by KrauseFx** [comment]
Even better:

```ruby
["Scheme1", "Scheme2", "Scheme3"].each do |scheme_name|
  gym(scheme: scheme_name)
  ENV["SCHEME"] = scheme_name
  snapshot
  deliver
end
```
and in your `Snapfile`:
```ruby
scheme ENV["SCHEME"]
```

This will use an environment variable to pass the scheme from `fastlane` to the `Snapfile`, so you only need one `Snapfile` :rocket:

**Comment by xfreebird** [comment]
:+1:

**Comment by ianwhite2** [comment]
Thanks a  lot @KrauseFx  and @xfreebird - This tool is great and so you guys are :). I will also contribute to this community soon :)

**Comment by KrauseFx** [comment]
:smiley:

**Comment by mkeiser** [comment]
Hi, my projects consists of a mac app with an iOS companion app, which I want to build and release in tandem. While I saw various ways I can build multiple targets from a single lane, I didn't see a way to make this work with different platforms. So my questions are:

1) Can I dynamically switch the "current" platform?
or
2) Can I specify the platform for "sub-lanes"?
or
3) Is the platform even important, except for sanity checks for certain actions that run only on one platform (i.e. TestFlight)?

**Comment by KrauseFx** [comment]
@mkeiser This might be more complex and will require advanced Ruby knowledge

**Comment by ikermart** [comment]
Any idea on how to do this for Android and multiple flavors?
I would like to download all metadata files, of my 50 different flavors app.
I know that "fastlane init" creates the folders for the specific app, how can I do with 50 different? and add different names for each folders?
Thank you in advance!

**Comment by sandeee1928** [comment]
How can I get all the schema from my xcode project and using "for loop" I want to run the "gym(scheme: scheme_name)" command?

**Comment by TKBurner** [comment]
HI @sandeee1928 You'll need to use ENV to properly do this. Thanks!

**Comment by KrauseFx** [comment]
For people coming from Google, check out the [Guide to use fastlane for apps with multiple targets](https://docs.fastlane.tools/faqs/#multiple-targets-of-the-same-underlying-app).
