### ISSUE TITLE
Why can't install fastlane

### ISSUE THREAD

**Issue by ChenJing000** [KrauseFx/fastlane#598]
$ sudo gem install fastlane --verbose
GET https://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
ERROR:  Could not find a valid gem 'fastlane' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/latest_specs.4.8.gz)
GET https://rubygems.org/prerelease_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.org/specs.4.8.gz
302 Moved Temporarily

**Comment by xfreebird** [comment]
Hi @ChenJing000, is that always reproducible ? 
On my side all works just fine. 
Try using a different internet connection and see if that helps.

**Comment by ChenJing000** [comment]
This issue has been solved by changing the mirror, but it finally failed as issue 599: Can't solve dependency problem between fastlane and deliver

**Comment by ChenJing000** [comment]
When I git clone the "deliver", during installation of deliver, it failed by dependency on fastlane, so it is a cycling dependency between fastlane and deliver!

**Comment by xfreebird** [comment]
From http://ruby.taobao.org/index_en.html: 

```Due to network issues in China (you understand)，there are intermittent connection failures when accessing to rubygems.org and the files hosted on Amazon S3.```

It could be that you got a corrupted cache or if you are using http://ruby.taobao.org mirror, it hasn't finished to sync all gems.

**Comment by KrauseFx** [comment]
Thanks @xfreebird for jumping in.

Closing in favor of https://github.com/KrauseFx/fastlane/issues/599
