### ISSUE TITLE
Can't solve dependency problem between fastlane and deliver

### ISSUE THREAD

**Issue by ChenJing000** [KrauseFx/fastlane#599]
During installation of "gem install fastlane", finally it got:

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires deliver (< 1.0.0, >= 0.13.2); frameit requires deliver (> 0.3)

I also cannot install deliver alone, what should I do?

My Email is: jing000@gmail.com. I am waiting for the solution anxiously, could you please help me solve this problem? thanks!

Jing

**Comment by xfreebird** [comment]
@ChenJing000 may be this is somehow related to your issue #598 ? Have you solved #598 ?

**Comment by ChenJing000** [comment]
When I turned to clone and install deliver, it finally failed as it depend on fastlane, what should I do?

**Comment by xfreebird** [comment]
Try removing all gems and start from beginning.

```bash
sudo gem uninstall --all
```

**Comment by ChenJing000** [comment]
sudo gem uninstall --all
Password:
ERROR:  While executing gem ... (Gem::CommandLineError)
    Please specify at least one gem name (e.g. gem build GEMNAME)

**Comment by xfreebird** [comment]
Try this one
```shell
for i in `gem list --no-versions`; do sudo gem uninstall -aIx $i; done
```

**Comment by ChenJing000** [comment]
After uninstalling, I gem install fastlane again and encountered the same issue,: Unable to resolve dependencies: fasten requires deliver (<1.0.0, >= 0.13.2), framed requires deliver (>0.3)

**Comment by ChenJing000** [comment]
After uninstalling, I gem install fastlane again and encountered the same issue,: Unable to resolve dependencies: fastlane requires deliver (<1.0.0, >= 0.13.2), frameit requires deliver (>0.3)

**Comment by ChenJing000** [comment]
I  failed at this stage:

...
GET http://rubygems-china.oss.aliyuncs.com/quick/Marshal.4.8/unf_ext-0.0.7.1.gemspec.rz
200 OK
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires deliver (< 1.0.0, >= 0.13.2); frameit requires deliver (> 0.3)

**Comment by xfreebird** [comment]
Hi @ChenJing000  just to make sure few things:

- which ruby are using (e.g. are you using system ruby or a different one installed through rvm or other means) do you have ```.rvm``` in you ```$HOME``` folder ?
- what version of OS X are you using ?

**Comment by ChenJing000** [comment]
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

I am using Mac OS X 10.10.5

**Comment by xfreebird** [comment]
You said before you had to change the ruby gem mirror, how did you change it ?

**Comment by xfreebird** [comment]
what does ```gem list``` return for you ?

**Comment by ChenJing000** [comment]
$ gem sources --remove https://rubygems.org/
$ gem sources -a http://ruby.taobao.org/

This way I changed the mirror into local URL ruby.taobao.org

**Comment by ChenJing000** [comment]
$ gem list

*** LOCAL GEMS ***

aws-sdk (1.65.0)
aws-sdk-v1 (1.65.0)
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
commander (4.3.5)
dotenv (2.0.2)
faraday (0.8.10)
faraday_middleware (0.10.0)
highline (1.7.3)
io-console (0.4.2)
json (1.8.3, 1.7.7)
libxml-ruby (2.6.0)
mini_portile (0.6.2)
minitest (4.3.2)
multipart-post (1.2.0)
net-sftp (2.1.2)
net-ssh (2.9.2)
nokogiri (1.5.6)
plist (3.1.0)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
rubyzip (1.1.7)
security (0.1.3)
shenzhen (0.14.2)
sqlite3 (1.3.7)
terminal-table (1.4.5)
test-unit (2.0.0.0)

**Comment by ChenJing000** [comment]
Another colleague who has cloned the latest version of code yesterday has luckily gone through the installation, and but when he try to run "deliver", it has succeeded once (uploaded meta data successfully without ipa), but always encountered this error (he didn't change any configuration between the time of success and the failure):
[17:16:53]: Logging into iTunesConnect
[17:17:20]: Looks like your login data was correct, but you do not have access to the apps.
error: Error logging in user zhangxinyi0104@163.com with the given password. Make sure you entered them correctly..

**Comment by xfreebird** [comment]
About your issue with sudo ```gem install fastlane``` it is related to your ruby setup and mirror. The mirror you are using is replicating the official ruby gems repository.

At least it is working flawless for me. 

The iTunes part, that is a different issue, please open a new issue or find and existing one.
Nevertheless I suppose the userzhangxinyi0104@163.com is not allowed to access apps in iTunesConnect that is what it says. If you login into iTunesConnect with those credential can you access apps. ?

Cheers,
Nicolae

**Comment by ChenJing000** [comment]
About the issue of logging iTunesconnect, yes the account works always, that's what we have been using for app store, and it can pull all the information including the screenshots from the app store which were uploaded long time before we use fastlane, therefore it means this account/password is correctly entered into the config of fastlane.

**Comment by ChenJing000** [comment]
Finally the problem disappeared, don't know why. Thanks anyway!
