### ISSUE TITLE
Command ipa set by default sdk : iphoneos, which failed with watch app 2

### ISSUE THREAD

**Issue by myrddinus** [KrauseFx/fastlane#601]
I noticed that the command ipa set by default the sdk to "iphoneos". But watch os 2 need the sdk set to "watchos".
I need to remove the --sdk option to build my ipa.
On the shenzen repository : https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/commands/build.rb
we have this line:
@sdk = options.sdk || 'iphoneos'

There is a way to remove that ?

**Comment by KrauseFx** [comment]
Yes, please use the new tool called [gym](https://github.com/fastlane/gym) instead of `shenzhen` and let me know if that works for you :+1:

You'll be able to pass all kinds of parameters using `fastlane action gym`

**Comment by myrddinus** [comment]
I didn't have time to switch to gym, I'm actually using the 1.3 :) I'm going to migrate soon. So I used xcodebuild(...) to make the job. Thank you.
