### ISSUE TITLE
Beta Entitlement Error in iTunes Testflight

### ISSUE THREAD

**Issue by mehulmind123** [KrauseFx/fastlane#603]
I am getting following error on iTunes "To use TestFlight Beta Testing, build XX must contain the correct beta entitlement. For more information, see the FAQ."  while using following sequence of command.

	produce
	cert
	sigh(adhoc: true)
	ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
	gym
	ENV["PILOT_IPA"] = ENV["IPA_OUTPUT_PATH"]
	pilot(skip_submission: true)

Anyone can let me know which command should i use to prevent this error?

**Comment by KrauseFx** [comment]
Could you try deleting your provisioning profile and letting `sigh` create a new one for you?

**Comment by mehulmind123** [comment]
I tried it, but did not work.
However i have noticed log of sign and discovered, it is performing following steps every time, even if there is profile on folder.

Successfully logged in
[11:03:03]: Fetching profiles...
[11:03:13]: Found 1 matching profile(s)
[11:03:13]: Downloading provisioning profile...
[11:03:15]: Successfully downloaded provisioning profile...
[11:03:15]: Installing provisioning profile...

**Comment by KrauseFx** [comment]
Have you tried the same using the latest version of `gym`?

**Comment by mehulmind123** [comment]
Yes, I tried after updating gym also.

**Comment by mehulmind123** [comment]
Its working now. Cheers!

There was no update on fastlane, but i have updated gym and pilot separately and its working now,

Thanks

**Comment by KrauseFx** [comment]
Great to hear :+1:

**Comment by mehulmind123** [comment]
Started getting this same error once again. Now i am using gyn(export_method: "ad-hoc")

**Comment by KrauseFx** [comment]
You could try `gym(use_legacy_build_api: true)`

**Comment by mehulmind123** [comment]
Not worked, getting same error.

New iTunes Connect shows "Missing Beta Entitlement" on External Testing Status Column.

**Comment by mehulmind123** [comment]
I figured it out.
Issue coming because of i am using 'ad-hoc' as export_method, it works fine with 'app-store' as export_method.
