### ISSUE TITLE
Getting options in before_all

### ISSUE THREAD

**Issue by pbrooks** [KrauseFx/fastlane#604]
As simple as it sounds,
For my gym call in before_all, I'd like to pass in the project path from the command line.

The use of:
platform :ios do
  before_all do |options|

    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # increment_build_number

    gym(project:options[:project]) # Build your app - more options available

    # xctool # run the tests of your app
  end

Fails on the use of |options|

**Comment by KrauseFx** [comment]
Sorry, the `before_all` and `after_all` blocks don't support parameters right now. Instead, move shared code into a `private_lane` and call it from the other lanes.

Does this make sense?

**Comment by pbrooks** [comment]
I used envy parameters instead, fits my purpose

**Comment by KrauseFx** [comment]
Perfect :rocket:
