### ISSUE TITLE
import_from_git clone folder name collision 

### ISSUE THREAD

**Issue by xfreebird** [KrauseFx/fastlane#608]
Hi @KrauseFx could you please change the ```import_from_git``` action so that it would use a unique location when cloning. 

```
clone_folder = File.join("/tmp", "fl_clones", repo_name)
```

Cloning to the same location is prone to collision when running multiple ```fastlane``` instances. I would do it myself but it seems the master branch fails some git tests.

Thanks for this great tool ! :+1:

**Comment by KrauseFx** [comment]
:+1:
