### ISSUE TITLE
Issues building with fastlane in a Jenkins job

### ISSUE THREAD

**Issue by lemonkey** [KrauseFx/fastlane#609]
Not sure what exactly is going on, but the same fastlane lane that builds and archives an iOS app that is using Cocoapods (0.35 for iOS 7 support) from the command line fails to find the pod targets during the linking phase when executed in the context of a Jenkins job:

ld: library not found for -lPods-xxx

Has anyone else experienced this? There isn't that much special going on in terms of the gym command being used to build the app and it's fine from the command line. None of the other phases of the lane in Jenkins is a problem (bumping version, getting latest provisioning profiles, etc.).

I'm using the latest fastlane tools including the recent updates to gym from today and Xcode 7 GM/iOS 9 SDK/etc. (Jenkins is at v1.598).

**Comment by KrauseFx** [comment]
Is your scheme shared? Do you use the `cocoapods` action in `fastlane`?

**Comment by lemonkey** [comment]
The scheme is shared, but I'm not using a cocoapods action in fastlane as the Pods folder is under source control.

I did just confirm from a fresh repo clone that the xcodebuild command being issued by Fastlane does fail on its own if done on the command line similar to how it fails in Jenkins, but not when executed within Fastlane.

set -o pipefail && xcodebuild -workspace 'XXX.xcworkspace' -scheme 'XXX Beta' -configuration 'AppStore-Beta' -destination 'generic/platform=iOS' -archivePath '/Users/xxx/Library/Developer/Xcode/Archives/2015-09-21/org.xxx.XXX-Beta.AppStore-Beta.ad-hoc.5.7.2.61 2015-09-21 15.55.58.xcarchive' clean archive CODE_SIGN_IDENTITY='iPhone Distribution: XXX (xxxxxxxx)' | xcpretty

**Comment by lemonkey** [comment]
Ok I think I know what's happening. A certain script wasn't running ahead of time.

**Comment by fanyuRN** [comment]
I experienced the same problem, how to solve it ,can you explaint  it detailedly？

**Comment by TKBurner** [comment]
@fanyuRN Thanks for reaching out on this. Can you open a new issue if you are running into a problem? Thanks!

**Comment by fanyuRN** [comment]
@TKBurner  Thanks!I have resolved it

**Comment by TKBurner** [comment]
@fanyuRN Awesome! So glad to hear you are up and running!

**Comment by cdunkel** [comment]
@fanyuRN I'm running into this problem, too.  Can you share what you did to solve it?  Thanks!

**Comment by fanyuRN** [comment]
![455a12b1-0ca4-46a4-a418-b9304fc4bcf2](https://cloud.githubusercontent.com/assets/20810414/18235951/a21f3082-7353-11e6-925d-861fcf671411.png)
you should  modify your workspace,
