### ISSUE TITLE
[Feature] Allow uploading dSYM only for hockey app.

### ISSUE THREAD

**Issue by alliannas** [KrauseFx/fastlane#613]
Hi there,

this is a simple feature request :)

##### Feature request

According to the [hockey app docs](http://support.hockeyapp.net/kb/api/api-versions#upload-version) it is allowed to only upload the dSYM.

The HockeyAction should be able to be configured to allow that as well.

##### Reasoning behind the feature

You want to get crash reports for your live app (thats in the app store) BUT you don't want to supple the ipa.

###### The reason for **NOT** supplying the ipa

Someone downloads your app from the App Store. They will be able to extract the APP_ID string on HockeyApp.
Those hackers will then be able to download the beta by just take your App ID, integrate the Hockey App SDK in a simple Xcode project, and then update from this empty app to the latest beta.

This can be avoided by using their authentication feature but that is not always feasible.

##### Workaround

For the project I need this in I temporary added a new `hockey_dsym_only` action but I'd love to be able to do it properly by adding it to fastlane.

**Comment by alliannas** [comment]
The current stratgey I have is this:

```
     ipa_filename = options[:ipa]
        if options[:upload_dsym_only] == true
          ipa_filename = nil
        end

     response = client.upload_build(ipa_filename, values)
```

where `upload_dsym_only` is a new option, defaulting to `false`.

Any thoughts on this implementation before I do a PR?

**Comment by KrauseFx** [comment]
Simplified: :+1: 
```ruby
ipa_filename = options[:ipa]
ipa_filename = nil if options[:upload_dsym_only]
response = client.upload_build(ipa_filename, values)
```

**Comment by alliannas** [comment]
Thanks for the tip :)

**Comment by KrauseFx** [comment]
This is resolved now, right?

**Comment by alliannas** [comment]
Yes it is resolved :)

**Comment by yakimant** [comment]
Hi and thanks for the feature!

Can we make 'ipa' as an optional parameter?
If I'm truing `upload_dsym_only` now:
```ruby
  lane :deploy do |options|
    hockey(
      api_token:          'TOKEN',
      public_identifier:  'APP_ID',
      release_type:       '0',
      dsym:               'some.app.dSYM.zip',
      upload_dsym_only:   true,
      notes:              '',
      notify:             '0',
      status:             '1',
    )
  end
```
I got the following prompt:
```
[19:12:00]: --------------------
[19:12:00]: --- Step: hockey ---
[19:12:00]: --------------------
[19:12:00]: Starting with ipa upload to HockeyApp... this could take some time.
[19:12:00]: To not be asked about this value, you can specify it using 'ipa'
Path to your IPA file. Optional if you use the `gym` or `xcodebuild` action. For Mac zip the .app:
```

No gyp/ipa/xcodebuild was used in prior, ipa/dsym ere build on a different lane.
