### ISSUE TITLE
Use Apple's method of Verifying Xcode for `verify_xcode`

### ISSUE THREAD

**Issue by mattyohe** [KrauseFx/fastlane#615]
https://developer.apple.com/news/?id=09222015a

**Comment by KrauseFx** [comment]
Thanks, I'm already on it! :rocket:

**Comment by KrauseFx** [comment]
Done https://github.com/KrauseFx/fastlane/commit/dfb5c46d78c41c96a9fd8b24b5811374cbd9a84e
