### ISSUE TITLE
Deploy to Crashlytics Beta fails.

### ISSUE THREAD

**Issue by dtrenz** [KrauseFx/fastlane#62]
It appears that some fatal error happens when the Crashlytics plugin is initialized, but I can't seem to figure out anything else based on this error & stack dump. Help is greatly appreciated.

![image](https://cloud.githubusercontent.com/assets/639833/6258373/00851bf8-b796-11e4-9048-ee1817fab350.png)

**Comment by KrauseFx** [comment]
Does the same happen if you run [shenzhen](https://github.com/nomad/shenzhen) Crashlytics by itself?

**Comment by dtrenz** [comment]
I figured out the issue. I took ```crashlytics_path: './path', # path to your 'Crashlytics.framework'``` to mean the path to the folder where the framework exists, NOT the path to the framework itself.

**Comment by KrauseFx** [comment]
But the error message is wrong. It shouldn't say, that it can't find `say_error`

**Comment by dtrenz** [comment]
I assumed that meant that it was trying to call an error logging method that didn't exist so that it could report that actual error. I agree that this should be fixed.

I will submit a PR to at least clarify slightly the usage of the crashlytics_path param in the README example.
