### ISSUE TITLE
IPad “gem install bundler” invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by JustGr00ve** [KrauseFx/fastlane#627]
Hello every-time i run the command "gem install bundler" on my IPad i end up getting this message. ERROR: While executing gem ... (ArgumentError)
invalid byte sequence in US-ASCII

Please help me, I cant seem to find a way around this

**Comment by KrauseFx** [comment]
> Hello every-time i run the command "gem install bundler" on my IPad

on your iPad?

Anyway, just add this to your `~/.bash_profile `

```sh
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
```

**Comment by JustGr00ve** [comment]
![untitled111](https://cloud.githubusercontent.com/assets/11280701/10062186/09645868-622e-11e5-87ff-376d842e24af.png)

I don't really understand. I'm Kinda new to this and I was following a youtube video. But then i got that message and now i'm stuck.

**Comment by KrauseFx** [comment]
@JustGr00ve what YouTube video? What are you trying to do?

**Comment by JustGr00ve** [comment]
@KrauseFx https://www.youtube.com/watch?v=5Df3_UAqV1o, Trying to add metasploit to ipad

**Comment by KrauseFx** [comment]
Sorry, you're wrong here. This is a repository for `fastlane` a tool for iOS developers and has nothing to do with the YouTube video you linked. I'll close this issue :+1:
