### ISSUE TITLE
Run sh commands from the root folder

### ISSUE THREAD

**Issue by jschmid** [KrauseFx/fastlane#629]
I have a Makefile that contains predefined actions, and for now I don't want to translate them into a Fastlane action.

Therefore I tried to run:

    sh "make identifiers"

However, since Fastlane is executed from the `fastlane` folder, `make` does not find the `Makefile` and fails. One solution could be:

    sh "cd .. && make identifiers"

But I don't find it very pretty. My question is broader than just using `make`. Is there a way to run `sh` commands from the project root folder instead of the `fastlane` folder ?

**Comment by KrauseFx** [comment]
I'd use either one of the these solution:

- Move the `Makefile` into the `fastlane` folder
- You can use Ruby to go a folder up:

```ruby
lane :beta do
  Dir.chdir("..") do
    sh "make identifier"
  end
end
```

Sorry that this is not ideal, but this is not something I can change now, as people already use it with the current behavior.

**Comment by jschmid** [comment]
Alright! I wondered if I had missed something. I'll use the Ruby way then.

Thanks!
