### ISSUE TITLE
Slack integration does not format code blocks

### ISSUE THREAD

**Issue by philipengberg** [KrauseFx/fastlane#635]
New to fastlane (:heart: it); Not sure if this is the right place to open this issue.

When sending a message like:
```ruby
slack(
 message: "<!here|here>: New :ios: app  running `#{environment}` `#{api}` has been submitted to Crashlytics",
)
```
the backticks are also printed in slack and the text within is thus not formatted correctly.

**Comment by KrauseFx** [comment]
Thanks! I have experienced the same issue with markdown code in general (e.g. lists)

I'm not sure if that's a `fastlane` or Slack issue.

**Comment by philipengberg** [comment]
According to [this documentation](https://api.slack.com/docs/formatting#message_formatting) Salck *does* support markdown in API messages.

**Comment by KrauseFx** [comment]
Yes, already got the reply on Twitter @KrauseFx code blocks are supported with `code` or ```pre``` if you include "mrkdwn": true in your request body. https://t.co/iypxUHAtDD

**Comment by KrauseFx** [comment]
Yes, already got the reply on Twitter https://twitter.com/SlackAPI/status/648518636647378944 :+1:

**Comment by philipengberg** [comment]
Beautiful :+1:

**Comment by KrauseFx** [comment]
Fixed https://github.com/KrauseFx/fastlane/commit/ec149c455f2912b31d1e79b41190fd1af6c6e235. This will be in the next release
