### ISSUE TITLE
Hockey: upload just the dSYM?

### ISSUE THREAD

**Issue by vendruscolo** [KrauseFx/fastlane#636]
Shenzhen allows us to upload just the dSYM to HockeyApp. I plan to use HockeyApp for crash reports (no app distribution), so skipping the ipa upload would make the process faster.
I don't know if fastlane already supports this (if it does, how can I set it up?), but if it doesn't it would be a welcome addition 😉
Perhaps [this Shenzhen issue](https://github.com/nomad/shenzhen/issues/43) can help.

**Comment by Liquidsoul** [comment]
Hi @vendruscolo 
Fastlane does not support this out of the box yet but maybe this is being addressed because this feature was already requested in #613

**Comment by Liquidsoul** [comment]
Seems like #638 contains the feature. Will be available in the next Fastlane release :rocket:

**Comment by vendruscolo** [comment]
👍 fantastic news.

Thank you.

**Comment by KrauseFx** [comment]
Yes, this will be in the next release :+1: I'll close this issue already, feel free to re-open if you run into any problems.
