### ISSUE TITLE
Submit existing iTC builds to Review instead of uploading a new one

### ISSUE THREAD

**Issue by bassrock** [KrauseFx/fastlane#64]
So when looking at the Fastane configuration, i am not sure if it makes sense with the new Apple TestFlight. The new Apple Testflight lets you take a beta build and then make it the live build. 

I propose the beta flow uploads the correct metadata for what the new version will be, with the snapshots and all. And then the App Store flow would basically just auto mark the beta upload to be the live version.

Thoughts, ideas?

**Comment by KrauseFx** [comment]
I agree, it would make sense to submit the same build for review, which you already had in TestFlight. 

How would we approach this? Right now, `deliver :testflight` will only upload the `ipa` file, and no metadata or screenshots.

Not sure, if there is a big advantage is submitting the same build?

**Comment by bassrock** [comment]
So i think the ```deliver :testflight``` should change so that it does include the metadata, because a test flight push now actually sets up the store page as it would normally.

Then when you do a ```deliver :appstore``` all that would happen is you would get a list of all the "active" builds in iTunes Connect that can be submitted and then you select the one to make app store official. This step would basically do no building or uploading, just parsing and letting you pick the option to make official.

**Comment by KrauseFx** [comment]
I'm not sure I completely agree. This would also mean, you have to use Apple TestFlight, which many people don't.

**Comment by bassrock** [comment]
Fair point. But I think this workflow situation should be supported. And for those that don't use test flight it should do the same like ur suggesting by using the same build somehow

**Comment by KrauseFx** [comment]
I'll close this issue for now, thanks for your feedback :+1:
