### ISSUE TITLE
warning: conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by sandman4sure** [KrauseFx/fastlane#643]
I get a lot of 
`/Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block`

As a (possible) result lots of times I will get errors like
gym: `No project/workspace found in the current directory`
snapshot: `No such file or directory - ./fastlane`

This didn't happen before the last big update.

**Comment by OJDee** [comment]
Similar issue, running fastlane beta, gets to the deliver step then

/Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block
[10:51:18]: You passed invalid parameters to 'deliver'.

...

[10:51:18]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.18.1/lib/fastlane_core/configuration/configuration.rb:52:in `block in verify_value_exists': Could not find option 'beta' in the list of available options

**Comment by maxbritto** [comment]
@OJDee : Deliver has received a major update to use spaceship and a some parameters have been changed. There is a migration guide to guide you through them : https://github.com/KrauseFx/deliver/blob/feature/spaceship/MigrationGuide.md

Regarding the main issue of the ticket I have it too since the last update :+1:

**Comment by josephlord** [comment]
I'm seeing the same issue although not when gym is the only thing in a lane. It is happening when preceded by:
```
     ensure_git_branch(branch: '(develop)|(master)')
     ensure_git_status_clean
     increment_build_number
```
Will try to narrow it down further.

**Comment by aylesm** [comment]
I'm seeing the same issue.  If I try to increment the build number and then call gym it causes issues.  

/Users/michaelayles/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block
/Users/michaelayles/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/credentials_manager-0.8.2/lib/credentials_manager/appfile_config.rb:31: warning: conflicting chdir during another chdir block

**Comment by OJDee** [comment]
@maxbritto thanks for the heads up. Even when I install spaceship I get the same issue - bear in mind I am calling fastlane not deliver, so having upgraded to latest version of fastlane I thought all it's components would have been updated too. Is there somewhere to just get all the latest version and have it just work through fastlane?

**Comment by davidattias** [comment]
I'm having the same issue when calling sigh...

**Comment by maxbritto** [comment]
@OJDee : You are calling fastlane and fastlane is calling deliver for you (probably in one of your fastfile lanes). Everything has probably been updated correctly and that is why you must update you deliver configuration and the params that fastlane gives to deliver in the fastfile.

**Comment by dral3x** [comment]
Same here :+1:

**Comment by cdemiris99** [comment]
Also same issue.  Did fastlane init, then tried fastlane test.  The gym build works but fastlane fails in chdir to ./fastlane/

**Comment by KrauseFx** [comment]
Sorry everyone for introducing this issue. I just pushed a new version (https://github.com/fastlane/fastlane_core/issues/34), please update using `sudo gem update fastlane_core`

**Comment by KrauseFx** [comment]
And please let me know if that fixes your problem.

**Comment by josephlord** [comment]
Seems to work for me. Thanks for all your work. Sorry I didn't have time today to dig deeper into it to send you PR.

**Comment by KrauseFx** [comment]
Thanks for confirming @josephlord :+1:

**Comment by cdemiris99** [comment]
Fixed it for me as well. Thanks.

**Comment by KrauseFx** [comment]
Great, I'll close this issue for now :+1:
