### ISSUE TITLE
Deliver Option deliver_file_path fails

### ISSUE THREAD

**Issue by pkurzok** [KrauseFx/fastlane#644]
Hi,

I have multiple build targets. In fasten there used to be an option to specify my delivery file: deliver_file_path

Since I upgraded to Version 1.30.0 this option fails. Any workarounds?

Best regards
Peter

**Comment by KrauseFx** [comment]
Sure thing, please read the [release notes](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and follow the [Migration Guide](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

**Comment by KrauseFx** [comment]
Let me know if you have any specific questions or have troubles migrating to the new release.
