### ISSUE TITLE
Does Fastlane use any kind of cache?

### ISSUE THREAD

**Issue by jschmid** [KrauseFx/fastlane#645]
I am using Fastlane to run my tests in CircleCI.
I run into a problem when I try to update the project build number from a lane.

My `circle.yml` looks like:

```ruby
machine:
  xcode:
    version: "7.0"
dependencies:
  override:
    - bundle install --path=vendor/bundle # Will update Gemfile.lock
test:
    - bundle exec fastlane test
deployment:
  adhoc:
    branch: adhoc
    commands:
      - git diff # Shows the Gemfile.lock has changed
      - git checkout -- Gemfile.lock
      - git diff # Shows the file has been cleared
      - bundle exec fastlane adhoc # Fails because of the dirty file
```

You can see that I install Fastlane using a Gemfile. I run my `test` lane without any problem.
The next step is to deploy if the tests are green. My lane looks like:

```ruby
private_lane :build do
  increment_build_number
  commit_version_bump xcodeproj: 'project.xcodeproj'
  gym
  add_git_tag
  push_to_git_remote
end
```

The build number is incremented, but the `commit_version` fails. The log from CircleCI looks like:

    [06:42:00]: [SHELL COMMAND]: git diff --name-only HEAD
    [06:42:00]: [SHELL]: Gemfile.lock
    [06:42:00]: [SHELL]: project.xcodeproj/project.pbxproj
    [06:42:00]: [SHELL]: project/Supporting Files/Info.plist

Apparently the Gemfile.lock is modified, although if you look at the `circle.yml` file, I make sure the file is discarded. 

> Does Fastlane use a cache that would make it output wrong information?

Thanks

**Comment by KrauseFx** [comment]
Sorry, not that I know about. It's probably somehow related to flushing the stdout. I think @andrewpage recently submitted a pull request https://github.com/fastlane/fastlane_core/pull/22

**Comment by jschmid** [comment]
You mean that the `git diff --name-only HEAD` has to do something with where the logs are output? 

I don't see where it relates to the "wrong" git status

**Comment by KrauseFx** [comment]
Sorry, I seem to have misunderstood the problem you're having. You didn't share your complete output when running `fastlane`, in particular not the stack trace the the log that was shown before.

**Comment by jschmid** [comment]
Here is the complete log: https://gist.github.com/jschmid/2d9d05648353aecc9ad6

Thank you for your help!

**Comment by jschmid** [comment]
Wow... that was an unexpected fix.

As it appears, the `bundle` command shipped with CircleCI is a bit outdated. 

When I ran my `bundle exec fastlane adhoc` command, Bundler updated the Gemfile.lock before running `fastlane adhoc`. It is related to [this issue](https://github.com/bundler/bundler/issues/3697).

I now update Bundler before running fastlane. The `Gemfile.lock` is not updated anymore and the command goes through. 

Big shout out to @kimh from Circle who found the culprit!

**Comment by KrauseFx** [comment]
:+1:
