### ISSUE TITLE
"Complex Fastfile example" omits creation of an *.ipa

### ISSUE THREAD

**Issue by dtrenz** [KrauseFx/fastlane#65]
Correct me if I'm wrong, but the ["Complex Fastfile example"](https://github.com/KrauseFx/fastlane#complex-fastfile-example) appears to omit the **ipa** action and will fail to deploy.

**Comment by KrauseFx** [comment]
Good point, I should add the `ipa` action to the example. Thanks for letting me know :+1:

**Comment by dtrenz** [comment]
Thanks for the quick response! :hamburger:
