### ISSUE TITLE
sigh and provisioning file download

### ISSUE THREAD

**Issue by mgrilloteravisiongames** [KrauseFx/fastlane#652]
Hi all, I'm a newbie in iOS development, and I'm trying to use fastlane to automatically generate a build and upload it into testflight without using the Xcode interface. I'm using fastlane version 1.30.2 and sigh 0.10.9, I followed the Automatic part of: https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md. I have a Mac with Yosemite 10.10.2 and I have Xcode 6.2.1.

 I'm using sigh with this parameters:

  sigh(
        output_path: ".",
        app_identifier: "com.IDENTITY",
        provisioning_name: "Project Distribution"
    )

However if I enter the apple developer site and download the provisioning for the same project the mobileprovisioning downloaded by sigh is different, in fact, it doesn't have the UDID's of the devices that I want to test on, am I missing any parameter here?

**Comment by KrauseFx** [comment]
@mgrilloteravisiongames By default `sigh` will downloaded your App Store provisioning profile. If you want to use the Ad Hoc or Development profile, check out the available options in `sigh` by running

```
sigh --help
```

I hope that helps :+1:

**Comment by mgrilloteravisiongames** [comment]
OMG!!! newbie mistake, the mobileprovisioning file I wanted to be downloaded was adhoc but I wasn't specifying that to sigh, I just added a 'adhoc: "true"' and worked like a charm, thanks @KrauseFx !

**Comment by KrauseFx** [comment]
Cool, glad I could help :+1:
