### ISSUE TITLE
codesign failed with exit code 1

### ISSUE THREAD

**Issue by mgrilloteravisiongames** [KrauseFx/fastlane#653]
Hi all!, I'm a ios development newbie, I've managed to succesfully use sigh to update my provisioning file in the project, however I got an error and I don't know how to fix it, I have this error on the gym log file:

    /usr/bin/codesign --force --sign <HEX NUMBER REDACTED> --entitlements <DIRECTION REDACTED>/test.app.xcent <DIRECTION REDACTED>/test.app: User interaction is not allowed.
    Command /usr/bin/codesign failed with exit code 1

I ran the command with --verbose but got the same result, in the end I'm not sure why the codesign command is failing or where to look for clues to solve the issue, can you please help me?

My fast file is:

	private_lane :build_app do |options|
	# Download the provisioning profile for the app
	sigh(
		output_path: "<DIRECTION REDACTED>",
		app_identifier: "<ID REDACTED>",
		cert_id: "<ID REDACTED>",
		provisioning_name: "<NAME REDACTED>",
		filename: "sigh_test.mobileprovision",
		adhoc: "True"
	) # Distribution Profile

	increment_build_number(xcodeproj: "test.xcodeproj") # version bump
	increment_version_number(bump_type: "patch")
	ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID];

	gym(
		export_method: "ad-hoc",
		codesigning_identity: "<NAME REDACTED>",
		provisioning_profile_path: "<SAME DIRECTION AS SIGH>/sigh_test.mobileprovision"
	)
	end
	lane :beta do
	build_app

	testflight(
		skip_deploy: true
	)

**Comment by KrauseFx** [comment]
Could you try using

```ruby
gym(
    use_legacy_build_api: true,
    codesigning_identity: "<NAME REDACTED>",
    provisioning_profile_path: "<SAME DIRECTION AS SIGH>/sigh_test.mobileprovision"
)
```
instead?

**Comment by mgrilloteravisiongames** [comment]
Thanks for your quick response!, I'm trying right now, the thing is every build is taking 30 minutes or so. I have another question, I redacted that identity, I saw in the help an example name like: 'iPhone Distribution: Name', but I see that there is something like: 'iPhone Distribution: Name (certid)', I've been trying with the first format, should I try with the second (with the certid)?

**Comment by mgrilloteravisiongames** [comment]
Hi all!, I ran the command as suggested by @KrauseFx but got the same result:

    Command /usr/bin/codesign failed with exit code 1

The only strange thing I see in the gym log is that before the signing command it prints out the signing Identity and the provisioning profile, and it has a XC in front of the bundle identifier. I still don't know what I'm doing wrong, any suggests?

Best Regards

**Comment by mgrilloteravisiongames** [comment]
I found out my mistake, I'm using ssh to execute the command and there was a problem with keychain, I ran the command:

    security unlock-keychain /Users/yannooo/Library/Keychains/login.keychain

And the first signing worked correctly. Thanks for the patience!

**Comment by zirinisp** [comment]
the unlock-keychain command did the trick for me too.
