### ISSUE TITLE
how to disable app symbols from fastlane

### ISSUE THREAD

**Issue by edwardvalentini** [KrauseFx/fastlane#656]
I want to submit my app without app symbols.   In xcode I would uncheck this box
![screen shot 2015-10-02 at 7 01 59 pm](https://cloud.githubusercontent.com/assets/1571326/10260980/5ebdd026-6938-11e5-959e-763f700d4c12.png)
but what would I do in the Fastfile to accomplish this?

Thank you.

**Comment by KrauseFx** [comment]
If you use `gym` for building, there is an option for that:

```
gym --help
```

    -m, --include_symbols  Should the ipa file include symbols? (GYM_INCLUDE_SYMBOLS)

You know how to pass the parameters?

```
gym(include_symbols: false)
```
:+1:

**Comment by edwardvalentini** [comment]
awesome - thanks!

**Comment by KrauseFx** [comment]
:+1:

**Comment by onmyway133** [comment]
@edwardvalentini just curious, why would you want to disable sending app symbol? Isn't it necessary for Apple to generate correct dSYM for bit code enabled app?
