### ISSUE TITLE
`generate_deliver_file': undefined method `latest_version'

### ISSUE THREAD

**Issue by aloifolia** [KrauseFx/fastlane#657]
During the initialization of fastlane with `fastlane init` the following prompt arises:
````
[13:14:57]: To not be asked about this value, you can specify it using 'app'
The app ID of the app you want to use/modify:
````
I then re-enter the bundle identifier (Or am I supposed to enter something different?). As a result, fastlane crashes:
`````
[13:15:00]: Error occurred with the setup program! Reverting changes now!
[13:15:00]: Moving './fastlane/screenshots' to 'screenshots'
[13:15:00]: Deleting the 'fastlane' folder
/Library/Ruby/Gems/2.0.0/gems/deliver-1.1.1/lib/deliver/setup.rb:31:in `generate_deliver_file': undefined method `latest_version' for "com.emundo.Salesman":String (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.1/lib/deliver/setup.rb:14:in `create_based_on_identifier'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.1/lib/deliver/setup.rb:5:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/setup.rb:110:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/setup.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
````
I am using fastlane 1.30.2.

**Comment by KrauseFx** [comment]
It looks like your app is not in the store yet, right? Could you update to the new deliver using `sudo gem update deliver` and let me know if that works for you?

**Comment by cytryn** [comment]
I had the same error, just tried updating the gem but it didnt work =/

**Comment by KrauseFx** [comment]
@cytryn I'll need some more information about the error you got.

**Comment by cytryn** [comment]
@KrauseFx it is exactly the same.

A brand new project with couple of pods and not yet on the app store.

**Comment by KrauseFx** [comment]
@cytryn which version of spaceship do you use? Please make sure to use the latest one using `gem update spaceship`

**Comment by cytryn** [comment]
spaceship (0.11.2)

$ gem update spaceship
Updating installed gems
Nothing to update

Just to mention that I am just following the guide: https://github.com/KrauseFx/fastlane/blob/master/docs/Guide.md

I installed fastlane gem and tried to init

**Comment by KrauseFx** [comment]
Sorry you're running into this issue. Does your app already exist on iTunes Connect and the app identifier matches the one you entered?

**Comment by cytryn** [comment]
@KrauseFx no there is no app on the app store, so I just typed 'app' at the app id...

is this the problem?

**Comment by KrauseFx** [comment]
Yes, that's the problem. The error message is not clear. I added a new message now: https://github.com/KrauseFx/deliver/commit/a56aa364a1eaf9abdfeaa99abd9e8c563f9d68b3

Anyway, so you can only `deliver init` if you already have an app.

**Comment by KrauseFx** [comment]
You can `fastlane init`, but you have to say No to setting up `deliver`

**Comment by cytryn** [comment]
@KrauseFx so ```deliver``` is supposed to be installed only when I have created the app on connect?

**Comment by KrauseFx** [comment]
You're right, it has been possible to init apps which are not in the store yet. This was removed with 1.0. I think it makes sense to add this feature again.

Why do you want to init deliver for an app that's not yet in the store? You have already installed deliver, it's only the setup that requires the app to be available.

**Comment by cytryn** [comment]
That makes sense. But perhaps the message is misleading:

```Do you want to setup 'deliver', which is used to upload app screenshots, app metadata and app
updates to the App Store? (y/n)```

This lead me to think that I could configure it even before creating it on itunesConnect. So I went for it.

Maybe a different message would be enough?

Thanks for the attention so far.

**Comment by aloifolia** [comment]
OK, with this new information, I managed the initialization. I am also voting for a better documentation regarding this option.

**Comment by KrauseFx** [comment]
@aloifolia There is no such thing as voting. It's an open source project, everyone can contribute!

**Comment by KrauseFx** [comment]
I'll improve the message that is displayed.

**Comment by KrauseFx** [comment]
```
"Do you want to setup 'deliver', which is used to upload app screenshots, app metadata and app updates to the App Store? This requires the app to be in the App Store already. (y/n)"
```

That's better now :+1:

**Comment by cytryn** [comment]
@KrauseFx awesome, thanks
