### ISSUE TITLE
Promo codes

### ISSUE THREAD

**Issue by iosdeveloper** [KrauseFx/fastlane#66]
Since this is so far the only alternative for https://github.com/kovpas/itc.cli that still works, I suggest implementing promo code generation (https://github.com/kovpas/itc.cli/tree/archive#promo-codes). It was really useful and a great time saver.
@KrauseFx @blach

**Comment by iosdeveloper** [comment]
I'd be more than happy to sponsor this, if anyone wants to take a shot at it.

**Comment by blach** [comment]
I would also be willing to help sponsor this.

**Comment by KrauseFx** [comment]
Thanks @iosdeveloper @blach, we're already in email contact and will finish and release this feature over the next few days :+1:

**Comment by KrauseFx** [comment]
Forgot to update the issue status. The tool is available now: https://github.com/KrauseFx/codes :+1: Thanks again for sponsoring this functionality.
