### ISSUE TITLE
git_commit action doesn't allow multiple paths

### ISSUE THREAD

**Issue by squarefrog** [KrauseFx/fastlane#660]
I'm writing a lane which will ease making a new Pod release. In this lane I version bump 3 files:

- `Example-Info.plist`
- `ExampleTests-Info.plist`
- `Example.podspec`

I'd like to commit all three of these files using the `git_commit` action:

    paths = 'path/to/Example-Info.plist path/to/ExampleTests-Info.plist path/to/Example.podspec'
    message = "Updating to #{version_number}"
    git_commit(path: paths, message: message)

This results in the following error:

    [11:25:45]: fastlane finished with errors
    /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/actions/git_commit.rb:27:in `block in available_options': Couldn't find file at path 'path/to/Example-Info.plist path/to/ExampleTests-Info.plist path/to/Example.podspec' (RuntimeError)
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/config_item.rb:53:in `call'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/config_item.rb:53:in `valid?'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/config_item.rb:38:in `verify!'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/configuration.rb:50:in `block in verify_value_exists'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/configuration.rb:45:in `each'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/configuration.rb:45:in `verify_value_exists'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/configuration.rb:30:in `initialize'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/configuration.rb:18:in `new'
            from /Users/myusername/.gem/gems/fastlane_core-0.19.0/lib/fastlane_core/configuration/configuration.rb:18:in `create'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/configuration_helper.rb:8:in `parse'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:134:in `block (2 levels) in execute_action'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:128:in `block in execute_action'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `chdir'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:127:in `execute_action'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/fast_file.rb:137:in `method_missing'
            from (eval):46:in `block (2 levels) in parse'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/lane.rb:36:in `call'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:51:in `block in execute'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `chdir'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/runner.rb:46:in `execute'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/lib/fastlane/command_line_handler.rb:31:in `handle'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/bin/fastlane:36:in `block (2 levels) in run'
            from /Users/myusername/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
            from /Users/myusername/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
            from /Users/myusername/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
            from /Users/myusername/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
            from /Users/myusername/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
            from /Users/myusername/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
            from /Users/myusername/.gem/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
            from /Users/myusername/.gem/bin/fastlane:23:in `load'
            from /Users/myusername/.gem/bin/fastlane:23:in `<main>'
            from /Users/myusername/.gem/bin/ruby_executable_hooks:15:in `eval'
            from /Users/myusername/.gem/bin/ruby_executable_hooks:15:in `<main>'

This is a result of [this line](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/git_commit.rb#L5) in [git_commit.rb](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/git_commit.rb#L5):

    result = Actions.sh("git commit -m '#{params[:message]}' '#{params[:path]}'")

Dropping the single quotes would affect anyone passing in a string with spaces in, so would you be opposed to me submitting a Pull Request adding in another action named `git_commit_multiple_paths` which takes in an array of strings?

**Comment by squarefrog** [comment]
Alternatively, would this be better suited as two discrete actions?

`git_add(path: './Filename')`

`git_commit(message: 'Commit message')`

**Comment by KrauseFx** [comment]
I'd be okay with allowing the user to pass either a string or an array and have a simple `if else` with `params[:path].kind_of?(String)`

Would you like to submit a pull request for that?

**Comment by squarefrog** [comment]
I'd love to!

**Comment by KrauseFx** [comment]
Thank you so much @squarefrog :+1:
