### ISSUE TITLE
fastlane init issue when setting up deliver

### ISSUE THREAD

**Issue by satbam** [KrauseFx/fastlane#666]
Hi there,
I cannot setup fastlane in my project as a result of the current issue:
*I get here
Do you want to setup 'deliver', which is used to upload app screenshots, app
metadata and app updates to the App Store or Apple TestFlight? (y/n)
*I type y
*Signs me into iTunes connect then asks me this

To not be asked about this value, you can specify it using 'app'
The app ID of the app you want to use/modify:
*I type in app or anything for that matter and it just crashes as this is a new app and I get this error

```
/Library/Ruby/Gems/2.0.0/gems/deliver-1.2.0/lib/deliver/setup.rb:31:in `generate_deliver_file': undefined method `latest_version' for "app":String (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.2.0/lib/deliver/setup.rb:14:in `create_based_on_identifier'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.2.0/lib/deliver/setup.rb:5:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/setup.rb:110:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/lib/fastlane/setup.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.30.2/bin/fastlane:133:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
Also is there a way to download a previous version of fastlane directly?

**Comment by KrauseFx** [comment]
I just tested the exact same process and it worked. Are you sure the app exists on iTunes Connect and you have access to it with that account?

**Comment by satbam** [comment]
Hi Felix,
The app does not exist I am setting it up for a new app. Is this not how it is supposed to work. In 0.29 it just installed it and then asked me if the app exists which is where I said no and it worked.

**Comment by KrauseFx** [comment]
You need to use [produce](https://github.com/fastlane/produce) to create a new app

**Comment by satbam** [comment]
So this does not work like it did earlier. I find it misleading as a user where it asks me to setup deliver in the setup process first but I need to have produce installed before and then setup the app?

**Comment by satbam** [comment]
Is there a way for me to download 0.29 directly?

**Comment by KrauseFx** [comment]
I don't understand what you mean. `deliver` is used to upload metadata to *existing* apps.

**Comment by satbam** [comment]
Hey Felix,
What I mean is that during the initial install process. When I select to install deliver and I don't have an existing app I should be able to install it. However it crashes.

**Comment by KrauseFx** [comment]
Good point, I'll add a note for that.

**Comment by KrauseFx** [comment]
Thanks again for your feedback :+1:

**Comment by satbam** [comment]
Thanks Felix. Great tool!
