### ISSUE TITLE
deliver_file_path option not available anymore

### ISSUE THREAD

**Issue by Sylvain-B** [KrauseFx/fastlane#667]
Hello,

Has the option for deliver "deliver_file_path" been removed? 

    Could not find option 'deliver_file_path' in the list of available options: username, app_identifier, app, ipa, metadata_path, screenshots_path, app_version, skip_metadata, force, submit_for_review, automatic_release, price_tier, app_rating_config_path, submission_information, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, app_review_information, description, name, keywords, release_notes, privacy_url, support_url, marketing_url

I was using this option because I manage several DeliverFile files.

Is there a workaround?

The documentation still mention the option : https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#deliver

The option "skip_deploy" seems unavailable too, is there a reason for it?

Thanks!

**Comment by KrauseFx** [comment]
Thanks @Sylvain-B, I updated the docs. Please check out the release notes: https://github.com/KrauseFx/deliver/releases/tag/1.0.0 in particular the migration guide on what has changed :+1: Sorry for the troubles

**Comment by Sylvain-B** [comment]
Thanks @KrauseFx for quick response!

I have checked the migration guide, but I did not find any workaround. Is there still a way to specify the path of DeliverFile?

**Comment by KrauseFx** [comment]
Sorry, that's not possible right now.
