### ISSUE TITLE
[Feature] Add dependencies between actions

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/fastlane#67]
```ruby
  sigh
  cert
```
or
```
  ipa
  sigh
```

should raise an exception, since it's obviously the wrong order of tools. I think there should be a new command, which you can put on the top of the `Fastfile`, something like

```ruby
skip_checking_dependencies
```

which will not raise an exception (in case you have some complex nested calls)

The exception should be raised when running the script and entering the `sigh` action, which sees, `ipa` was already run.

Therefore, `fastlane` should keep a record of executed commands and store it in the lane context.

**Comment by champo** [comment]
Maybe commands is not the best idea? Since I could have a custom action that does sigh-like things. But rather, require that actions declare their inputs and outputs, and match those?

**Comment by almassapargali** [comment]
Maybe just don't care and let commands run in there order user declared. And let it fail if some inputs incorrect, like user wants to create push certificate, but not created app yet, etc. :imp:

**Comment by KrauseFx** [comment]
@almassapargali agree, that's possible the easiest and most stable way. Maybe we should close this issue.

**Comment by joshdholtz** [comment]
@krausefx I agree. I don't think command dependency is necessary. Sounds like it be over engineering at the moment 😁

**Comment by KrauseFx** [comment]
Okay, I'll close this issue for now.
