### ISSUE TITLE
Implementing `is_supported?` for all actions is mandatory. Please update Fastlane::Actions::XXXX

### ISSUE THREAD

**Issue by pronebird** [KrauseFx/fastlane#676]
Is there any guide how to implement custom Actions? I was looking at some examples but they seem to be out of date. Thanks.

**Comment by KrauseFx** [comment]
You want to develop your own local action, right? You can run `fastlane new_action` to create a new action.

What is out of date?

Take a look at some of the integrations here https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/carthage.rb

**Comment by pronebird** [comment]
Thanks, I finally figured that out!

I looked at https://github.com/fastlane/examples/blob/master/BeMyEyes/actions/get_global_value.rb and it's apparently out of date.

**Comment by KrauseFx** [comment]
Thanks for letting me know :+1:
