### ISSUE TITLE
Fastlane actions that are possibly missing documentation.

### ISSUE THREAD

**Issue by squarefrog** [KrauseFx/fastlane#679]
Files in [`lib/fastlane/actions`](https://github.com/KrauseFx/fastlane/tree/master/lib/fastlane/actions) that are missing documentation in [`Actions.md`](https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md). 

Some of these are built in actions so can probably be safely ignored.

- [x] appstore.rb
- [x] backup_file.rb
- [x] backup_xcarchive.rb
- [x] debug.rb
- [x] dotgpg_environment.rb
- [x] git_pull.rb
- [x] import_from_git.rb
- [x] restore_file.rb
- [x] update_info_plist.rb

The following are actions I'm unsure about:

- [ ] puts.rb - is this just a wrapper around Ruby `puts` command? E.g. `puts("Hello world")`

The following are actions used by `Fastlane` and probably don't need documenting in `Actions.md`:

- [ ] default_platform.rb
- [ ] fastlane_version.rb
- [ ] import.rb
- [ ] lane_context.rb
- [ ] opt_out_usage.rb
- [ ] team_id.rb
- [ ] team_name.rb
- [ ] update_project_code_signing.rb

**Comment by KrauseFx** [comment]
Nice catch, I didn't know so many actions were missing. My goal is to generate `Actions.md` based on the actual source code soon. 

I'll go through the list to add missing documentation.

**Comment by KrauseFx** [comment]
Also, you know about the `fastlane actions` command?

**Comment by squarefrog** [comment]
I don't mind documenting most of these actions, that will leave you free to concentrate on more important things. 

Autogenerating sounds like a good idea. Although as it stands at the moment it's nice that it's mostly organised into sections. 

I didn't know about `fastlane actions` but I do now! :+1:

**Comment by squarefrog** [comment]
At least I can document all the user added actions, as you'll know more about the fastlane provided actions better than me.

**Comment by KrauseFx** [comment]
Sounds good, thank you so much for helping me with this! :+1:

**Comment by squarefrog** [comment]
No problem, I can do that during the time I'd be waiting for builds and releases without using `fastlane` :laughing:

**Comment by KrauseFx** [comment]
Yeah, nice :rocket:

**Comment by squarefrog** [comment]
OK I'm done.

Please check the `import_from_git` documentation. I wasn't sure if the `url` parameter was supposed to be `https` or `ssh`.

Also I'm not sure if the `debug` action needs documenting in here, or if it's part of the core toolset that it can be left out.

**Comment by KrauseFx** [comment]
`puts` is a wrapper for `Helper.log.info` which will also prefix the output with the current time.

**Comment by squarefrog** [comment]
Would you like it documenting?

**Comment by KrauseFx** [comment]
Thanks again :+1:
