### ISSUE TITLE
Unable upload new version of app - Deliver 1.3.0 and Fastlane 1.32.1

### ISSUE THREAD

**Issue by zeroel** [KrauseFx/fastlane#682]
I'm using Deliver to create a new version of my app, that already exist in App Store. But alway getting error.
@KrauseFx Please help me soon!

The log:
......
[37m[21:16:55]: [0mLoading './fastlane/metadata/copyright.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/primary_category.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/secondary_category.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/primary_first_sub_category.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/primary_second_sub_category.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/secondary_first_sub_category.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/secondary_first_sub_category.txt'...
[37m[21:16:55]: [0mLoading './fastlane/metadata/secondary_first_sub_category.txt'...
[37m[21:16:56]: [0mActivating languages da, de-DE, el, en-AU, en-CA, en-GB, en-US, es-ES, es-MX, fi, fr-CA, fr-FR, id, it, ja, ko, ms, nl-NL, no, pt-BR, pt-PT, ru, sv, th, tr, vi, zh-Hans, zh-Hant...
[37m[21:16:59]: [0m[33mVariable Dump:[0m
[37m[21:16:59]: [0m{:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload_all"}
[1m[31m[21:16:59]: [0m[0mMust be a hash

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | deliver                             | 11          |
+------+-------------------------------------+-------------+

[1m[31m[21:16:59]: [0m[0m[31mfastlane finished with errors[0m
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/tunes/app_version.rb:232:in `update_rating': Must be a hash (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_metadata.rb:143:in `set_app_rating'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_metadata.rb:54:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):89:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:142:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by squarefrog** [comment]
Looking at your stack trace you have an error here:

```
update_rating': Must be a hash (RuntimeError) from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_metadata.rb:143:inset_app_rating'
```

Are you setting `update_rating` properly? Can you post your `Fastfile` / `Deliverfile`?

**Comment by zeroel** [comment]
How can I settings "update_rating"?
====THIS IS MY DELIVERFILE=======

ipa './fastlane/app.ipa'

app_icon './fastlane/appicon/icon.png'
app ENV["kAPP_APPLE_ID"]



copyright "#{Time.now.year} Application"

automatic_release ENV["kAPP_AUTOMATIC_RELEASE"]

app_review_information(
  first_name: "Name",
  last_name: "Name",
  phone_number: "+11111111",
  email_address: "contact@gmail.com",
  demo_user: "",
  demo_password: "",
  notes: ""
)


app_rating_config_path './fastlane/ratings.json'

price_tier 0 


submission_information({
  add_id_info_limits_tracking:true,
  add_id_info_serves_ads:ENV["kAPP_FURTHER_ADVERTISING_IDENTIFIER"],
  add_id_info_tracks_action:false,
  add_id_info_tracks_install:false,
  add_id_info_uses_idfa:ENV["kAPP_FURTHER_ADVERTISING_IDENTIFIER"],
  content_rights_contains_third_party_content:ENV["kAPP_FURTHER_CONTAINS_THIRD_PARTY"],
  content_rights_has_rights:ENV["kAPP_FURTHER_HAS_RIGHTS"],
  export_compliance_available_on_french_store:false,
  export_compliance_contains_proprietary_cryptography:false,
  export_compliance_contains_third_party_cryptography:false,
  export_compliance_is_exempt:ENV["kAPP_FURTHER_IS_EXEMPT"],
  export_compliance_uses_encryption:false,
  export_compliance_ccat_file: false,
  export_compliance_app_type:false,
  export_compliance_encryption_updated:ENV["kAPP_FURTHER_ENCRYPTION_UPDATED"],
  export_compliance_compliance_required:false,
  export_compliance_platform:false
})


=====AND MY FASTFILE======
fastlane_version "1.6.0"

default_platform :ios


platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods

    # increment_build_number

    # ipa # Build your app - more options available

    # xctool # run the tests of your app

 
 end

  desc "# Runs all the tests"
  lane :test do
    # snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # snapshot
    sigh
    deliver(beta: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  lane :create_app do
     produce({
          username: 'contact@gmail.com',
          app_identifier: ENV["kAPP_IDENTIFIER"],
          app_name: ENV["kAPP_PRODUCE_NAME"],
          language: 'English',
          app_version: '1.0',
          sku: ENV["kAPP_PRODUCE_SKU"]
     })

  ENV["kAPP_APPLE_ID"]=ENV["PRODUCE_APPLE_ID"]
  end

  
  lane :upload_all do

    deliver(submit_for_review: false, force: true)
    # frameit
  end

  

  desc "Uploads metadata only - no ipa file will be uploaded"
  desc "You'll get a summary of the collected metadata before it's uploaded"
  lane :upload_metadata do
    deliver(metadata_only: true, skip_deploy: true, force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end


  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md

**Comment by squarefrog** [comment]
OK it looks like you are setting the `app_rating_config_path`:

```
app_rating_config_path './fastlane/ratings.json'
```

Does this file exist? And what are the contents of this file?

**Comment by zeroel** [comment]
Yes, this is my ratings.json:

```ruby
{
  "CARTOON_FANTASY_VIOLENCE": 0,
  "REALISTIC_VIOLENCE": 0,
  "PROLONGED_GRAPHIC_SADISTIC_REALISTIC_VIOLENCE": 0,
  "PROFANITY_CRUDE_HUMOR": 0,
  "MATURE_SUGGESTIVE": 0,
  "HORROR": 0,
  "MEDICAL_TREATMENT_INFO": 0,
  "ALCOHOL_TOBACCO_DRUGS": 0,
  "GAMBLING": 0,
  "SEXUAL_CONTENT_NUDITY": 0,
  "GRAPHIC_SEXUAL_CONTENT_NUDITY": 0,
  
  "UNRESTRICTED_WEB_ACCESS": 0,
  "GAMBLING_CONTESTS": 0
}
```

**Comment by zeroel** [comment]
Resovled, Thank @squarefrog

**Comment by squarefrog** [comment]
No problem. What was the issue?

**Comment by KrauseFx** [comment]
Thanks @squarefrog for jumping it! :+1:
