### ISSUE TITLE
ipa file  has wrong entitlements

### ISSUE THREAD

**Issue by purplepeng** [KrauseFx/fastlane#688]
HI,
    I use `fastlane` and have configured the `Fastfile` like below.
```
lane :fir do
    sigh
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "gaibianjia",use_legacy_build_api: true)
    sh "../fir.sh"
  end
```
And my project file has sign，just like below
![ebb71899-fe36-423c-a92a-e2e2b4542b59](https://cloud.githubusercontent.com/assets/3256113/10423654/2de37dc8-70fb-11e5-8c13-9bf6bb25cb54.png)
My gym version is `0.9.0`,fastlane version is `1.32.1`.
When i choose the fir lane in command line, it build success, but the ipa's entitlements is not correct,it's entitlements is product what i selected is development.
When I use Xcode 6, i did't enchant the problem. When I use Xcode 7, it has the problem. What's wrong with it? Thank you.

**Comment by purplepeng** [comment]
I also try the `gym --use_legacy_build_api true` from the command line. It build correctly and has correct entitlements. But what I use fastlane, and config it like above. How to resolve it？Thank you!

**Comment by KrauseFx** [comment]
It's okay to use the legacy API for now if that's working for you :+1:

**Comment by purplepeng** [comment]
My fastlane is 1.32.2,gym 0.9.0,and I config it like above, it can builded ,but the entitlements is not correct.

**Comment by KrauseFx** [comment]
You selected `iOS Developer` in your project instead of `iOS Distribution`. It must be distribution when running `sigh` without parameters as it uses an App Store profile by default.

**Comment by purplepeng** [comment]
Yes, you are right.:+1:
