### ISSUE TITLE
import_from_git fails if repo containing master Fastfile has sub-folders

### ISSUE THREAD

**Issue by lemonkey** [KrauseFx/fastlane#689]
I was wondering if in addition to importing a master Fastfile, the import_from_git action could also handle any custom actions that the master Fastfile might depend on.

I created a new repo path that contains my master Fastfile along with an actions sub-folder containing my custom Ruby script.

When I then used a simplified Fastfile for my app that imports this master Fastfile using import_from_git, the shell command fails when testing this simplified Fastfile (using `fastlane list`):

```
import_from_git(url: 'git@github.com:<organization>/tools.git', path: 'fastlane')
```

```
[12:08:04]: --- Step: import_from_git ---
[12:08:04]: -----------------------------
[12:08:04]: Cloning remote git repo...
[12:08:04]: [SHELL COMMAND]: git clone 'git@github.com:<organization>/tools.git' '/tmp/fl_clones_1444676884/tools.git' --depth 1 -n 
[12:08:04]: [SHELL]: Cloning into '/tmp/fl_clones_1444676884/tools.git'...
[12:08:06]: [SHELL COMMAND]: cd '/tmp/fl_clones_1444676884/tools.git' && git checkout HEAD 'fastlane'
[12:08:06]: [SHELL COMMAND]: cd '/tmp/fl_clones_1444676884/tools.git' && git checkout HEAD './actions'
[12:08:06]: [SHELL]: error: pathspec './actions' did not match any file(s) known to git.
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `eval': Is a directory - /tmp/fl_clones_1444676884/tools.git/fastlane (Errno::EISDIR)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:193:in `import'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:235:in `block in import_from_git'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:206:in `import_from_git'
	from (eval):27:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:33:in `chdir'
```

**Comment by KrauseFx** [comment]
`fastlane` will automatically import all the local actions as well, see this command
```
[12:08:06]: [SHELL COMMAND]: cd '/tmp/fl_clones_1444676884/tools.git' && git checkout HEAD './actions'
```
but it looks like it's failing with 
```
[12:08:06]: [SHELL]: error: pathspec './actions' did not match any file(s) known to git.
```

Do you have an `actions` folder in the repo?

**Comment by KrauseFx** [comment]
I'm using this for all fastlane releases: https://github.com/KrauseFx/fastlane/tree/master/fastlane/actions

**Comment by Liquidsoul** [comment]
Hi @lemonkey 

The problem is there:
```[12:08:06]: [SHELL COMMAND]: cd '/tmp/fl_clones_1444676884/tools.git' && git checkout HEAD 'fast lane'```
It seems like you've specified a custom `path` for your `import_from_git` call. By default, we use `fastlane/Fastfile` and it seems like you're passing only `fastlane`.
Consequently, when we try to build the path for the `actions` folder, we compute your path as if it was a file resulting to `./actions` instead of `fastlane/actions`.

The solution here seems to use the default path used in `import_from_git`.

**Comment by KrauseFx** [comment]
@Liquidsoul interesting, I guess this is something the action should catch and show a nice error for.

**Comment by Liquidsoul** [comment]
@KrauseFx In fact, we're already showing that the path is not valid because it's a directory here :wink: 
`/Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:36:in `eval': Is a directory - /tmp/fl_clones_1444676884/tools.git/fastlane (Errno::EISDIR)`

The fact that the `actions` folder is optional makes error handling trickier.

**Comment by lemonkey** [comment]
@Liquidsoul You are correct, I am using a custom path since it is a sub-folder in an existing repo holding some of my other tools, etc.

**Comment by lemonkey** [comment]
Note that if anything but the default path for import_from_git is used, you'll want to update the advanced (documentation)[https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#import_from_git]

**Comment by lemonkey** [comment]
After renaming my master Fastfile to just "Fastfile" in my tools repo fastlane sub-directory and after updating my call to import_from_git to use the default path "fastlane/Fastfile", it now works.

Thanks!

**Comment by lemonkey** [comment]
FYI
``` 
[14:24:17]: Cloning remote git repo...
[14:24:17]: [SHELL COMMAND]: git clone 'git@github.com:<organization>/tools.git' '/tmp/fl_clones_1444685057/tools.git' --depth 1 -n 
[14:24:17]: [SHELL]: Cloning into '/tmp/fl_clones_1444685057/tools.git'...
[14:24:20]: [SHELL COMMAND]: cd '/tmp/fl_clones_1444685057/tools.git' && git checkout HEAD 'fastlane/Fastfile'
[14:24:20]: [SHELL COMMAND]: cd '/tmp/fl_clones_1444685057/tools.git' && git checkout HEAD 'fastlane/actions'
```
