### ISSUE TITLE
[Feature] pass provisioning profile ID from sigh to ipa action

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/fastlane#69]
Use the lane context to pass this value.

**Comment by champo** [comment]
Isn't this supported already? I've got: 
```
  sigh :development, :skip_install
  ipa({
    embed: Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH], 
    identity: ENV['SIGH_TEAM_ID'],
    clean: '', 
    destination: 'fastlane/build'
  })  
```

**Comment by KrauseFx** [comment]
Currently the lane context is used (a ruby hash). 

Instead of writing 
```ruby 
embed: Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH]
```

you could write
```ruby
embed: ENV["SIGH_PROFILE_PATH"]
```

or even better, skip that line alltogether.

**Comment by KrauseFx** [comment]
Sorry, I misunderstood your recent comment.

What I meant was:

```ruby
Actions::SharedValues::SIGH_UDID # the UDID of the generated provisioning profile
```

You can now access the UDID of the provisioning profile, to set it in your Xcode project. This is implemented with the most recent release.
