### ISSUE TITLE
cert doesn't use team_id from Appfile

### ISSUE THREAD

**Issue by jerolimov** [KrauseFx/fastlane#700]
`cert` asks on the command line to selected a team on a CI server when `team_id` is not defined in the lane call. But `sigh` use automatically the `team_id` from `Appfile`.

`cert(team_id: "...")` works well.

It would be great if the `cert` command in a lane would load the `team_id´ from the same `Appfile` here as default.

**Comment by nicolasbraun** [comment]
I confirm this issue. `username`is correctly inferred from the AppFile but `team_id`is not

**Comment by KrauseFx** [comment]
Thanks, I'll fix it :+1:

**Comment by KrauseFx** [comment]
This will be in the next release later today, thanks @nicolasbraun :+1:
