### ISSUE TITLE
Using Pilot and Deliver

### ISSUE THREAD

**Issue by squarefrog** [KrauseFx/fastlane#704]
I'm trying to write my app store release lane, but theres something I'm not quite sure about.

Our app is tested through TestFlight, so the app gets built once a week and released using `pilot`. Now say for example, we're happy with the last update and want to submit it for review. We currently have to do this manually, so I'd prefer to use `deliver`, however if you attempt to use `deliver` with the same ipa file it fails (quite rightly so), as that build has already been submitted.

What is the intended flow here? Use `deliver` to upload metadata only, then select the build and submit for review manually?

**Comment by KrauseFx** [comment]
iTunes Connect introduced this behavior after `deliver` was initially released. Currently `fastlane` doesn't support this workflow. 

Do you have any ideas how I could implement it? How does `deliver` know which build to choose?

**Comment by KrauseFx** [comment]
* when only putting an existing TestFlight build into production

**Comment by squarefrog** [comment]
I was actually thinking about this today and I think I had the wrong mindset about this. My initial thought was the release lane should 

1. Build production app
2. Submit with `deliver`
3. Build beta
4. Submit with `pilot`

However I think I'm approaching this the wrong way. The current workflow supports the following lane

1. Build beta app
2. Submit using `pilot`
2. Create new version and upload metadata with `deliver`
4. When we are happy with the beta build then manually login, choose the version and submit for review 

I didn't realise until I read the `deliver` documentation that it only submits an ipa when explicitly told to. That was an oversight on my part!

Most people won't have that problem as they will use fabric or hockey to distribute betas!

**Comment by KrauseFx** [comment]
Sounds good :+1:

**Comment by squarefrog** [comment]
I think I'll close this as its not an issue with the tooling. Thanks Felix :+1:

**Comment by KrauseFx** [comment]
Thanks for thinking about the process and letting me know :+1:
