### ISSUE TITLE
Your current version (1.0) does not respect the format A.B.C

### ISSUE THREAD

**Issue by aloifolia** [KrauseFx/fastlane#710]
I am using the command `increment_version_number` in my fastline config and get the following error message:
````
[15:40:29]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`
👍  This makes resolving issues much easier and helps improving fastlane
🔒  The reports might contain personal data, but will be stored securely on getsentry.com
✨  Once crash reporting is enabled, you have much cleaner output when something goes wrong
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.33.4/lib/fastlane/actions/increment_version_number.rb:37:in `run': Your current version (1.0) does not respect the format A.B.C (RuntimeError)
````
The version in plist is actually 1.0.9. So where does fastlane get this version number from?

**Comment by Liquidsoul** [comment]
Hi @aloifolia 

We use `agvtool` to get the version from your project using the command:

    $ agvtool what-marketing-version -terse1

You need to setup your project using [these instructions](https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#increment_version_number) in order to use this feature.

**Comment by aloifolia** [comment]
Thank you, by running the tool without the `terse1` option I found that I missed some plist files when I set the version and build numbers of my project. After this error was fixed, I still had to adapt the Build Settings (Current Project Version = build number, Versioning System = "Apple Generic"), but this is unrelated to the original problem.

**Comment by KrauseFx** [comment]
Thanks @Liquidsoul :+1:
