### ISSUE TITLE
Why is fastlane 1.34.0 not available on rubygems?

### ISSUE THREAD

**Issue by nvh** [KrauseFx/fastlane#718]
I don't see it here: https://rubygems.org/gems/fastlane

Did you forget to push it in yesterday's excitement? :smile:

**Comment by jtkendall** [comment]
I was wondering this as well. Just found out about Fastlane and want to use the latest and greatest. :)

**Comment by KrauseFx** [comment]
I'm really sorry about this, the initial deployment didn't go through. It's available now :+1:
