### ISSUE TITLE
fastlane init behind http proxy

### ISSUE THREAD

**Issue by inidona** [KrauseFx/fastlane#719]
Hi,

our buildserver is behind a http proxy. while fastlane init it hangs while connect to itunescoonect, after some minutes it breaks with broken connection.

is it possible to set an proxy server for communication?

thanks
andreas

**Comment by xfreebird** [comment]
@inidona the simplest way is to set it from command line:

```bash
export http_proxy=http://proxy.server.com:@aproxy:portnumber
export https_proxy=https://proxy.server.com:@aproxy:portnumber
export no_proxy=localhost,127.0.0.0/8,*.local
```

you could add these lines to ```~/.profile``` and ```~/.bashrc```

The alternative way is to set system wide proxy from ```System Preferences - > Network``` or from command line:

```networksetup –setwebproxy "Ethernet" "proxy.amsys.co.uk" "8080"```
```networksetup –setwebproxy "Ethernet" "proxy.amsys.co.uk" "8080" "on" "darren" "123"```

**Comment by inidona** [comment]
hi,

thanks, works fine. i had the proxy setup, but as automatic proxy setup via proxy.pac. this works not here.

thanks
andreas
