### ISSUE TITLE
Documentation - ipa vs. ipa (shenzhen)?

### ISSUE THREAD

**Issue by powtac** [KrauseFx/fastlane#72]
In the Readme.md, in the [list of tools](https://github.com/KrauseFx/fastlane#ipa) there is `ipa` listed. For me it unclear if this referes to a fastlane tool or to [shenzhen](https://github.com/nomad/shenzhen).

![unbenannt](https://cloud.githubusercontent.com/assets/36167/6328046/417b5cfa-bb63-11e4-95cc-1ae39f692c39.PNG)

**Comment by KrauseFx** [comment]
Good point, I'll make the README clearer. It's `shenzhen` under the hood!

**Comment by powtac** [comment]
Thanks - good to know! I was searching for the fastlane "ipa" documentation and realized it was not there.
