### ISSUE TITLE
Crash when App ID does not exist

### ISSUE THREAD

**Issue by ZevEisenberg** [KrauseFx/fastlane#721]
crash ID: 2d41bc5323433cc2b3c9cc90056289da

I am using a temporary app ID for development of a v2, so that I can have v1 and v2 installed at the same time on my device. I’m going to change it to the real app ID before I ship. I was prompted to set up deliver while running `fastlane init`, and when I put in an App ID that does not currently exist on iTunes Connect, I got a crash.

**Comment by KrauseFx** [comment]
That's expected behavior. When using `deliver init` is generates a configuration for you based on an existing app. That's why it will fail if the app is not available.

**Comment by ZevEisenberg** [comment]
It would be nice if it exited cleanly, rather than crashing.

**Comment by KrauseFx** [comment]
@ZevEisenberg right now that's the same thing for `fastlane` tools. I want to distinguish between real crashes and just errors in the future.
