### ISSUE TITLE
Create new app on Android

### ISSUE THREAD

**Issue by pieisgood** [KrauseFx/fastlane#722]
Not sure how the Android beta works yet, but updates are only uploaded after the first APK is sent to google. I assume app creation is in the works, but just in case it should work I thought I'd ask.

**Comment by KrauseFx** [comment]
This is not possible due the API limits for Google Play. I'm working on a solution :+1:

**Comment by KrauseFx** [comment]
For updating existing apps, check out [supply](https://github.com/fastlane/supply)

**Comment by pieisgood** [comment]
Cool, yeah I got supply working. Thanks again.
