### ISSUE TITLE
Combine embedded frameworks dSYMs before uploading to Hockey

### ISSUE THREAD

**Issue by vittoriom** [KrauseFx/fastlane#725]
I don't know why this issue wasn't already raised before, but I think the hockey action should combine the app dSYMs with the embedded framework ones, otherwise if a crash happens in an embedded framework, there is no way to know why/how

Additional info:
During archiving, separate dSYM packages are made for app itself and for each framework. When only dSYM for app is submitted to Hockey, the parts of code belonging to the framework cannot be symbolicated.

After archiving, open the Archive, then open the [framework].dSYM (Use "Show Package" in Finder), then copy `Contents/Resources/DWARF/[framework]` file into the `Contents/Resources/DWARF` of the [main app].dSYM, which will now contain two files, and can be uploaded to Hockey.

I'm not sure this is going to work or needs some more tinkering, but it's a starting point and something that would be nice if the hockey action could take care of

**Comment by xfreebird** [comment]
@vittoriom there is a ```gym``` PR https://github.com/fastlane/gym/pull/114 with a similar functionality. Not sure when is going to be merged.

**Comment by vittoriom** [comment]
Hi @xfreebird, correct! Thanks a lot, I missed that one. Will subscribe so I know when it's available. I'll definitely close this one since gym is probably a better place to have it anyway.
