### ISSUE TITLE
command not found (fastlane init) after installing

### ISSUE THREAD

**Issue by WhitneyMFoster** [KrauseFx/fastlane#729]
### Steps:
**sudo gem install fastlane --verbose**
   ...
   Successfully installed fastlane-1.34.0
   Parsing documentation for fastlane-1.34.0
   Parsing sources...
   100% [141/141]  lib/fastlane/version.rb
Done installing documentation for fastlane after 2 seconds
   1 gem installed

**cd MyAppFolder/**
**fastlane init**
   -bash: fastlane: command not found

Am I doing something wrong?

**Comment by DouglasHennrich** [comment]
something is wrong with your GEM PATH
try to run `where fastlane`
mine is `/Users/DHennrich/.gems/bin/fastlane`

**Comment by WhitneyMFoster** [comment]
Thanks for the fast reply! I keep getting this though :/
`-bash: where: command not found`

**Comment by DouglasHennrich** [comment]
on my `.zshrc` I have a line with this: `export GEM_HOME=~/.gems`
With that I assume that I have link my GEM PATH to `~/.gems` so all my gem's are downloaded and stored on that path... run `$GEM_HOME` on terminal to see of you have it too.

By the Way, I'm using [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) which I highly recommend you to use

**Comment by DouglasHennrich** [comment]
of course I have to `mkdir ~/.gems` before start to downloading my gems

**Comment by WhitneyMFoster** [comment]
ugh I feel completely command line challenged right now. Can I email you the output? It's saying `fastlane not found` even after i re-installed it.

**Comment by DouglasHennrich** [comment]
maybe facebook would be faster to reply hahaha

**Comment by DouglasHennrich** [comment]
[@DouglasHennrich](https://www.facebook.com/douglas.hennrich)

**Comment by WhitneyMFoster** [comment]
Just sent you a message. Thank you so much for your help!

**Comment by DouglasHennrich** [comment]
The problem has been solved! :+1:

**Comment by WhitneyMFoster** [comment]
Whoot! you're awesome!

**Comment by KrauseFx** [comment]
Oh wow, from GitHub issue to providing Facebook support, that's a new one :+1: Thank for helping @DouglasHennrich

**Comment by KrauseFx** [comment]
@DouglasHennrich Could you also share the solution here on GitHub for everyone to read?

**Comment by DouglasHennrich** [comment]
Sure @KrauseFx !
So... we have edit her `.zshrc` file... adding:
* export GEM_HOME=~/.gems
 
and add gems to the $PATH
* export "...:/Users/{Username}/.gems/bin"

after that... she downloaded `Fastlane` again and it was stored on the new GEM_HOME.
like you teach [here](https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#update_fastlane)

**Comment by AdrianBinDC** [comment]
I encountered a similar issue to the one @WhitneyMFoster encountered. I followed @DouglasHennrich's suggestion, yet the `fastlane not found` error persisted **until I rebooted Terminal** in OS X El Capitan.

**Comment by TKBurner** [comment]
@AdrianBinDC Thanks for letting us know. We'll try to reproduce over here. Hope you have a great weekend coming up! 👍

**Comment by dustinrwh** [comment]
I was dealing with the same issue, but adding this line to ~/.bash_profile (as suggested during install) fixed it for me:

`export PATH="$HOME/.fastlane/bin:$PATH"`

**Comment by rajeshm20** [comment]
I install by using common `brew cask install fastlane` had the same issue resolved by export `PATH="$HOME/.fastlane/bin:$PATH".` thanks @dustinrwh

**Comment by andryuwka** [comment]
exporting path working! thanks very much!!

**Comment by huwr** [comment]
I had to add this to my path:

`export PATH="$HOME/.fastlane/bin/fastlane_lib:$PATH`

**Comment by nmdias** [comment]
@AdrianBinDC did you manage to overcome this issue?

I also set run `export PATH="$HOME/.fastlane/bin:$PATH"`, and it work after that.

But **after closing** the terminal window, I have to set it again.

**Comment by nmdias** [comment]
Scratch that, I managed to get it working.

I had to **manually create** the `.bash_profile`file, in my `~/`folder:

```
cd ~/
touch .bash_profile
```

Then manually edit the file:

`nano .bash_profile`

With the export:

`export PATH="$HOME/.fastlane/bin:$PATH"`

It's working now.
