### ISSUE TITLE
Documenation - add list of fastlane terminology 

### ISSUE THREAD

**Issue by powtac** [KrauseFx/fastlane#73]
I think so far fastlane makes an excellent job of using good terminology for their APIs and documentations. But fastlane also uses several terms that could be understood or are understood differently in other projects. Maybe a list of words, on an extra page, could help a little to define how some terms are understood (differently) in the fastlane universe. Nothing long. But one sentence about what a term means for fastlane. No links, simple definitions.

**Proposal for fastlane terminology list**

* action
* extensions
* deliver
* produce
* snapshot
* codes
* lanes
* frames
* ...

Please feel free to extend/discuss this list to see if this request makes sense.

**Comment by KrauseFx** [comment]
I agree. I'm currently not happy with the README, I think I'll move all available actions into its own `.md` file (as it's already the case at the `deliver` project)

When doing this refactoring, we should also add a documentation about those words.

**Comment by KrauseFx** [comment]
I'll close this issue for now, I don't have plans to add this to the README right now, thanks for your feedback.
