### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by BlackFirePR** [KrauseFx/fastlane#732]
I have just installed Fastlane on my dev machine. If I want to make sure I'm using the latest version, how do I update it? Should I just run the command: "sudo gem install fastlane --verbose" whenever I want to use the latest version? Any risks of overwriting any configuration files if I do this?

Thanks!

**Comment by KrauseFx** [comment]
You can update using `sudo gem update fastlane`. The configuration will not be changed.

**Comment by BlackFirePR** [comment]
Thanks for the help and the quick reply!

Sent from Outlook




On Sat, Oct 24, 2015 at 2:40 PM -0700, "Felix Krause" <notifications@github.com> wrote:
You can update using `sudo gem update fastlane`. The configuration will not be changed.

---

**Comment by KrauseFx** [comment]
Happy to help :+1:
