### ISSUE TITLE
Invalid Swift Support

### ISSUE THREAD

**Issue by larryonoff** [KrauseFx/fastlane#737]
I get the following error while uploading build via fastlane/gym
```
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
```
While uploading via Xcode it's fine.

I have just found out that the issue occurs when export_method is "ad-hoc", when export_method is "app-store" error doesn't appear.

**Comment by xfreebird** [comment]
@larryonoff if you are trying to upload the ipa to TestFlight Beta or AppStore, then you should always use the  ```app-store``` profile.

In case you are uploading to 3rd party beta distribution sites such as Crashlytics or HockeyApp, you can use ```add-hoc```.

**Comment by larryonoff** [comment]
@xfreebird thanks. Didn't know about it.
