### ISSUE TITLE
Credentials manager

### ISSUE THREAD

**Issue by mdeandreis** [KrauseFx/fastlane#740]
I´m working with fastlane and Jenkins trying to upload a new version to testflight. When I run a job on Jenkins calling "fastlane beta" the new version can not be uploaded because I need to pass the password to login with my Apple account. The warning tells that I have to update `FASTLANE_PASSWORD` env variable on credentials manager. How can achieve this? I read that I need to update credentials manager but I do not know how to do it

Thanks,
Martin

**Comment by mdeandreis** [comment]
Finally ,I found a solution. I updated FASTLANE_PASSWORD variable on Appfile and everything works fine

Thanks,
Martin

**Comment by KrauseFx** [comment]
Sounds good! :+1:

**Comment by crewshin** [comment]
This same thing happened to me too. I was setting FASTLANE_PASSWORD into keychain access and setting export FASTLANE_PASSWORD=MyPassword into ~/.bash_profile and neither worked. So I guess I need to put it into the Fastfile.

**Comment by KrauseFx** [comment]
@crewshin are you talking about Jenkins?

**Comment by crewshin** [comment]
Ah. Both actually.

**Comment by KrauseFx** [comment]
Maybe [Keys.md](https://github.com/fastlane/setups/blob/master/Keys.md) can help you?
