### ISSUE TITLE
Execution fails on fastlane-0.1.14

### ISSUE THREAD

**Issue by pcardoso** [KrauseFx/fastlane#79]
I installed the gem without any issues, but executing the fastlane command would fail with this message:

```/Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/bin/fastlane:12:in `<class:FastlaneApplication>': uninitialized constant Commander::Methods (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.1.14/bin/fastlane:11:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'```

After doing a "gem install commander" it worked, so it seems  this commander thing is missing in the dependencies.

**Comment by KrauseFx** [comment]
That's weird, I'll take a look at it.

**Comment by joshdholtz** [comment]
@pcardoso Do you have multiple version of Ruby installed at all? Or installed `fastlane` in the wrong gemset? I use RVM and this happens to me sometimes. Not sure if this is the case but just asking to rule it out :grin:

**Comment by pcardoso** [comment]
@joshdholtz No rvm, just a stock Yosemite install. I haven't yet started to mess with the defaults. :)

**Comment by joshdholtz** [comment]
@KrauseFx Is this issue fixed with this commit? https://github.com/KrauseFx/fastlane_core/commit/8325a0dfc2f7f4fd6d8e0a985ee52ef76ccc6ece

**Comment by KrauseFx** [comment]
I hope so. Let's close the issue for now.
