### ISSUE TITLE
Multiple target support

### ISSUE THREAD

**Issue by nicolaslauquin** [KrauseFx/fastlane#8]
First of all, thank you for the great job.

I have an Xcode proj with 8 targets, each apps has its bundleid, appid and languages. In that case, time saved thanks to fastlane would be even more important for me but how to handle this ? For now I have my custom script and I'm thinking to migrate if there is built-in support in fastlane.

I'd like to create some configuration in a centralized file "Appfile" contening all the necessary information and be able to directly call the required one (Note: Appfile and Deliverfile for now look to share some duplicate information like app_identifier).

I found this issue https://github.com/KrauseFx/deliver/issues/67, it is a tips but It won't work for the multiple appstore metadata I think and it is not an official support in "fastlane".

Would you think about such an architecture support ? 

Thanks for your help !

**Comment by frranck** [comment]
Hi; I am have a similar project with multiple targets.
When i run 
fastlane test I get an error message:

NFO [2015-01-18 15:54:39.38]: Using './Snapfile'
DEBUG [2015-01-18 15:54:39.38]: xcodebuild -workspace xxx' -list
2015-01-18 15:54:40.797 xcodebuild[90191:2392002] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-6611/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7fcf4506e600 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
Object:   <IDESourceControlManager: 0x7fcf4484d590>
Method:   -loadRepositories
Thread:   <NSThread: 0x7fcf4242df90>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
DEBUG [2015-01-18 15:54:41.63]: Found available schemes: ["xxx", "xxxx"]
Found the following schemes in your project:
You can use 'scheme "Name"' in your Snapfile
--------------------------------------------
1) xxx
2) xxxx

INFO [2015-01-18 15:54:41.63]: Variable Dump:
INFO [2015-01-18 15:54:41.63]: {:LANE_NAME=>:test}
FATAL [2015-01-18 15:54:41.63]: Could not fetch available schemes: No such file or directory - test
FATAL [2015-01-18 15:54:41.64]: fastlane finished with errors
error: Could not fetch available schemes: No such file or directory - test. Use --trace to view backtrace
franck:fastlane franck$ 

PS: could you be more verbose in the use  'scheme "Name" syntax ?
is it in the Fastline file ? If I put it on top of it I get an error message.
Thanks

**Comment by KrauseFx** [comment]
Honestly I don't think it's correct to abuse Xcode targets to be different Apps, which is why I didn't have this in mind when creating `fastlane` and its tools. Why don't you use different Xcode projects with a shared code base?

Currently the only good solution is to write some Ruby code in your `Deliverfile`, `Fastfile` and `Appfile` to work with all your apps.

**Comment by frranck** [comment]
Hi, i'm in the same situation; 1 project with (a lot) of multiple targets. That sounds more easy to maintain to me. (?)

**Comment by nicolaslauquin** [comment]
There are many industrial&service scenarios when we have to create multiple target. I would prefer handle simple project but the reality is that we need to use this kind of solution and it si much more efficient to use target in one project and be able to run into the simulator the wanted project by switching scheme than having to close and find&open the corresponding Xcode proj. Also, imagine you have to adapte a class or a xib by target, in one Xcode project it is much more easy to navigate, update and refactor.

Anyway, I don't want to convince you, I just I think there is a need for that kind of support.

**Comment by KrauseFx** [comment]
Okay. What kind of solution would you suggest? How would your perfect 'interface' look like for `fastlane` and its tools?

**Comment by nicolaslauquin** [comment]
My vision would be (user point of view): 
- centralize all the configuration into one unique file "App" (so it would take care of the redondant information I mentioned before). 
- keep a default usage configuration so it still work the same but allow to create some specific configuration "AppXXX" (having an extension would be even better to associate it to its favorite edition tool with associate color syntax)
- then call the action just by be providing the config to load, like heroku command line for ex: ```fastline deploy --app AppXXX```

**Comment by KrauseFx** [comment]
To your points

1) If you init your project, the app_identifier should **only** be stored in the `Appfile`. Older versions of `deliver` also stored it in the `Deliverfile`, not any more.
2) Syntax highlighting can easily be enabled (at least on Sublime Text), since the file name is the extension, if there is no real extension
3) I like that, looks good. This reminds me of this issue: https://github.com/KrauseFx/CredentialsManager/issues/2

**Comment by nicolaslauquin** [comment]
1) I just did a test from scratch and **confirm** the issue. By doing a ```fastlane init```I got the ```app_identifier``` & ```apple_id``` stored in ```Deliverfile``` and ```Appfile```. I also checked that I'm up to date with fastlane & deliver. If you do not reproduce maybe we can open a new thread for that or I can send you my log by mail.
2) Ok for one but for multiple config app it wont anymore.
3) cool :)

**Comment by KrauseFx** [comment]
1) Oh, there must have been an error when merging, it's not there at https://github.com/KrauseFx/deliver/blob/master/lib/assets/DeliverfileExample, but still is at https://github.com/KrauseFx/deliver/blob/master/lib/assets/DeliverfileDefault, I'll push a fix
2) True, I just followed the convention for `Rakefile`, `Gemfile`, `Podfile`, `Makefile`, which all don't have an extension

**Comment by mhilscher** [comment]
:+1:

**Comment by nicolaslauquin** [comment]
Is this feature available ? Just tested with fastlane 0.7 the default ".env" file is well loaded but using a  specific config file ".env.production" is not working: 
```fastlane inhouse --env production```

```ruby
/Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/lib/fastlane/lane_manager.rb:38:in `cruise_lanes': undefined method `overload' for Dotenv:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-0.7.0/bin/fastlane:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
```
The command is working well with the default config file:
```fastlane inhouse```
```
INFO [2015-04-14 17:50:39.74]: -------------------------------------------------
INFO [2015-04-14 17:50:39.74]: --- Step: Verifying required fastlane version ---
INFO [2015-04-14 17:50:39.74]: -------------------------------------------------
INFO [2015-04-14 17:50:39.74]: fastlane version valid
INFO [2015-04-14 17:50:39.74]: Driving the lane 'inhouse'
ENV=ENV DEFAULT
INFO [2015-04-14 17:50:39.74]: fastlane.tools finished successfully 🎉
```

Files are present:
```ruby
ls -al fastlane/.env*
fastlane/.env
fastlane/.env.development
fastlane/.env.production
```

Did I missed something? I followed the doc available here : https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md

**Comment by KrauseFx** [comment]
@joshdholtz did the `.env` integration, maybe he can help? :smiley:

**Comment by thisiscrazy4** [comment]
So is it possible to have multiple sets of metadata? 1 for each target?

**Comment by agassiyzh** [comment]
Thank you for the great job. But I need this feature! I have 63 targets^_^

**Comment by KrauseFx** [comment]
@agassiyzh It is possible, have you tried using the `env` plugin? Do you need help on this? Do you have some Ruby experience? 

Maybe @joshdholtz can add a comment on this.

**Comment by agassiyzh** [comment]
@KrauseFx Thx, I will try this plugin.

**Comment by lisbakke** [comment]
For anyone looking to use fastlane with multiple apps in one xcode project:

1) make separate targets per app

2)  Make separate directories for metadata & screenshots. If you already have the apps in the appstore, run these

`deliver download_metadata --metadata_path fastlane/metadata-app1 --app_identifier com.yourcompany.App1`

and

`deliver download_screenshots --screenshots_path fastlane/screenshots-app1 --app_identifier com.yourcompany.App1`


3) Setup your Fastfile for multiple targets / dirs:

```
lane :app1_appstore do
  match(type: "appstore",
  app_identifier: "com.yourcompany.App1",
  git_url: "https://github.com/username/repos")

  gym(scheme: "App 1 Scheme")
  deliver(metadata_path: "fastlane/metadata-app1",
   screenshots_path: "fastlane/screenshots-app1",
   app_identifier: "com.yourcompany.App1")
end

lane :app2_appstore do
  match(type: "appstore",
  app_identifier: "com.yourcompany.App2",
  git_url: "https://github.com/username/repos")

  gym(scheme: "App 2 Scheme")
  deliver(metadata_path: "fastlane/metadata-app2",
   screenshots_path: "fastlane/screenshots-app2",
   app_identifier: "com.yourcompany.App2")
end
```

**Comment by drosenstark** [comment]
Thanks to this plug you can now update the plists directly for version numbers and build: https://github.com/SiarheiFedartsou/fastlane-plugin-versioning

I'm using it like this (inside a lane):

```
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Lite'
      )
```
and I  have one of those per lane (I'm just learning this stuff... I imagine I could DRY it out somehow?)

Big shout out to @SiarheiFedartsou for providing this necessary plug. Cool stuff, thank you!

**Comment by KrauseFx** [comment]
For people coming from Google, check out the [Guide to use fastlane for apps with multiple targets](https://docs.fastlane.tools/faqs/#multiple-targets-of-the-same-underlying-app).
