### ISSUE TITLE
[HOW-TO] Some explanations on signing/certs/provisioning are needed

### ISSUE THREAD

**Issue by PaulTaykalo** [KrauseFx/fastlane#85]
Hi there.  
Tried fastlane today, read all possible docs :)  Maybe not enough, and I missed somethings  
So here's few questions I want to clear out:  
Let's say we want to submit an app in the AppStore  
1.  Should we create an .ipa first, and then resign in by using `sigh` ?  
2.  Now in  provided example https://github.com/KrauseFx/fastlane-example/blob/master/fastlane/Fastfile#L50-L54 we have next code:  
```
lane :deploy do
  sigh
  deliver :skip_deploy
end
```
So `sigh` will get provision profile.  When this profile will be used? Will it be used by default on `deliver` action?  
3. What about signing identity? Should I specify it somewhere or there's a way when it will be resolved by cert/sigh? How should I pass those resolved params to other actions?  
4. Is there's a way to force Shenzhen(ipa) using team-id/provisioning/signing from Appfile/sigh resul, instead of Xcode?  

Thanks. Maybe more real-world examples of fastlane usages/schemes will help :)

**Comment by KrauseFx** [comment]
I agree with you, there should be a better example. Have you seen this setup? https://github.com/krausefx/fastlane-example

1) You first have to use `sigh` to get the provisioning profile. Then run `ipa` to build and sign the app
2) `deliver` will not do anything building/signing related automatically. Instead check out the available environment variables https://github.com/krausefx/fastlane#lane-context. You can use the 2 sigh values, in the `ipa` or `deliver` action
3) If you add `cert` to the top of the `Fastfile`, it will make sure to use the correct code signing identity in `sigh` automatically
4) Not sure what you mean?

If you have any ideas for improvements regarding documentation structure or missing information, please let me know or even submit a pull request updating it :+1: 

I hope I could help. I'll be working on a more advanced example setup.

**Comment by PaulTaykalo** [comment]
Yep, I saw https://github.com/krausefx/fastlane-example :) And some other examples from other guys :)
1) Ok. The reason I was asking - is that in example - ipa build is in before_all section ) So I wasn't sure, if I am missing something  
2) I was tried to do this in `Deliverfile`, but I failed (Well, I wasn't able get data from the context)  I added this step into `Fastlane` file. I edned up with this lane:    
```
lane :deploy do
 # Create all the screenshots!
 #snapshot

 # Make sure we have correct cert (Based on the values from Appfile)
  cert

 # Get correct provision profile (For ApppStore submission by default)
  sigh

 # Create ipa. identity and provision profile specified.
 # Provision profile was get from the last step via Actions.lane_context
  ipa({
    workspace: "MyApp.xcworkspace",
    configuration: "Release",
    scheme: "MyApp",
    identity: "iPhone Distribution: Ivan Ivanov (2323222322)",
    embed: Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH],
    verbose: "true"
  })

  # Deliver to the AppStore
  deliver :skip_deploy, :force
end
```
3.
4. I thought that values from Context such like SIGH_PROFILE_PATH and others will be passed to `ipa` action :) Now I know that they aren't  :)  

Thanks for explanation.

**Comment by KrauseFx** [comment]
Sorry for the delayed reply. I guess it would make sense to pass the profile path to the `ipa` action. The main problem here is, that only setting the profile path, does not make code signing work. You still have to set the code signing settings in your project.

Are there any more questions? Not sure if I missed something now :wink:

**Comment by PaulTaykalo** [comment]
Well, I thought that if put Singing Identitiy via  
```
identity: "iPhone Distribution: Ivan Ivanov (2323222322)",
```

and Profile via
```
    embed: Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH],
```

It should work. Well, It works that way. So thing is that I don't want to set code signing settings in the xcode project (At least, I want to have the way that it will use as much data from Fastlane configs)

**Comment by KrauseFx** [comment]
@dtrenz @joshdholtz What do you think? I guess it would make sense to automatically use the provisioning profile created/downloaded with `sigh` in both `xcodebuild` and `ipa`. 

Is there a reason against it?

**Comment by dtrenz** [comment]
WRT `xcodebuild` - You cannot use an uninstalled profile, so it would have to be installed on the build machine. `sigh` could do this if we implement this: https://github.com/KrauseFx/sigh/issues/58

**Comment by KrauseFx** [comment]
You've probably also seen https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md? 
I'll close this issue for now.
