### ISSUE TITLE
update_project_code_signing

### ISSUE THREAD

**Issue by edwardlafoy** [KrauseFx/fastlane#87]
ended up tracking this down: `File.write(path, p.gsub(/PROVISIONING_PROFILE = ".*";/, "PROVISIONING_PROFILE = \"#{udid}\";"))`

If no profile is selected this line won't exist

Thoughts on improving this?

**Comment by KrauseFx** [comment]
I agree, that's why this feature is not listed and documented anywhere yet. I haven't had time to work on a better, cleaner solution yet.

**Comment by KrauseFx** [comment]
I'll close this issue for now, as it's not officially supported right now.
