### ISSUE TITLE
Multiple "Branded" Targets of same underlying App

### ISSUE THREAD

**Issue by ehlersd** [KrauseFx/fastlane#88]
My first solution was to setup a separate Fastfile for each branded target....but I'm not seeing a way to specify the Fastfile to use with fastlane.

I'll be integrating shortly with Jenkins (just trying to get a manual process working first).

So, what would be your recommendation as to the best way to setup and utilitize fastlane?

Thanks in advance...

**Comment by joshdholtz** [comment]
Hey @ehlersd ,

I think I should be able to help you out here. 

## :warning: Official Answer :warning: 
A PR of mine was just merged into master a few days ago (I don't think the gem has been pushed out yet) that allows for multiple environments using `dotenv`.

Ex: `fastlane beta --env brand1` or `fastlane beta --env brand2`
Here is a gist with that example: - https://gist.github.com/joshdholtz/aa902e7ae28c1c0bea2a 

## :warning: Unofficial Answer :warning: 
Since this isn't a "released" feature yet, you can use a gem I wrote that adds this ability AND "brand" specific lanes if you need that - https://github.com/joshdholtz/fastlane-env-lanes

If you use `fastlane-env-lanes`, you would call `fastlane beta:brand1` instead of `fastlane beta --env brand1`. By using this gem, you can also decorate lanes for a specific brand.

```ruby
lane :beta do 
  # Only gets called if NO environment/brand is used
  puts "Why are you building without a brand?"
end

lane :beta, :brand1 do
  # Do some specific brand 1 stuff

  # Will load CONFIG and SCHEME from .env.<brand> where brand is brand1 because that is the environment specific lane we are in
    ipa({
        workspace: ENV['WORKSPACE'],
        configuration: ENV['CONFIG'],
        scheme: ENV['SCHEME'],
      })
end

lane :beta, :brand2 do
  # Do some specific brand 1 stuff

  # Will load CONFIG and SCHEME from .env.<brand> where brand is brand2 because that is the environment specific lane we are in
    ipa({
        workspace: ENV['WORKSPACE'],
        configuration: ENV['CONFIG'],
        scheme: ENV['SCHEME'],
      })

end
```

**Comment by ehlersd** [comment]
Awesome!  Great answer...thx!

**Comment by joshdholtz** [comment]
**Note:** The `fastlane-env-lanes` also loads the different `.env` files like my PR does. It just loads it differently `:brand` instead of `--env brand`.

Let me know if you need any more help with setting anything up! Always available to help :grin:

**Comment by KrauseFx** [comment]
@joshdholtz being awesome again :rocket: :grinning: How about putting this information into its own `.md` file in the repository and link to it from the README?

**Comment by joshdholtz** [comment]
@KrauseFx I can do that! :fist: Let's keep this issue open until I do that

**Comment by KrauseFx** [comment]
@joshdholtz I'll assign the issue to you :wink: 

I'll be working on the big refactoring of the `fastlane` documentation, so let's wait until that's finished.

**Comment by fatuhoku** [comment]
Would love to try this. Wow. iOS tooling has just got even more awesome. :beers:

**Comment by KrauseFx** [comment]
@joshdholtz I got asked about the multiple targets again, if you have some time it would really be cool to add a short explanation to the `docs` folder when you have some time :+1:

**Comment by jaroslavas** [comment]
I cannot make it load different snapshot config files. Am I doing something wrong?
.env.something:
```
LOCALIZED_CONFIGS_PATH="./fastlane/s_lt"
```

Fastfile (doesn't work):
```
lane :deploy do
  snapshot(
      snapshot_file_path: ENV["LOCALIZED_CONFIGS_PATH"],
    )
end
```

However, it works if I change it to:
```
lane :deploy do
  snapshot(
      snapshot_file_path: './fastlane/s_lt',
    )
end
```

Command: `fastlane deploy --env something`

It would also be very good if I could use ENV is Snapfile (and other config files) but it also doesn't seem to work.

**Comment by KrauseFx** [comment]
@jaroslavas Can you try replacing
```
LOCALIZED_CONFIGS_PATH="./fastlane/s_lt"
```

with 

```
export LOCALIZED_CONFIGS_PATH="./fastlane/s_lt"
```

**Comment by jaroslavas** [comment]
Still getting `Could not find './Snapfile'`

**Comment by KrauseFx** [comment]
I'll close this issue for now, thanks @joshdholtz for providing the documentation on how to solve this problem :+1:

**Comment by cytryn** [comment]
@joshdholtz and @KrauseFx , any news if **fastlane-env-lanes** is an official solution by now?

**Comment by joshdholtz** [comment]
@cytryn Oh man, I haven't update or ran the repo in a while 😇  I am not sure if it still works but definitely not an official solution 😉  

Your best bet would probably be to have a separate `.env` file for each branch `.env.brand1`, `.env.brand2`, etc, and switch on stuff in your lane to a different method or something.

**Comment by cytryn** [comment]
@joshdholtz oh ok. I will definitely try that! Thanks for the update.

**Comment by joshdholtz** [comment]
@cytryn No problem! I should also go mark that repo has no longer supported probably 😬

**Comment by KrauseFx** [comment]
Correct me if I'm wrong, but dotEnv is already integrated into fastlane, run `fastlane --help` for more information

**Comment by joshdholtz** [comment]
@KrauseFx Yup yup, it is! But @cytryn was asking about my environment specific lanes repo (https://github.com/joshdholtz/fastlane-env-lanes) that I made back in the day. I mentioned that I don't support that and the official solution would be to use the `.env.*` method that is built in already 👌

**Comment by fbensaid** [comment]
HI, is there any possible to use gym for a specific target ?
