### ISSUE TITLE
Step by step Jenkins setup for sending .ipa to Apple iTunes Connect Testflight

### ISSUE THREAD

**Issue by jonnyijapan** [KrauseFx/fastlane#89]
I am trying to get Fastlane/Deliver to upload a .ipa to Apple iTunes Connect Testflight... using Jenkins. I have tried lots of options back and forth and have yet to succeed. I can't say even that I got things working 100% from the command line, although I have sometimes seen better success there.

Some things:

- when using Jenkins, we shouldn't really have to use settings files like Deliverfile, Fastfile etc right? The settings files are honestly confusing to me - it would be easier to just specify the appid, appbundleidentifier and other things like path, ONCE, in the Jenkins build job settings. You only write that once anyway. As it is now, I'm not sure what setting goes where really, and what setting is eventually used. I do get lots of failed jobs because of Deliver/Fastlane not finding the path to the .ipa that it just had built (by Shenzhen's ipa).

Log of typical error where paths seems to be incorrect:

```
INFO [2015-03-04 13:20:57.51]: [SHELL OUTPUT]: Successfully built:
INFO [2015-03-04 13:20:57.51]: [SHELL OUTPUT]: /Users/me/.jenkins/jobs/myappfastlane/workspace/myapp.ipa
INFO [2015-03-04 13:20:57.51]: ---------------------
INFO [2015-03-04 13:20:57.51]: --- Step: deliver ---
INFO [2015-03-04 13:20:57.51]: ---------------------
WARN [2015-03-04 13:21:01.34]: You already set a value for key 'ipa'. Overwriting with new value '#<Proc:0x007f8e0d3994f8@(eval):46>'.
WARN [2015-03-04 13:21:01.34]: You already set a value for key 'beta_ipa'. Overwriting with new value '#<Proc:0x007f8e0d3983a0@(eval):59>'.
error: The directory /Users/me/.jenkins/jobs/myappfastlane/workspace/fastlane does not contain an Xcode project or workspace.. Use --trace to view backtrace
/Library/Ruby/Gems/2.0.0/gems/deliver-0.7.12/lib/deliver/deliverfile/dsl.rb:133:in `validate_ipa!': The given ipa file seems to be wrong. Make sure it's a valid ipa file. 
```

Note that the .xcodeproj file really exists in the /Users/me/.jenkins/jobs/myappfastlane/workspace/ directory above. I have no idea why it looks for it in /Users/me/.jenkins/jobs/myappfastlane/workspace/fastlane

So, I would very much appreciate if there was a step by step tutorial on how to set up a Jenkins job which from scratch builds a .xcodeproj and uploads to Apple Testflight. I don't need any job to send .ipa off for review. I also don't need anything that uploads screenshots... well not yet, I'd just like to get the automatic upload flow working.

**Comment by KrauseFx** [comment]
First off, the configuration files do make sense: You store that **once**, but not in the Jenkins job, but in a text file, which is stored in version control. You are then able to run `deliver` or `fastlane` from **any** computer, no matter if it's a CI-server or your local machine. 

If you've read through the docs, you probably also found this guide? https://github.com/KrauseFx/fastlane/blob/master/GUIDE.md Does that help you getting started? If not, how can I improve it? 

If you are using `shenzhen` to build your app, use this action instead: https://github.com/krausefx/fastlane#ipa
It will take care of transferring the path to the ipa from `shenzhen` to `deliver` - you don't need to do anything by yourself. It also describes how you have to change the `Deliverfile` to make it work.

There **will** be a way to use `deliver` and `snapshot` without configuration files, this will be possible once I got time to work on this issue: https://github.com/KrauseFx/fastlane/issues/45

Does that help you?

**Comment by KrauseFx** [comment]
Any updates on this @jonnyijapan?
