### ISSUE TITLE
Adding Application Services/Entitlements

### ISSUE THREAD

**Issue by nathanclevenger** [KrauseFx/fastlane#90]
Hello - 

I've got a full fastlane process in place, but there is one gap.  While PEM adds the Push Notification services in addition to just creating the certs, since my app uses a couple of additional application services, including iCloud and Apple Pay, if I don't manually add those prior to sigh executing then deliver fails due to invalid entitlements.  

First off, does fastlane have support for adding additional app services?  If not, where would the best place for extending things be?  With produce? PEM? sigh? Or create a whole new custom module/script?

Thanks in advance!

**Comment by KrauseFx** [comment]
Hey, that's right, the tools do not support the additional services you mentioned. Honestly, I can't tell you where this would belong to, probably `PEM` I guess.
I haven't used those services myself, so it's hard to tell for me. What do you suggest?

**Comment by nathanclevenger** [comment]
I was leaning towards PEM myself since it already adds the services for Push, and it seems like the right place in the overall workflow (after initial app id creation but before provisioning profile creation).  It will have to call `open_app_page` a second time because you get booted back to the list screen, as well as create an equivalent method to `fetch_cer_file` for the other services.  Finally, I'll need to modify `CertManager.run()` to accept additional `global_option` parameters for other services.  

In order for it to pulled back in though, some larger refactoring would probably be needed as I'm not sure a class called CertManager should manage additional services beyond push certs ... but that's your call.  Does this approach make sense?

**Comment by KrauseFx** [comment]
This is now possible using [produce](https://github.com/fastlane/produce) :+1:
